lerna/lerna

- lib/commands/publish.js
Same as https://github.com/babel/babel/pull/3129/files
> print the updated packages at the end for use in the changelog

- lib/commands/bootstrap.js
https://docs.npmjs.com/getting-started/scoped-packages
Scoped packages exist in `node_modules/@package-scope/package-name`, so using `mkdirp` will create the top level directory.
> use mkdirp instead of fs.mkdir to allow for scoped packages

- .eslintrc
- .travis.yaml
- README.md
- lib/commands/bootstrap.js
- lib/commands/index.js
- lib/commands/publish.js
- lib/commands/updated.js
- package.json
Fixes https://github.com/kittens/lerna/issues/12
New command: `lerna updated` (open to suggestions for the name: `diff, changed, dryrun`) 
Add linting config from babel
There's some duplicated code (utility functions) that I didn't bother to share.
We should probably just print out the changed packages by default anyway when you run `lerna publish` right? We currently print it at the end.
---
For babel https://github.com/babel/babel/compare/v6.4.4...master
> Command to show what packages will be updated

- lib/commands/updated.js
> Fix checkUpdatedPackages for repos without any tags

- lib/commands/bootstrap/linkDependencies.js
For some reason npm is installing right over the "linked" files, I'm not sure how this was working previously, but it seems that npm install should occur before linking.
> Fix linking

- bin/lerna.js
- package.json
`meow` uses `loud-rejection` which uses `signal-exit` which uses `process.on('SIGSEGV', ...)` which has this problem with `readline-sync` https://github.com/anseki/readline-sync/issues/29.
This PR unloads `signal-exit` after `meow` loads it.
> Fix for signal-exit hanging

- lib/commands/bootstrap/linkDependenciesForPackage.js
I'm not sure if there was any reason not to just symlink dependencies, but it causes issues like this: https://github.com/kittens/lerna/issues/11
> Symlink instead of creating files

- lib/utils/checkUpdatedPackages.js
If a package's name is `@org/foo`, the script was trying to diff on the folder at `packages/@org/foo`, which doesn't work for obvious reasons.
This change makes sure we're using the folder name (`foo` in this example) for the diff, not the package's name.
> Detect changes in packages with @ prefix

- lib/commands/publish/npmPublishAsTemp.js
- lib/commands/publish/npmPublishSemiAtomic.js
- lib/commands/publish/npmUpdateAsLatest.js
Thought I'd open this to discuss since we were talking about pre-releases elsewhere and theres no reason we need to override the "prerelease" tag.
> Switch to publishing temp tag instead of "prerelease"

- bin/lerna.js
- lib/commands/diff/index.js
- lib/commands/index.js
- lib/utils/checkUpdatedPackages.js
- lib/utils/gitGetLastTaggedCommit.js
- lib/utils/gitHasTags.js
- package.json
> Add lerna diff command

- lib/commands/publish/publishChangedPackages.js
Somehow `--follow-tags` doesn't always work.
https://github.com/kittens/lerna/issues/52
> Push version tags explicitly

- lib/commands/diff/index.js
- package.json
Without this patch, in OS X `bash`,  `default-pager` outputs a bunch of escaped color codes:
```
ESC[1mdiff --git a/packages/my-awesome-pkg/.npmignore b/packages/my-awesome-pkg/.npmignoreESC[m
ESC[1mnew file mode 100644ESC[m
ESC[1mindex 0000000..281df39ESC[m
ESC[1m--- /dev/nullESC[m
ESC[1m+++ b/packages/my-awesome-pkg/.npmignoreESC[m
ESC[36m@@ -0,0 +1,2 @@ESC[m
ESC[32m+ESC[mESC[32msrcESC[m
ESC[32m+ESC[mESC[32mtestESC[m
ESC[1mdiff --git a/packages/my-awesome-pkg/README.md b/packages/my-awesome-pkg/README.mdESC[m
ESC[1mnew file mode 100644ESC[m
ESC[1mindex 0000000..b326138ESC[m
ESC[1m--- /dev/nullESC[m
ESC[1m+++ b/packages/my-awesome-pkg/README.mdESC[m
ESC[36m@@ -0,0 +1 @@ESC[m
ESC[32m+ESC[mESC[32m# my-awesome-pkgESC[m
```
Providing `less -R` as the pager makes it display the correct …
> Fix diff output colors

- .eslintrc
- package.json
Fixes eslint errors from a deprecated eslint rule space-after-keywords.  Check out [the docs](http://eslint.org/docs/rules/space-after-keywords) for more details
```
dougwade code/lerna ‹master› » eslint .
/Users/doug.wade/code/lerna/bin/lerna.js
3:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing  space-after-keywords
/Users/doug.wade/code/lerna/index.js
1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing  space-after-keywords
/Users/doug.wade/code/lerna/lib/commands/bootstrap/bootstrapPackages.js
1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing  space-after-keywords
/Users/doug.wade/code/lerna/lib/commands/bootstrap/index.js
1:1  error  Rule 'space-after-keywords' was removed and …
```
> Fix eslint error from deprecated rule space-after-keywords

- bin/lerna.js
- lib/commands/bootstrap/bootstrapPackages.js
- lib/commands/bootstrap/index.js
- lib/commands/bootstrap/linkDependenciesForPackage.js
- lib/commands/diff/index.js
- lib/commands/index.js
- lib/commands/init/index.js
- lib/commands/publish/index.js
- lib/commands/publish/publishChangedPackages.js
- lib/init.js
- lib/utils/packageUtils.js
Resolves #47
This will simplify a lot of things that I want to do soon like `lerna.json`, then once `lerna.json` is in we won't have to use the `cwd` anymore and we can recursively look up the tree to find a `lerna.json` or `package.json` with a `lerna` field.
This also improves the experience of `--independent`, see the warning in `lib/init.js`.
```
`VERSION` does not exist, have you run `lerna init`? Or maybe you meant to run this with `--independent` or `-i`?
```
> Create lerna init command

- lib/commands/bootstrap/hasMatchingDependency.js
- lib/commands/bootstrap/installExternalPackages.js
- lib/commands/bootstrap/linkDependencies.js
- lib/commands/bootstrap/linkDependenciesForPackage.js
- lib/utils/logger.js
- lib/utils/npmUtils.js
- package.json
Fixes #79 and #59
I also fixed a problem with the logger and an issue with how we match dependencies that should be "linked".
This allows you to create new dependencies that don't exist on npm yet.
This might also open up the possibility of doing actual symlinks because we are explicitly installing only external deps.
> Install only external dependencies during bootstrap

- src/commands/InitCommand.js
`lerna init` with `2.0.0-beta.7` fails in an empty repository:
```
$ lerna init
Lerna v2.0.0-beta.7
Updating package.json.
Errored while running InitCommand.execute
TypeError: Cannot read property 'version' of undefined
at InitCommand.ensureLernaJson (/usr/local/lib/node_modules/lerna/lib/commands/InitCommand.js:111:27)
at InitCommand.execute (/usr/local/lib/node_modules/lerna/lib/commands/InitCommand.js:58:12)
at InitCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:148:21)
at /usr/local/lib/node_modules/lerna/lib/Command.js:133:15
at /usr/local/lib/node_modules/lerna/lib/Command.js:157:13
at InitCommand.initialize (/usr/local/lib/node_modules/lerna/lib/commands/InitCommand.js:51:7)
at InitCommand._attempt (/usr/local/lib/node_modules/lerna/lib/Command.js:148:21)
at …
```
> fix(init): lerna.json does not exist in empty repository

- src/GitUtilities.js
- src/commands/DiffCommand.js
- test/DiffCommand.js
- test/GitUtilities.js
`lerna diff` on a repository without any commits fails due to:
```console
$ lerna diff
Lerna v2.0.0-beta.7
Independent Versioning Mode
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Errored while running DiffCommand.initialize
Error: Command failed: git rev-list --max-parents=0 HEAD
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
at checkExecSyncError (child_process.js:470:13)
at Object.execSync (child_process.js:510:13)
at Function.execSync (/usr/local/lib/node_modules/lerna/lib/ChildProcessUtilities.js:37:38)
at …
```
> fix: `lerna diff` for repositories without commits

- package.json
- src/GitUtilities.js
- src/Repository.js
- src/UpdatedPackagesCollector.js
- src/commands/PublishCommand.js
- src/commands/UpdatedCommand.js
- test/UpdatedCommand.js
Basically:
```
$ git diff --name-only
packages/package-a/src/source-file.js
packages/package-b/test/test-file.js
```
Then use `minimatch` to filter out files in the diff that `lerna.json#publishConfig.ignore` is ignoring
> Add publishConfig and ignore option for publishing

- src/commands/InitCommand.js
I think we want this as a devDep right? Also do we want to add `^` in front as well?
Also, this means we don't want users to use it as a global npm package?
cc @thejameskyle
> lerna init should add lerna as a devDependency

- src/commands/InitCommand.js
`lerna init` is currently overriding `publishConfig` because it isn't included in the init process.
Rather than whitelisting every property I'm just going to accept additional properties.
> Allow additional properties in lerna init

- .editorconfig
- .eslintrc
This adds an eslint rule to make sure we use proper indentation.
cc @thejameskyle
> chore: enforce proper indentation

- src/UpdatedPackagesCollector.js
- test/UpdatedCommand.js
- test/fixtures/UpdatedCommand/circular/lerna.json
- test/fixtures/UpdatedCommand/circular/package.json
- test/fixtures/UpdatedCommand/circular/packages/package-1/package.json
- test/fixtures/UpdatedCommand/circular/packages/package-2/package.json
- test/fixtures/UpdatedCommand/circular/packages/package-3/package.json
- test/fixtures/UpdatedCommand/circular/packages/package-4/package.json
https://github.com/lerna/lerna/issues/128
Probably not the best but it seems to work on Babel (where the max callstack error happened).
Examples:
babel-types -> all packages updated
babel -> babel only (no other dependencies)
stage-3 preset -> stage-0, stage-1, stage-2, stage-3
> Add cache for checking updated dependencies

- README.md
I went ahead and added some more stuff and merged the 2.x readme changes. How do we want to keep around the old docs since (some?) people might be using 1.x still.
@thejameskyle 
(Also, when do we want to get out of beta, and should make 2.x the default)
```bash
$ npm view lerna dist-tags
{ latest: '1.1.2', prerelease: '2.0.0-beta.13' }
```
> Link to 1.x docs

- bin/lerna.js
- src/commands/PublishCommand.js
This adds a `--confirm` flag for usage in CI that automatically answers the publish confirmation prompt.
```
lerna publish --canary --confirm
Lerna v2.0.0-beta.9
Independent Versioning Mode
Publishing canary build
Checking for updated packages...
Changes:
- component-a: 0.0.3 => 0.0.3-canary.2c247805
- component-b: 0.0.2 => 0.0.2-canary.2c247805
- component-c: 0.0.2 => 0.0.2-canary.2c247805
Assuming confirmation.
Publishing packages to npm...
Reseting git state
Successfully published:
- component-a@0.0.3-canary.2c247805
- component-b@0.0.2-canary.2c247805
- component-c@0.0.2-canary.2c247805
```
> Implements #134 - add a --confirm flag

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
Fixes #166 
Could potentially be an option in lernaConfig with a default of alpha? I think its fine to do just this atm though.
This is breaking change if people have been using it before though?
> Use alpha version instead of canary

- .eslintrc
http://eslint.org/docs/rules/space-infix-ops
Remarkably, this just passes.  No violations.  Nice work, Lerna!
> Add "space-infix-ops" eslint rule

- README.md
- src/commands/ExecCommand.js
Adds information about `lerna exec` the `--scope` flag and fixes `lerna exec` to respect `--concurrency`.
@hzoo PTAL
refs #152
> Docs update exec run

- src/ChildProcessUtilities.js
If the error from `child.exec` is just that the child process emitted too much
on stderr, then that stderr output is likely to be useful.  Emit as much as
possible, with a warning that it's partial output.
> Emit partial stderr output from child on maxBuffer exceeded

- README.md
- bin/lerna.js
- src/commands/PublishCommand.js
- test/PublishCommand.js
Have Lerna update all versions and dependencies where required in `package.json` files without actually publishing the changes to NPM.
This is useful for publishing manually, which is necessary to do periodically to get README updates to show up on npmjs.com (until https://github.com/npm/newww/issues/389 is resolved).
This is a workaround for #64.
This was proposed in #127.
> Add --skip-npm flag

- README.md
This was requested [here](https://github.com/lerna/lerna/pull/198#discussion_r66518956).
> Mention `--skip-git` README-publishing workaround in README

- README.md
- bin/lerna.js
- src/commands/CleanCommand.js
- src/index.js
- test/CleanCommand.js
- test/fixtures/CleanCommand/basic/lerna.json
- test/fixtures/CleanCommand/basic/package.json
- test/fixtures/CleanCommand/basic/packages/package-1/package.json
- test/fixtures/CleanCommand/basic/packages/package-2/package.json
Removes the `node_modules` directory from all packages.
Closes #195.
Or would [`lerna nuke`](https://github.com/lerna/lerna/issues/195#issuecomment-224743936) be better? 👹
> Add `lerna clean` command

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/cold/lerna.json
- test/fixtures/BootstrapCommand/cold/package.json
- test/fixtures/BootstrapCommand/cold/packages/package-1/package.json
- test/fixtures/BootstrapCommand/cold/packages/package-2/package.json
- test/fixtures/BootstrapCommand/warm/lerna.json
- test/fixtures/BootstrapCommand/warm/package.json
- test/fixtures/BootstrapCommand/warm/packages/package-1/node_modules/external/package.json
- test/fixtures/BootstrapCommand/warm/packages/package-1/package.json
- test/fixtures/BootstrapCommand/warm/packages/package-2/package.json
This makes bootstrap in a repo that has been bootstrapped previously much faster.
This addresses #125.
> Only install missing external dependencies during bootstrap

- README.md
- src/Repository.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/basic/lerna.json
We'd like to add flow annotations to Jest (tomorrow at our internal hackathon :) ).
Flow only looks at files with an `@flow` annotation. If a file doesn't have it, it skips it entirely and doesn't infer types for that file. When using lerna, even if the specific package is flow typed, because the proxy file in between in `node_modules` doesn't have `@flow`, the package won't be typed across boundaries.
This diff adds a `linkedFiles.prefix` option to add such annotations (or anything else, really) to such linked files.
I also added it to the README and updated a test for it. I didn't want to duplicate too much test code and add more fixtures, so I added it to an existing bootstrap test which should be good enough. Let me know if you'd like a separate test, however.
> Add `linkedFiles.prefix` option to add @flow annotations to the linked files.

- src/NpmUtilities.js
- test/BootstrapCommand.js
This output was getting discarded, anyway.  This avoids buffering it
(and potentially failing due to exceeding `maxBuffer`).
This fixes #213.
> Expicitly ignore output from `npm install`

- README.md
- bin/lerna.js
- src/PackageUtilities.js
- src/Repository.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/PackageUtilities.js
* Added `ignore` flag to CLI
* Check `bootstrapConfig.ignore` key in `lerna.json`
The CLI flag will override the `bootstrapConfig` option in `lerna.json`. Both the flag and the option accept a glob pattern of package names to ignore.
this is the new PR from my company's github org
> Add option to ignore packages when bootstrapping (fixes #117)

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
> Fix bootstrap install to use quotes around versions

- .travis.yml
- package.json
- src/ChildProcessUtilities.js
- test/UpdatedCommand.js
- test/_initFixture.js
Reverts lerna/lerna#220
https://github.com/nodejs/LTS - v0.10 maintenance is going to be over soon (same with 0.12) so it seems ok to drop support. We're in beta and a new tool as well
> Revert "Use sync-exec for node 0.10"

- README.md
That [last commit](https://github.com/lerna/lerna/pull/173/commits/372de5aa7c433d48da2bb44ca8578f912ef9a6a3) in #173 updated _one_ reference to package name, but missed another. 😅
> Consistent naming in README `import` section

- .travis.yml
- package.json
- src/ChildProcessUtilities.js
- src/commands/ImportCommand.js
- test/ImportCommand.js
- test/UpdatedCommand.js
- test/_initExternalFixture.js
- test/_initFixture.js
Node's [0.10 maintenance window](https://github.com/nodejs/LTS/blob/ce364a94b0e0619eba570cd57be396573e1ef889/schedule.png) expires in October.  Lerna should probably support it until then.
Also babel still supports it, so... 😆
> Re-introduce node 0.10 support

- src/commands/ImportCommand.js
This allows it to skip duplicate commits due to merge history.
This fixes #251.
> Let `git am` to fall back to three way merge during import

- src/ChildProcessUtilities.js
- src/NpmUtilities.js
- test/BootstrapCommand.js
> Emit stderr output from `npm` on bootstrap failure

- src/NpmUtilities.js
- src/commands/ExecCommand.js
- test/ExecCommand.js
- test/RunCommand.js
Useful for passing some configuration to tasks, like: `DIALECT=bar lerna run foo`
> run/exec: forward env variables

- src/commands/ImportCommand.js
- test/ImportCommand.js
Noticed while investigating #251 that error handling during the `execute` phase of the import command is poor.  This patch includes the following:
- No "Import complete!" message on failure
- Emit an error message with:
- All stderr output from `git am`
- The sha of the failed commit
- Intent to roll back
- Abort the failed `git am` and roll back to previous HEAD
- Don't allow import with uncommitted changes
Error output looks like:
> Improved error handling for the import command

- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/basic/packages/package-1/index.src.js
- test/fixtures/BootstrapCommand/basic/packages/package-1/package.json
Bootstrap should leave packages with usable dependencies.
If a dependency's `prepublish` script hasn't been run then it may not be `require()`-able.
> [The prepublish script will be run before publishing, so that users can consume the functionality without requiring them to compile it themselves. In dev mode (ie, locally running npm install), it'll run this script as well, so that you can test it easily.](https://docs.npmjs.com/files/package.json#devdependencies)
Furthermore, if packages use each other _during_ `prepublish`, then order of execution is important.
This, for example, is not a viable workaround:
```bash
$ lerna bootstrap
$ lerna run prepublish
```
Because a package may require a not-yet-built module due to incorrect order of execution.
This patch runs each package's …
> Run `prepublish` scripts during bootstrap

- lib/progress-bar.js
Fixes the progress bar not working and erroring when spawning lerna because stdout is not a TTY when called from process.spawn, node-progress was failing when trying to call this.stream.clearLine
> Fixes the progress bar not working

- README.md
The ability to factor common `devDependencies` out into the repo root is a
useful feature of Lerna.  Add a section to the README explaining the benefits
and caveats.
This was suggested in https://github.com/boennemann/alle/issues/1.
> Add a note about common devDependencies to README

- src/FileSystemUtilities.js
- src/commands/BootstrapCommand.js
- test/fixtures/BootstrapCommand/basic/packages/package-2/package.json
- test/fixtures/BootstrapCommand/basic/packages/package-3/package.json
- test/fixtures/BootstrapCommand/basic/packages/package-4/package.json
This is an attempt to get @rygine's #192 merged by trimming extraneous changes
to slim down the diff.
None of the following changes reflect _disapproval_ of the code in the
original PR.  This is pure change-set minimization.
Changes:
- Revert incidental code reorganization in:
- `createLinkDependency`
- `linkDependencies`
- `createLinkedDependencyFiles`
- Thin interface of `createBinaryLink`
- Eliminate unused optional argument to `FileSystemUtilities.symlink`
- Simplify `createBinaryLink`
- Remove jsdoc comments
With this patch the diff against master is now pure addition.
@hzoo, @thejameskyle - If this looks good to you, please merge #192 _first_, to preserve authorship.  This will apply cleanly on top of that with a rebase.
> Diff compaction for package binary PR

- src/commands/BootstrapCommand.js
The dependency-order bootstrap scheduler introduced in #250 assumes that the
dependency graph is acyclic.  This turns out not to be a valid assumption, as
demonstrated in #299.
This patch falls back to the package with the most dependents when bootstrap
is blocked by a cycle in the dependency graph.  It issues a warning that graph
cycles may cause instability during bootstrap if dependencies are used during
`prepublish`.
> Handle dependency graph cycles during bootstrap

- src/ChildProcessUtilities.js
- src/Command.js
- test/RunCommand.js
- test/_fakeChild.js
I ran into this with `lerna run test`.  I have one test that fails quickly and another _expensive_ test that keeps on chugging after lerna exits.
With this patch I get this:
Then I can just `CTRL-C` instead of having to track down orphaned children and kill them.
> Wait for child processes to exit before exiting from parent

- src/commands/UpdatedCommand.js
This is helpful for figuring out what will actually be published.
Goes along with #321.
Looks like:
> Indicate private modules in output from `updated`

- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/fixtures/PublishCommand/normal/packages/package-5/package.json
Private modules may need to be updated during publish to keep their dependency
versions up to date, but they can't actually be published to the npm registry.
This addresses #303 (and #286 also, I think?)
> Don't try to publish private modules

- README.md
If you use lerna without the intention to publish your packages on npm, it might be unclear, which packages are affected by `lerna publish`.
We use lerna internally and use `lerna publish` with `--skip-npm` to manage git releases. We accidentally had some of our packages marked as private, from when they were standalone. `lerna pubslish` and `lerna ls` gave us quite the headache, because it listed/published only "some" of our packages, though linking the packages worked just fine (`bootstrap`).
> docs(lerna-publish): add hint to indicate which packages will be published

- src/ChildProcessUtilities.js
Turns out this wasn't supported until node v0.10.18.
https://github.com/nodejs/node/commit/f91b047891c0deb402220b385f166c08edcb0591
> Don't chain off of `stream.setEncoding(...)`

- src/Package.js
- test/BootstrapCommand.js
- test/Package.js
- test/fixtures/BootstrapCommand/peer/lerna.json
- test/fixtures/BootstrapCommand/peer/package.json
- test/fixtures/BootstrapCommand/peer/packages/package-1/package.json
- test/fixtures/BootstrapCommand/peer/packages/package-2/package.json
**Reason**
`lerna bootstrap` deviates from the [peerDependencies behaviour][npmpeerdeps] found in `npm install` (npm@3)
---
This patch removes peerDependencies from `bootstrap`'s list of installable dependencies per package.
Tests added 💥 
Related:
- #160 First reporting the peer dep behaviour issue in `lerna bootstrap`
- #334 Discussion for lifting shared external packages to root directory (would be great for peer deps)
[npmpeerdeps]: https://docs.npmjs.com/files/package.json#peerdependencies
> Change bootstrap command to not install peerDependencies

- src/commands/ImportCommand.js
- test/ImportCommand.js
fixes #345 
`git format-patch` outputs something like this for renames:
```
diff --git a/test1 b/test2
similarity index 100%
rename from test1
rename to test2
```
Previously `ImportCommand` would properly replace `a/test1` and `a/test2` with the proper relative paths, but would not replace the "rename" lines, which would cause an error.
> Fix importing commits which renamed files (Fixes #345)

- package.json
- test/PublishCommand.js
This along with #348 makes all tests pass on Windows.
> Normalize newlines in lerna.json in publish tests

- README.md
- package.json
- src/FileSystemUtilities.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
Fixes #339 and allows `lerna bootstrap` to run as a regular user on Windows.
For the record, the calls to `normalize()` are there to remove any trailing slashes from the paths (I forget which had them - the `path.join` results or the `readlinkSync` results).
> Use unprivileged alternatives to symlinks on Windows

- src/FileSystemUtilities.js
- src/GitUtilities.js
- src/NpmUtilities.js
- src/logger.js
The decorator spec requires that a function decorator either:
- returns a new /descriptor/ for the property, or
- changes the fields on the given descriptor
The logify* methods instead returned a new function implementation, which
is not correct, and caused the decorations to be silently ignored.
decorator spec: https://github.com/wycats/javascript-decorators#detailed-design
function decorator example: https://github.com/jayphelps/core-decorators.js/blob/master/src/deprecate.js
This commit changes logifySync and logifyAsync in the following ways:
- they now have no return value, and instead modify the descriptor
- they now must be called with no arguments so they can properly capture
the `this` value (without this, the function cannot find the logger instance)
- they now log at 'verbose', …
> Fix logifyAsync, logifySync decorators.

- README.md
https://github.com/lerna/lerna/pull/237 removed `linkedFiles` feature.
> Remove `linkedFiles` from README

- README.md
Add empty line becouse of not be ordered list on GitHub Markdown preview.
It will not happen on Atom Editor Markdown Preview.
> Fix ordered list syntax at README.md

- README.md
- src/PackageUtilities.js
- src/Repository.js
- src/commands/InitCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/extra/lerna.json
- test/fixtures/LsCommand/extra/lerna.json
Updated to address the discussion at https://github.com/lerna/lerna/pull/365#pullrequestreview-3931001
> Expect packages config to be array of globs to directories containing package.json

- src/commands/InitCommand.js
The current implementation assumes lerna to be a devDependency. Our project has lerna as a dependency (because the shell project is only build tools, which makes lerna a dependency in that sense). However when we run `lerna init` (after a lerna upgrade for example), lerna gets added to the `devDependencies` and not updated in the dependencies. This PR fixes this.
> [Feature] lerna init assumes lerna in devDependencies

- src/FileSystemUtilities.js
If the symlink exists, the check in BootstrapCommand will incorrectly fail despite the path being correct as pkgDependencyLocation symlink path is returned without trailing slash, whereas the dependencyPackage location does have the trailing slash.  Only effects Windows.
> Resolve symlink path on windows to add trailing slash.

- README.md
The example for creating an independent mode lerna project said "lerna publish --i" instead of "init". This is a bit confusing. It might make sense to add the "independent" option as an example under the "publish" command additionally, if required.
> Fix confusing example in README

- FAQ.md
Be explicit that `<package>` represents a local path rather than a URL as described here https://github.com/lerna/lerna/issues/269
> Update FAQ for import

- README.md
- package.json
- src/Command.js
- src/PackageUtilities.js
- src/Repository.js
- src/UpdatedPackagesCollector.js
- src/commands/DiffCommand.js
- src/commands/InitCommand.js
- src/commands/PublishCommand.js
- src/commands/UpdatedCommand.js
- test/BootstrapCommand.js
- test/Command.js
- test/DiffCommand.js
- test/LsCommand.js
- test/PackageUtilities.js
- test/fixtures/BootstrapCommand/extra/lerna.json
- test/fixtures/BootstrapCommand/extra/package-3/cli1.js
- test/fixtures/BootstrapCommand/extra/package-3/cli2.js
- test/fixtures/BootstrapCommand/extra/package-3/package.json
- test/fixtures/BootstrapCommand/extra/package.json
- test/fixtures/BootstrapCommand/extra/packages/package-1/index.src.js
- test/fixtures/BootstrapCommand/extra/packages/package-1/package.json
- test/fixtures/BootstrapCommand/extra/packages/package-2/cli.js
- test/fixtures/BootstrapCommand/extra/packages/package-2/package.json
- test/fixtures/BootstrapCommand/extra/packages/package-4/package.json
- test/fixtures/LsCommand/extra/lerna.json
- test/fixtures/LsCommand/extra/package-3/package.json
- test/fixtures/LsCommand/extra/package.json
- test/fixtures/LsCommand/extra/packages/package-1/package.json
- test/fixtures/LsCommand/extra/packages/package-2/package.json
Just needs documentation. @nruhe you said you were interested? I would now, but I'm working on documentation for another project about to be open sourced
> [Feature] Add support for configurable package locations

- src/commands/BootstrapCommand.js
Spoiler, it's `warn`, not `warning`. (Porting fix from https://github.com/asini/asini/pull/17)
When upgrading an existing lerna repo that has bootstrapped dependencies from _before_ they became symlinks (I was upgrading from beta-24, in this instance), this not-so-friendly error results:
```shell
$ lerna bootstrap
Lerna v2.0.0-beta.31
Independent Versioning Mode
Bootstrapping 14 packages
Preinstalling packages
Installing external dependencies
Symlinking packages and binaries
${NVM_DIR}/versions/node/v6.9.2/lib/node_modules/lerna/lib/commands/BootstrapCommand.js:301
_this6.logger.warning(dependency + " is already installed for " + filteredPackage.name + ". " + "Replacing with symlink...");
^
TypeError: _this6.logger.warning is not a function
at …
```
> Use correct logger method for warnings

- src/Command.js
- src/logger.js
- src/progressBar.js
- test/_env.js
fixes #406 
Previously, when running Lerna with `NODE_ENV` set to "test", it would output nothing to stdout and always exit with a code of `0`. Now the output and exit code will not be suppressed.
> Change testing NODE_ENV to "lerna-test" (Fixes #406)

- src/ChildProcessUtilities.js
As per https://nodejs.org/api/child_process.html#child_process_event_close, the close event is emitted when the stdio streams of a child process have been closed, which is important as there is a chance for race condition when process has exited (process's exit event), but collecting  stderr hasn't been finished yet (stderr stream's done event). Using close event seems to be pretty common if you look at implementations of child_process.exec, grunt.utils.spawn, etc.
> Use close event to wait for spawned processes to finish

- src/commands/PublishCommand.js
- test/PublishCommand.js
This allows for users to opt to use exact versions of cross-dependencies when publishing.
> Add support for hidden '--exact' flag

- README.md
In the website, the `packages` folder exists in the [_Getting Started_](https://lernajs.io/#getting-started) section, but it doesn't exist in the README.md file in the repository.
> Add missing folder in README.md

- README.md
- bin/lerna.js
- src/commands/PublishCommand.js
- test/PublishCommand.js
This commit introduces a new option for publish: --message. When given
this option, lerna will use the supplied message as the commit message
when it commits updates while publishing. If no message flag is
specified, the default hard-coded messages are used.
Resolves #395
> Add --message option for custom commit msgs when publishing

- src/PromptUtilities.js
This commit uses message which is passed to the static method input() as an argument. Previously, string 'Enter a custom version' was being used instead of message passed from its caller.
See [src/commands/PublishCommand.js:222](https://github.com/lerna/lerna/blob/master/src/commands/PublishCommand.js#L222) for usage of input()
> use message passed as argument to the static method input() in PromptUtilities

- lerna.json
This technically makes Lerna a Lerna repo, but it doesn't tackle any of the substantive changes from #174.
> Add configuration for `lerna-changelog`

- src/commands/PublishCommand.js
Fixes [this reported bug](https://lernajs.slack.com/files/diogo/F3W4R0JRF/-.txt) that is not allowing people using `2.0.0-beta.33` to publish packages.
Config flags shouldn't be undefined for publish.
> [CRITICAL] Publish command is broken for 2.0.0-beta.33

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
This fixes an issue where `lerna bootstrap --scope foo --include-filtered-dependencies`
was only running `prepublish` in the specifically-named scoped packages, rather than in
all transitive dependencies. (e.g., `foo` gets prepublish run, but if `foo` depends on `bar`, `bar` doesn't get prepublished).
I think this was maybe just missed in #390?
> Fixes issue: prepublish not running in dependencies with `--scope --include-filtered-dependencies`

- package.json
- src/PromptUtilities.js
- yarn.lock
Reduces dependencies by one.
I didn't see it specified in `engines`, but since [Travis only runs on `node>=4`](https://github.com/lerna/lerna/blob/master/.travis.yml#L10-L13), I figured `node@0.12.0` support was dropped.  If that's wrong, I'll close this.
> Upgrade `inquirer` dependency

- src/commands/CleanCommand.js
- test/CleanCommand.js
- test/fixtures/CleanCommand/include-filtered-dependencies/lerna.json
- test/fixtures/CleanCommand/include-filtered-dependencies/package.json
- test/fixtures/CleanCommand/include-filtered-dependencies/packages/package-1/package.json
- test/fixtures/CleanCommand/include-filtered-dependencies/packages/package-2/package.json
- test/fixtures/CleanCommand/include-filtered-dependencies/packages/package-3/package.json
Sorry about the horkage in the CleanCommand test. I moved the existing tests into their own `describe`, which caused whitespace changes, which... you can see the results.
> [clean] Support --include-filtered-dependencies flag

- .npmignore
- package.json
Fixes #516 
Looks to me like only bin/lib are needed (well, and package.json, CHANGELOG.md, LICENSE, README.md which are included by default)--so I switched out the `.npmignore` for a 2 entry `files`.
Edit: ^ undid the switch
I wasn't 100% sure about the yarn files; looks like the answer is don't publish them: see the last line of https://yarnpkg.com/en/docs/yarn-lock
I sanity checked with:
```
npm pack
tar xvf lerna-2.0.0-beta.33.tgz
cd package
ls -a  # => bin  CHANGELOG.md  lib  LICENSE  package.json  README.md
./bin/lerna.js # => prints help message
```
Cuts the package size in half :) 
```
$ du -b --apparent-size lerna-2.0.0-beta.33.tgz after.tgz             
72884   lerna-2.0.0-beta.33.tgz
33347   after.tgz
```
> Don't include unnecesary files in the npm package

- package.json
- yarn.lock
`object-assigned-sorted@2.0.1` drops the `object-assign` dependency.
> Bump `object-assigned-sorted`.

- package.json
- yarn.lock
Bumps `signal-exit` from `^2.1.2` to `^3.0.2`.  This way, it will dedupe with the version used by `loud-rejection`.  I don't think `lerna` was doing anything with SIGPROF, so it shouldn't be breaking.
> Bump `signal-exit`.

- src/FileSystemUtilities.js
Improves performance of `lerna clean` on large projects.
I fully recognize that this could be contentious, but I also didn't see an issue/conversation about it, so I figured it couldn't hurt to submit. This shaves ~19s (21% improvement!) off our monorepo build with `lerna`:
```
lerna clean --concurrency 6 --loglevel debug --yes  81.95s user 114.90s system 281% cpu 1:10.00 total
lerna clean --concurrency 6 --loglevel debug --yes  78.54s user 117.52s system 282% cpu 1:09.41 total
lerna clean --concurrency 3 --loglevel debug --yes  71.90s user 108.78s system 249% cpu 1:12.42 total
#internal rimraf
lerna clean --concurrency 6 --loglevel debug --yes  55.34s user 85.40s system 156% cpu 1:29.84 total
lerna clean --concurrency 1 --loglevel debug --yes  59.14s user 94.69s system 142% cpu 1:48.14 …
```
> Proposal: Spawn child process for rimraf

- package.json
- src/PackageUtilities.js
- yarn.lock
Drops `isarray` for `Array.isArray`.
> Drop `isarray`.

- README.md
Forgot to update the README when I added this a couple days back.
> Updating README: `clean` respects --include-filtered-dependencies

- package.json
- yarn.lock
Bumps `cross-env` from `^1.0.8` to `^3.1.4`.  `cross-env@3.0.0` drops the `lodash.assign` dependency.
It's a devDependency, so it's not terribly important.
> Bump `cross-env`.

- src/FileSystemUtilities.js
On NPM3, `rimraf` is being hoisted to the parent node_modules, so `exec("npm bin", {cwd: __dirname},` produces the wrong bin path. So in the current version of lerna, the clean command is broken.
I've simplified the logic to use `require.resolve`, which will work regardless of where rimraf is. This should also be faster as well!
Fixes bug introduced in: https://github.com/lerna/lerna/pull/547
> Fix rimraf bin resolution

- src/NpmUtilities.js
The degenerate case of `NpmUtilities.installInDir` is an install of no packages.  The _behavior_ in this case was previously to run an `npm install` with no arguments, which installs _everything_.
This patch short-circuits out of the noop.
> Short-circuit out of install with no packages

- src/FileSystemUtilities.js
These noop rimrafs were cheap before #547, but they're expensive now.
> Check if directories exist before removing during hoist

- .gitignore
- .npmignore
- CONTRIBUTING.md
- package.json
In response to https://github.com/lerna/lerna/pull/574#issuecomment-277347146
> Add coverage report

- src/FileSystemUtilities.js
- src/NpmUtilities.js
- test/BootstrapCommand.js
- test/FileSystemUtilities.js
- test/NpmUtilities.js
Use temporary package.json files.
This is groundwork for:
- Pluggable npm clients (yarn).
- A `lerna upgrade` command.
This is a port of https://github.com/asini/asini/pull/45.  Please see original PR commentary during review.
> Install with no arguments

- README.md
- src/Command.js
- src/commands/BootstrapCommand.js
- src/commands/CleanCommand.js
- test/ExecCommand.js
- test/LsCommand.js
- test/RunCommand.js
- test/fixtures/ExecCommand/include-filtered-dependencies/lerna.json
- test/fixtures/ExecCommand/include-filtered-dependencies/package.json
- test/fixtures/ExecCommand/include-filtered-dependencies/packages/package-1/package.json
- test/fixtures/ExecCommand/include-filtered-dependencies/packages/package-2/package.json
- test/fixtures/ExecCommand/include-filtered-dependencies/packages/package-3/package.json
- test/fixtures/LsCommand/include-filtered-dependencies/lerna.json
- test/fixtures/LsCommand/include-filtered-dependencies/package.json
- test/fixtures/LsCommand/include-filtered-dependencies/packages/package-1/package.json
- test/fixtures/LsCommand/include-filtered-dependencies/packages/package-2/package.json
- test/fixtures/LsCommand/include-filtered-dependencies/packages/package-3/package.json
- test/fixtures/RunCommand/include-filtered-dependencies/lerna.json
- test/fixtures/RunCommand/include-filtered-dependencies/package.json
- test/fixtures/RunCommand/include-filtered-dependencies/packages/package-1/package.json
- test/fixtures/RunCommand/include-filtered-dependencies/packages/package-2/package.json
- test/fixtures/RunCommand/include-filtered-dependencies/packages/package-3/package.json
* Adds support to `ls`,`exec`,`run`
* Removes need for additional instance variable on BootstrapCommand, CleanCommand
* Adds tests for ls, exec, run
This PR looks huge because I had to change whitespace in a couple of tests, and added new fixtures, but the "actual" work is mostly in `Command.js`, with some find-and-replace in `BootstrapCommand.js`, and `CleanCommand.js`.
> Improve support for --include-filtered-dependencies

- package.json
- yarn.lock
Removes `array-from` and `repeat-string` from the dependency tree.
Interesting side-note: `command-join` originally did not require `array-from` and `repeat-string`, but they were added [so it could be used by `lerna`](https://github.com/seangenabe/command-join/pull/1).
> Bump `command-join`.

- src/commands/DiffCommand.js
- test/DiffCommand.js
Fixes #585 
Basically, the test was behaving inconsistently with all of the other myriad `spawn` stubs, and the source reflected this incorrect test behaviour. A simple falsy check (consistent with all other usage) seemed the way to go.
> Avoid exception after successful `lerna diff`

- src/Command.js
Noticed that the docs in the README say it's under "commands", but the code
was only looking in "command".  This patch supports either/or.
Example:
```js
{
...
"commands": {
"bootstrap": {
"includeFilteredDependencies": true
}
}
}
> Support command config in either "commands" or "command"

- src/PackageUtilities.js
- test/PackageUtilities.js
Suppose we have:
- `package-a`
- `package-b`
- `package-c`
<hr/>
The following works as expected:
```
lerna bootstrap --ignore=package-@(a|b)
```
The message is:
```
Ignoring packages that match 'package-@(a|b)'
```
And the following packages are bootstrapped:
- `package-c`
<hr/>
The following does *not* work as expected:
```
lerna bootstrap --ignore=package-{a,b}
```
The message is:
```
Ignoring packages that match 'package-a,package-b'
```
And the following packages are bootstrapped:
- `package-a` (incorrect)
- `package-b` (incorrect)
- `package-c`
The latter glob is expanded to an array even before reaching `filterPackage` in `PackageUtilities`. (Notice the difference in messages). However, the logic regarding negation (i.e. `maybeNegate`) was only *within* `glob.some`, which would not …
> Fix --ignore flag when globs are expanded to an array

- bin/lerna.js
- src/PackageGraph.js
- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- src/commands/ExecCommand.js
- src/commands/PublishCommand.js
- src/commands/RunCommand.js
- test/PublishCommand.js
Expanding on the work done in https://github.com/lerna/lerna/pull/412 by @seansfkelley.
This makes the `publish` command publish packages to npm in topological order so that there is never a time where npm could have a package whose dependencies do not yet exist in the registry. There's already some `dist-tags` toggling going on, but that doesn't have any effect on users who already have dependencies on a version range in their deps.
Feedback welcome. Main questions:
If you have dependency cycles in your repo, this means Lerna will start logging `"Encountered a cycle in the dependency graph. This may cause instability!"` on every call to `lerna publish` where it wouldn't have before, is that cool?
> Publish npm packages in topological order.

- README.md
- src/Command.js
- src/NpmUtilities.js
- src/commands/BootstrapCommand.js
- src/commands/PublishCommand.js
- test/BootstrapCommand.js
- test/PublishCommand.js
- test/fixtures/BootstrapCommand/registries/lerna.json
- test/fixtures/BootstrapCommand/registries/package.json
- test/fixtures/BootstrapCommand/registries/packages/package-1/package.json
- test/fixtures/PublishCommand/registries/lerna.json
- test/fixtures/PublishCommand/registries/package.json
- test/fixtures/PublishCommand/registries/packages/package-1/package.json
Corrected version of #563
Again, sorry for messing up the previous PR.
> Explicit registry flag feature

- src/Command.js
Can be configured at the top level or per-command.
Example:
```js
{
...
"commands": {
"run": {
"sort": false
}
}
}
```
> Support `sort` option in lerna.json

- src/Command.js
Works at both the top level and also per-command.
Example:
```js
{
...
"commands": {
"bootstrap" {
"includeFilteredDependencies": true
}
}
}
> Durable `includeFilteredDependencies` config via lerna.json

- src/commands/RunCommand.js
- test/RunCommand.js
Fixes #491
npm defines default scripts for `test` and `env`. Lerna only runs
scripts when they’re defined in `package.json`, but this could lead to
unexpected behaviour in these two cases. In particular, it could lead
to `pretest` and `posttest` not being run by Lerna, when npm would have
run them.
> Always run test and env scripts

- appveyor.yml
- package.json
- src/GitUtilities.js
- src/UpdatedPackagesCollector.js
- src/commands/PublishCommand.js
- test/GitUtilities.js
- test/PublishCommand.js
- test/UpdatedCommand.js
Lerna by default now check changes between last tag in current branch (instead of current latest tag in whole repository), it allows to publish older versions of project. (Issue 89).
Checks that user is in a branch and not a detached commit, because lerna can't publish without git branch.
(Issue #89). Reopened pull request #415, because I couldn't work on it anymore.
> Lerna checks changes between last tag in current branch

- README.md
- bin/lerna.js
- src/ChildProcessUtilities.js
- src/NpmUtilities.js
- src/commands/RunCommand.js
- test/RunCommand.js
Emit output from child processes immediately.
- Each line is prefixed with the name of the originating package.
- Output from stdout goes to stdout, and stderr goes to stderr.
```sh
$ lerna run watch --stream
```
This closes #446.
> Add a --stream option to the run command

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
I have no idea if this is a proper solution, therefore I'd like to have some guidance on how to properly test this.
> Feature: skip-temp-tag

- README.md
I ran into an issue where `lerna run build:watch` ("build:watch" being a
babel command with the `--watch` flag) would only run for one package
(called "core"). It turns out to be caused by lerna running commands in
a topologically sorted order, executing packages that others depend on
first before moving on.
The nature of "watch" commands is usually to never end. In my case that
meant that lerna was waiting indefinitely for the "core" package command
to finish.
By reading the documentation I came across the `--no-sort` flag, which
helped resolve my issue. It wasn't super clear in the README that this
flag would help out with my problem, so I decided to add a little bit
about "watch" commands right next to it.
Relevant discussion: …
> Add documentation about "watch" commands next to --no-sort

- README.md
I think this copy more clearly explains the relationship of the two example dependencies (`babel-generator` and `source-map`). The old copy is somewhat vague. Do this change make sense?
> Update vague text in readme.md

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/tepid/lerna.json
- test/fixtures/BootstrapCommand/tepid/package.json
- test/fixtures/BootstrapCommand/tepid/packages/package-1/node_modules/external-1/package.json
- test/fixtures/BootstrapCommand/tepid/packages/package-1/package.json
This makes install all-or-nothing.  If a single dependency is missing then
Lerna will install all dependencies for that location.  This is mostly a noop,
but it's necessary for consistent behavior across npm clients such as Yarn.
It preserves the _true_ noop when there's nothing to install.
This addresses https://github.com/lerna/lerna/issues/630.
> Install with all dependencies when installing

- src/Command.js
This allows for durable configuration.
May be set globally at the top level, or per-command.
```js
{
"concurrency": 2,
"commands": {
"bootstrap": {
"concurrency": 8
}
}
}
```
As with all options obtained from `Command#getOptions()` a value passed on the command-line will override configuration from package.json.
```sh
lerna bootstrap --concurrency=4
```
> Allow concurrency to be configured via package.json

- src/PromptUtilities.js
- src/commands/PublishCommand.js
Added prompts for `prepatch`, `preminor`, `premajor`, and `prerelease` which correspond to the same functionality in `npm version`
> Add prompts for prerelease versions

- .travis.yml
- appveyor.yml
Mostly copied from https://github.com/babel/babel/blob/7.0/.travis.yml, it should help ease the pain of non-parallel AppVeyor somewhat.
> chore(ci): use yarn instead of npm

- README.md
It's very confusing when it shows the latest PR status.
> chore(badge): Appveyor reflects master, not latest

- src/Package.js
- src/commands/BootstrapCommand.js
- test/Package.js
Passing in the logger works just as well as a boolean flag (just like the topological sorting method).
However, in both instances that `Package##hasMatchingDependency()` is actually called, neither of them ever passed `true` in the second arg, so it was basically dead code.
If it was intentional to omit logging in all use cases, then we can delete the dead code.
> Actually warn when a matching dependency version is not satisfied

- src/Command.js
- src/ExitHandler.js
- src/UpdatedPackagesCollector.js
- src/commands/CleanCommand.js
- src/commands/ImportCommand.js
Again, for consistency, let's make sure all the subcommands are accessing the logger and progress bar in the same way. Making as many as possible accessed via instance properties makes future mocking and/or test optimizations a lot easier.
> Use class properties instead of singleton imports

- src/FileSystemUtilities.js
- src/commands/ImportCommand.js
95% percent of the time, we don't destructure named exports when importing them. For the sake of any future mocking or spec-related munging we need to do, let's keep them consistently importing the default export.
> Import consistently in subcommands

- test/BootstrapCommand.js
- test/PublishCommand.js
It's incredibly subtle, and paradoxically the linter does not complain about it.
Additionally, many `assertStubbedCalls` lists had repetitive object stubs, which are easier to read when condensed.
> Indent parsimonious stubbedCalls consistently

- .travis.yml
- appveyor.yml
This is one way we can avoid PRs that update dependencies without committing `yarn.lock` (another is improving our contributing docs, also on my todo list). I've also harmonized the two CI config files as much as possible, with improved caching for AppVeyor.
> Use `yarn --frozen-lockfile` in CI

- package.json
- src/ChildProcessUtilities.js
- src/Command.js
- src/PackageUtilities.js
- src/Repository.js
- src/commands/BootstrapCommand.js
- src/commands/InitCommand.js
- src/commands/PublishCommand.js
- test/ChildProcessUtilities.js
- test/Command.js
- test/InitCommand.js
- yarn.lock
A few high-level goals, here:
* `lerna init` should be the only time we (maybe) run `git init`.
* `lerna` commands should ensure they are run in a git repo during the validation phase, not instantiation.
* Use more "lazy" getters to avoid wasted work and streamline the command startup path.
* Use high-quality libraries ([find-up][], [load-json-file][]) instead of rolling our own.
fixes #645, #555
[find-up]: https://www.npmjs.com/package/find-up
[load-json-file]: https://www.npmjs.com/package/load-json-file
> Support lerna execution from subdirectories of repo root

- package.json
Tested with `npm pack && tar tf lerna-2.0.0-beta.38.tgz`:
```diff
package/package.json
package/README.md
package/LICENSE
package/CHANGELOG.md
-package/CONTRIBUTING.md
-package/FAQ.md
-package/.eslintcache
package/bin/lerna.js
package/lib/ChildProcessUtilities.js
package/lib/FileSystemUtilities.js
package/lib/GitUtilities.js
package/lib/NpmUtilities.js
package/lib/Package.js
package/lib/ExitHandler.js
package/lib/PackageUtilities.js
package/lib/PromptUtilities.js
package/lib/Repository.js
package/lib/UpdatedPackagesCollector.js
package/lib/logger.js
package/lib/ConventionalCommitUtilities.js
package/lib/index.js
package/lib/Command.js
package/lib/progressBar.js
package/lib/PackageGraph.js
package/lib/commands/BootstrapCommand.js
package/lib/commands/CleanCommand.js …
```
> chore: whitelist files included in package tarball [skip ci]

- test/BootstrapCommand.js
- test/ExecCommand.js
- test/ImportCommand.js
- test/InitCommand.js
- test/PublishCommand.js
- test/RunCommand.js
Due to https://github.com/facebook/jest/issues/2059, turns out we need
those try/catch blocks I tried to remove in the previous PR.
Async test cases (calling `done()`, basically) will cause timeout errors when one of the preceding assertions throws an error. I misread the docs that implied this wasn't the case.
This partially reverts #682
Multiple AppVeyor failures due to jasmine timeouts today have provided evidence that this is needed.
> Re-wrap async done() in try-catch

- appveyor.yml
- package.json
- test/CleanCommand.js
- test/FileSystemUtilities.js
- test/helpers/fixtureUtils.js
- test/helpers/initExternalFixture.js
- test/helpers/initFixture.js
- yarn.lock
1. Switching the crash-prone `lerna-<process.pid>-<SHA>/<fixtureDir>_<index>_<fixtureName>` temp directory naming scheme to a more robust `lerna-<Date.now()>-<random 6 digits>-<fixtureDir>_<index>_<fixtureName>` directory-per-test.
2. Removes overcomplicated `recursive-copy` dev dependency in favor of simpler `cpr`.
3. Runs windows tests on AppVeyor the same way as Travis, removing the `--runInBand` option.
Several flapping tests in both AppVeyor and Travis.
Merciless test repetitions.
> Make tmpdir resolution more robust in tests

- src/Command.js
- src/Repository.js
- src/commands/InitCommand.js
- test/InitCommand.js
- test/Repository.js
- test/fixtures/InitCommand/updates/lerna.json
We should always allow semver-compatible CLI versions to operate on a given lerna monorepo, even pre-releases.
Currently, this will fail:
```
$ npm i -g lerna@canary
$ npm i -D lerna@canary
$ lerna init
$ lerna diff
```
The canary releases I've been doing recently were pointed out as failing with the latest changes from #694. Turns out I reversed the order of arguments to `semver.satisfies()` in that PR, and inadvertently conflated `--exact` dependency versioning with CLI version validation.
This fixes #702.
Improved the quality and coverage of the existing InitCommand and Repository tests.
> Fix cli compat check

- src/GitUtilities.js
- src/commands/PublishCommand.js
- test/GitUtilities.js
- test/PublishCommand.js
- test/helpers/assertStubbedCalls.js
To facilitate `--canary` publishes in CI, we shouldn't break `lerna publish` when it detects a detached `HEAD` when canary is enabled. We also need to avoid calling `git symbolic-ref` because it breaks in detached `HEAD` situations (which is going to be the case for a vast majority of CI environments). I renamed the `GitUtilities` method `isDetachedHead()` to better express its intent.
I've also clarified some of the internal flag parsing, creating a new `gitEnabled` instance property that better describes the intent behind `!(this.flags.canary || this.flags.skipGit)`. I was able to simplify some of the conditionals as a result.
This fixes #699 
I reordered the appropriate `ChildProcessUtilities.execSync` stubs, and added a new test for a complicated set of configuration to improve …
> Do not reject detached HEAD when publishing a canary release

- src/UpdatedPackagesCollector.js
- test/PublishCommand.js
Fix for #715 
Publish command used the wrong Command attribute for packages.
Added new unit test.
> fix: ignore flag handling in Publish Command

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/basic/packages/package-2/package.json
- test/fixtures/BootstrapCommand/basic/packages/package-3/package.json
While working on #714, I found that binaries from scoped packages weren't being made correctly.
When `npm` makes a symlink to `@foo/bar`'s CLI, it is available at `./node_modules/.bin/bar`.
Prior to this PR, `lerna` was making the equivalent symlink at `./node_modules/.bin/@foo/bar`.
Updated existing test cases.
> fix(BootstrapCommand): symlink binaries of scoped packages correctly

- src/PackageUtilities.js
- src/index.js
- test/PackageUtilities.js
Remove the public exports of various unused/broken `PackageUtilities` methods. Additionally, completely remove the unused `PackageUtilities.getGlobalVersion()` method.
This was broken anyway, and we can provide better interaction through `--json` output (and the like) for various interrogative subcommands (`ls`, `updated`, etc).
These were discovered while working on #714.
N/A
> fix(PackageUtilities): remove public API, it's broken anyway

- src/Command.js
- src/ConventionalCommitUtilities.js
- src/GitUtilities.js
- src/UpdatedPackagesCollector.js
- src/commands/DiffCommand.js
- src/commands/ImportCommand.js
- src/commands/InitCommand.js
- src/commands/PublishCommand.js
- test/ConventionalCommitUtilities.js
- test/DiffCommand.js
- test/GitUtilities.js
- test/InitCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
Pass `opts.cwd` to all utility executions (in addition to existing `opts`, if present).
This aims to remove any implicit reliance on `process.cwd()`, improving consistency and laying more groundwork for concurrent unit tests.
This builds on the work done in #714.
Updated existing unit test suite.
> Commands: pass execOpts to all utilities executions

- src/Command.js
- src/ConventionalCommitUtilities.js
- src/ExitHandler.js
- src/GitUtilities.js
- src/Repository.js
- src/UpdatedPackagesCollector.js
- src/commands/DiffCommand.js
- src/commands/ImportCommand.js
- src/commands/InitCommand.js
- src/commands/PublishCommand.js
- test/BootstrapCommand.js
- test/CleanCommand.js
- test/Command.js
- test/ConventionalCommitUtilities.js
- test/DiffCommand.js
- test/ExecCommand.js
- test/GitUtilities.js
- test/ImportCommand.js
- test/InitCommand.js
- test/LsCommand.js
- test/PackageUtilities.js
- test/PublishCommand.js
- test/Repository.js
- test/RunCommand.js
- test/UpdatedCommand.js
- test/__snapshots__/PublishCommand.js.snap
- test/helpers/initFixture.js
- test/integration/lerna-bootstrap.test.js
- test/integration/lerna-init.test.js
Pass an explicit CWD parameter to Repository during Command instantiation.
By passing this to every test instance, we improve test isolation and open the door to more concurrency.
This builds on the work done in #714 and #733.
Updated existing unit test suite.
> Command: pass explicit CWD to Repository constructor

- package.json
- test/integration/lerna-bootstrap.test.js
Fix the test that broke when I published `v2.0.0-rc.0`
> Use relative path when specifying file: dependency

- .eslintrc
- package.json
- src/Command.js
- src/UpdatedPackagesCollector.js
- test/UpdatedCommand.js
- test/fixtures/.eslintrc
- test/fixtures/BootstrapCommand/basic/packages/package-2/cli.js
- test/fixtures/BootstrapCommand/basic/packages/package-3/cli1.js
- test/fixtures/BootstrapCommand/basic/packages/package-3/cli2.js
- test/fixtures/BootstrapCommand/extra/package-3/cli1.js
- test/fixtures/BootstrapCommand/extra/package-3/cli2.js
- test/fixtures/BootstrapCommand/extra/packages/package-2/cli.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-2/cli.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-3/cli1.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-3/cli2.js
- test/fixtures/BootstrapCommand/integration/package-2/cli.js
- test/fixtures/BootstrapCommand/integration/package-3/cli1.js
- test/fixtures/BootstrapCommand/integration/package-3/cli2.js
- test/helpers/constants.js
- test/helpers/serializePlaceholders.js
- yarn.lock
Add `eslint-plugin-node` with enforcement of node v4 compatibility.
It's really frustrating when you write code that doesn't work on a supported platform.
Specifically, when writing CommonJS (because Jest a `snapshotSerializer` isn't transpiled), I forget what is and isn't supported by Node v4, which I basically never run anymore (except when trying to debug mysterious CI failures).
We also have a few issues with "best-practice" compliance. I fixed one of them with `safe-buffer`, but the `process.exit()` thing I just ignored and added a `TODO`. It'll get easier to fix that one once we're in `async`/`await` land.
Running automated tests.
> Add eslint-plugin-node

- README.md
I've switched to referencing the [conventionalcommits.org](conventionalcommits.org) website in the section of documentation on the `--conventional-commits` flag.
I think it's worth having a centralized website that describes the concept of conventional commits, rather than it being spread out across various projects.
> Reference conventionalcommits.org website in README

- package.json
- src/GitUtilities.js
- test/GitUtilities.js
- test/integration/__snapshots__/lerna-publish.test.js.snap
- test/integration/lerna-publish.test.js
- yarn.lock
* Move `tempy` to `devDependencies`
* Remove `lerna-publish` lifecycle integration test
* Add multi-line commit validation integration tests
Fixes #552, #551
> Use temp-write for multi-line commit messages

- bin/lerna.js
- package.json
- src/ChildProcessUtilities.js
- src/Command.js
- src/ConventionalCommitUtilities.js
- src/FileSystemUtilities.js
- src/GitUtilities.js
- src/NpmUtilities.js
- src/commands/DiffCommand.js
- src/commands/ExecCommand.js
- src/commands/ImportCommand.js
- src/commands/RunCommand.js
- test/ChildProcessUtilities.js
- test/ConventionalCommitUtilities.js
- test/DiffCommand.js
- test/ExecCommand.js
- test/FileSystemUtilities.js
- test/GitUtilities.js
- test/NpmUtilities.js
- test/integration/__snapshots__/lerna-bootstrap.test.js.snap
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/__snapshots__/lerna-run.test.js.snap
- test/integration/lerna-bootstrap.test.js
- test/integration/lerna-exec.test.js
- test/integration/lerna-import.test.js
- test/integration/lerna-init.test.js
- test/integration/lerna-publish.test.js
- test/integration/lerna-run.test.js
- yarn.lock
`execa` gives us much more robust interface for `child_process`, with a Promise API that will make async/await much easier to migrate to.
* `execa` makes calling dependency binaries a cinch.
* Registering children takes advantage of the rich Promise API.
* Streamed output now has prefixing via `strong-log-transformer` pipes (timestamps available with an option).
Updated unit and integration tests, as well as local testing via `yarn link`.
There are cleanups to the recent CLI refactoring; unfortunately they're too tightly coupled with the other changes in the PR.
> Use execa for child_process calls

- bin/lerna.js
- src/Command.js
- src/UpdatedPackagesCollector.js
- src/commands/BootstrapCommand.js
- src/commands/CleanCommand.js
- src/commands/ExecCommand.js
- src/commands/ImportCommand.js
- src/commands/InitCommand.js
- src/commands/PublishCommand.js
- src/commands/RunCommand.js
- src/commands/UpdatedCommand.js
- test/Command.js
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/lerna-exec.test.js
A funny thing happened on the way to the forum...
Well, turns out I broke "durable" option config yesterday, so I decided to pull off the bandaid that's been itching me for weeks (the `Command#getOptions()` API) and convert it into a lazy getter with lodash `_.defaults()` instead of `Object.assign()`.
I've also made edits and tweaks to the `yargs` options.
Restoring durable config patterns, with some optimization thrown in.
Local hoisted bootstraps and other operations, as well as more integration tests.
> Fix durable option resolution

- src/commands/PublishCommand.js
Fixes #757
The validate function fails when any string is returned. The return of semver.valid will be the same version string (as long as it's valid). So, a valid version will be an "error" according to the validate function. Switching to check for a non-null value coerces this to a boolean that validate is looking for. 
Note: I could have done `!!v` as well, but this is more explicit and readable, I think.
> Fix custom version prompt

- src/ConventionalCommitUtilities.js
- src/FileSystemUtilities.js
- test/ConventionalCommitUtilities.js
- test/FileSystemUtilities.js
- test/integration/lerna-publish.test.js
To protect Windows from itself, use explicit `node path/to/cli.js [..args]` call style. 
The `require.resolve()` calls were removed in #759, not realizing `yarn` was going to rain on our parade very shortly. This PR builds on #770, which provides some optimizations to the `rimraf` calls independent of the local resolution issue.
#708 is fixed by this because we're not letting Windows Script Host get involved at all, instead calling the resolved CLI in the `node path/to/cli.js [..args]` pattern (which is implicitly what a shebang does, anyway).
Local testing, because yet again I am foiled by unstable test snapshots (`lerna publish --conventional-commits` almost all the way there, except for the timestamps in the changelog output and actual commit history, etc). Le sigh.
> Resolve internal CLI calls with Windows-safe pattern

- src/PackageUtilities.js
- test/PackageUtilities.js
- test/fixtures/PackageUtilities/globstar/lerna.json
- test/fixtures/PackageUtilities/globstar/package.json
- test/fixtures/PackageUtilities/globstar/src/even/package-2/package.json
- test/fixtures/PackageUtilities/globstar/src/even/package-4/package.json
- test/fixtures/PackageUtilities/globstar/src/odd/package-1/package.json
- test/fixtures/PackageUtilities/globstar/src/odd/package-3/package.json
- test/fixtures/PackageUtilities/globstar/src/package-5/package.json
When recursing (via `**`, or "globstar") in our search for `package.json` files, we should ignore any files found under a `node_modules` directory.
Any support we currently have for nesting package locations is accidental, and bootstrapping a "dirty" tree will definitely cause issues. I happened to encounter this on an internal repo where I was trying to bootstrap a nested tree of private packages with a valid `src/**` glob.
This also happens to validate the "managed root package" case inherited from `asini`.
A new `globstar` fixture, as well as local `lerna ls` etc.
> Ignore node_modules when traversing nested package locations

- doc/hoist.md
- src/NpmUtilities.js
- src/commands/BootstrapCommand.js
Use `npm install --global-style` under `lerna bootstrap --hoist` for packages which cannot be hoisted. This results in more consistently correct behavior at the cost of increased duplication of some packages.
In the event that an explicit dependency (`dep1@X`) of a package is hoisted but other dependencies with a common sub-dependency on a different version of `dep1@Y` cannot be hoisted, npm will attempt to share that package by installing `dep1@Y` in the root of the package's `node_modules` directory. As a result, the incorrect version of `dep1` will be available to the package rather than the hoisted dependency it requires.
1. A package has three explicit dependencies: `dep1@2.x`, `dep2`, and `dep3`. 
2. `dep2` & `dep3` have a transitive dependency on a _different version_ of `dep1` …
> fix: always install leaves using `npm --global-style`

- src/commands/BootstrapCommand.js
`meow` allowed `--hoist` to have behaviour that wasn't translated accurately into `yargs`.
Fixes #768
Local testing on the repo provided in #768
> Fix --hoist with no argument default

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
Explicit skipping of a temp tag is no longer necessary since packages are published in topological order. Fixes #742
I removed the `--skip-temp-tag` flag from the codebase and replaced it with `--temp-tag` with a default value of `false`.
This means that if nothing is provided Lerna will not create a temp-tag.
If someone would like to create a temp-tag in the process he/she could do it by providing the `--temp-tag` flag.
Inverted the test case where temp tag creation was disabled and tested if it indeed is created when requested.
> move from --skip-temp-tag to --temp-tag

- src/FileSystemUtilities.js
- src/commands/BootstrapCommand.js
- src/commands/CleanCommand.js
- test/BootstrapCommand.js
- test/CleanCommand.js
- test/FileSystemUtilities.js
Restore original async loop of deleting `node_modules` directories.
Turns out I misunderstood the original algorithm when I made changes last week. It doesn't matter how many `node_modules` directories you pass to `rimraf`, it's still going to take a long time if you don't map them concurrently.
This partially reverts #770
Local testing, with updates to unit tests.
> Restore async rimraf loops

- test/BootstrapCommand.js
- test/NpmUtilities.js
- test/__snapshots__/BootstrapCommand.js.snap
Test coverage for `npmGlobalStyle` option in `NpmUtilities.installInDir`.
* https://github.com/lerna/lerna/pull/775
* https://github.com/lerna/lerna/commit/c590d57fa0736950ae4820932176d71ceca61587
`npm test`
> Add tests for npm global style option

- README.md
- src/Command.js
- src/commands/ImportCommand.js
- test/Command.js
- test/ImportCommand.js
Add a new flag `---max-buffer` to solve spawn issues.
Fixes: #479
Added flag with docs, and a new test. I did not add a new test to every command because the buffer issue only surfaced while devs were using the `import` command.
With a new unit test.
> Add --max-buffer flag

- src/PromptUtilities.js
Pause logging and progress bars when prompts are visible, and resume both when answered.
#779 left the prompts cut off and very hard to use. This fixes that.
Local `lerna publish` in a live repo. I like to live dangerously. 🔥
> Prevent log messages and progress bars from mangling prompts

- src/Command.js
- src/FileSystemUtilities.js
- src/GitUtilities.js
- src/commands/CleanCommand.js
- test/integration/__snapshots__/lerna-clean.test.js.snap
- test/integration/lerna-clean.test.js
Restore some logging to indicate actions during `lerna clean`.
- Tunes the log level of some frequent internal calls to improve their usefulness
- Adds normalizeStdio() utility to avoid cross-platform snapshot mismatch
Fixes #788
local runs, integration test updates
> Log the directories being cleaned

- README.md
- src/ChildProcessUtilities.js
- src/commands/ExecCommand.js
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/lerna-exec.test.js
With this flag, `lerna exec` will run the command in _all_ filtered packages
in parallel, completely ignoring concurrency and topological sorting.
```sh
lerna exec -- babel src -d lib -w
lerna exec --scope package-foo -- babel src -d lib -w
```
I found this useful in a hoisted monorepo to transpile package exports that are themselves linked to private webpack entry points. Disabling the progress bar is necessary in all cases.
It is advised to constrain the scope of the command when running with this
flag, as spawning dozens of subprocesses may be harmful to your shell's
equanimity (or maximum file descriptor limit, for example). YMMV
local development in a lerna monorepo, and several integration tests.
> Add --parallel flag to `lerna exec`

- README.md
- src/commands/RunCommand.js
- test/RunCommand.js
- test/__snapshots__/RunCommand.js.snap
- test/fixtures/RunCommand/integration-lifecycle/packages/package-1/package.json
- test/fixtures/RunCommand/integration-lifecycle/packages/package-2/package.json
- test/fixtures/RunCommand/integration-lifecycle/packages/package-3/package.json
- test/integration/__snapshots__/lerna-run.test.js.snap
- test/integration/lerna-run.test.js
Provide a new flag, `--parallel`, to facilitate easier and less error-prone spawning of long-running watchers from npm scripts (e.g., `lerna run watch`).
This allows simpler invocation of `watch` scripts, with the caveat that concurrency and topological sorting are _completely_ ignored. This is generally the intention when calling `lerna run watch` and other similar script targets, hence the additional flag.
```sh
$ lerna run watch --concurrency=1000 --stream
$ lerna run watch --parallel
```
Package filtering (`--scope` and `--ignore`) is still available when this new flag is being used, and it is advised to narrow the scope of parallel execution when you have more than a dozen packages or so (YMMV).
local monorepo dev and copious unit and integration tests.
> Add --parallel flag to `lerna run`

- src/PackageUtilities.js
- test/PackageUtilities.js
- test/fixtures/PackageUtilities/explicit-node-modules/lerna.json
- test/fixtures/PackageUtilities/explicit-node-modules/package.json
- test/fixtures/PackageUtilities/explicit-node-modules/packages/node_modules/@scoped/package-5/package.json
- test/fixtures/PackageUtilities/explicit-node-modules/packages/node_modules/package-1/package.json
- test/fixtures/PackageUtilities/explicit-node-modules/packages/node_modules/package-2/package.json
- test/fixtures/PackageUtilities/explicit-node-modules/packages/node_modules/package-3/package.json
- test/fixtures/PackageUtilities/explicit-node-modules/packages/node_modules/package-4/package.json
- test/fixtures/PackageUtilities/mixed-globstar/lerna.json
- test/fixtures/PackageUtilities/mixed-globstar/package.json
- test/fixtures/PackageUtilities/mixed-globstar/packages/node_modules/package-1/package.json
- test/fixtures/PackageUtilities/mixed-globstar/packages/node_modules/package-2/package.json
- test/fixtures/PackageUtilities/mixed-globstar/packages/node_modules/package-3/package.json
- test/fixtures/PackageUtilities/mixed-globstar/packages/node_modules/package-4/package.json
- test/fixtures/PackageUtilities/mixed-globstar/src/package-5/package.json
* When package globs have been configured with an explicit `node_modules` path, don't ignore `**/node_modules/**`
* When no package globs have a globstar, don't ignore `**/node_modules/**`
* When globstars exist in packages config, don't allow explicit `node_modules` paths
Fixes #792, based on [discussion](https://github.com/lerna/lerna/issues/792#issuecomment-298133075)
more unit tests to maintain coverage level
> Do not ignore explicit node_modules in package paths

- src/Command.js
- src/commands/BootstrapCommand.js
- src/commands/CleanCommand.js
- src/commands/ExecCommand.js
- src/commands/LsCommand.js
- src/commands/RunCommand.js
- test/integration/__snapshots__/lerna-bootstrap.test.js.snap
- test/integration/lerna-bootstrap.test.js
According to Bootstrap Command's description it is not necessarily true that we need to check if the command was run in a project where there is a pre-initialized git repository. This PR tries to resolve this issue.
I added a `--skip-git-check` flag to the Bootstrap Command which is on by default resulting in a behavior described above
#438
I added integration tests.
> Skip git repo check by default in Commands which do not rely on git

- src/ChildProcessUtilities.js
Make streaming output a bit easier to distinguish with rotating colors and removal of scary "ERROR" prefix of `stderr` pipe.
I wanted to make things pretty, like `debug` does (but simpler).
I'd paste a screenshot, but then I'd have to scrub a bunch of sensitive work stuff...
A lot of local `lerna exec --parallel` and `lerna run watch --parallel`. Regrettably nothing automated, but then again, nothing previously existed in these cases.
> Prefix piped streams with rotating colors

- src/GitUtilities.js
- test/GitUtilities.js
This PR allows Lerna to work with a user's git config to allow signing of tags.
I removed the `-a` option from the invocation of `git tag`. Since we're invoking `git tag` with `-m`, this will have no effect on the generated tag unless a user has the `tag.forceSignAnnotated` option enabled in their git config.
This is the easy solution to #814 
All existing tests pass, both with and without `tag.forceSignAnnotated` enabled in my git config.
> Support GPG signing of git tags

- README.md
- src/Command.js
- src/commands/LsCommand.js
- src/commands/UpdatedCommand.js
- test/LsCommand.js
- test/UpdatedCommand.js
- test/__snapshots__/LsCommand.js.snap
- test/__snapshots__/UpdatedCommand.js.snap
Adds a `--json` flag, which is currently used only by `lerna ls` and `lerna updated` to produce machine-readable output.
Inspired by the discussion in https://github.com/lerna/lerna/pull/686 and my own desire to not have our artisanally-crafted script be reliant on the plain text formatting of `lerna updated` moving forward.
Manually via invocations of the command with and without the `--json` flag, as well as new test cases.
> Add json output to `ls` and `updated` commands

- src/commands/DiffCommand.js
Some awkwardness crept into `lerna diff` during recent refactoring. This cleans it up.
Fixes #816
existing unit tests pass
> Make pkg argument optional for lerna diff

- README.md
This explains how `bootstrap` does semver checks before using/linking internal packages in a lerna repo.
Sometimes it makes sense to always use the latest version of an internal package, for all other packages.
Being naive, I first used the `latest` dist tag in the `package.json`s of _'all other packages'_. This is when I learnt that tags flat-out do not satisfy semver ranges. Makes sense.
Not applicable.
> Add semver notes to bootstrap command docs

- README.md
- src/commands/ExecCommand.js
- test/ExecCommand.js
- test/fixtures/ExecCommand/basic/packages/package-1/package.json
- test/fixtures/ExecCommand/basic/packages/package-2/package.json
- test/integration/lerna-exec.test.js
Currently, if a subprocess created using `lerna exec` throws an error, it will kill the entire operation. This change adds a `bail` flag, which will ignore subprocess errors for the `exec` command. The default value for `bail` is true, thereby preserving the existing functionality.
This works by passing a `reject` flag to `execa` (documented [here](https://www.npmjs.com/package/execa#reject)). When this flag is set to `false`, it will resolve its Promise instead of the default rejection behavior.
Motivated by #323 , which outlined that there are many cases where you want to run a command that may fail on all packages, and that the failure outcome should not be cause for halting the operation for the remaining packages.
* Added a new unit test, which confirms the passing of the `reject` …
> Flag for exec to bail upon child execution error

- src/Command.js
- src/commands/ExecCommand.js
- src/commands/PublishCommand.js
- src/commands/RunCommand.js
- test/Command.js
`lerna publish` was the last vestige of `this.flags.*`, providing inconsistent behaviour as @tivac detailed in #841
successful unit and integration tests
> All CLI options should be configurable in lerna.json

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
This allows `--message` to only override the subject in `--independent` publishes and interpolates the global version in a `%s` placeholder for "fixed" publishes.
@tivac pointed out in #842 that #460's intent (as captured by @emmenko) wasn't entirely accomplished, and it's really handy to be able to override the pedestrian-yet-serviceable "Publish" default subject.
Real live publish from my localhost with updated code, as well as updated tests.
> Preserve tag summary with `lerna publish --message`

- src/commands/RunCommand.js
- test/RunCommand.js
Display a warning when `lerna run <script>` does not find any npm scripts to execute, rather than throw an error.
Similar to @treshugart, we have a desire to run certain npm scripts against only changed packages. Sometimes no packages have changed, and sometimes only packages without the referenced script has changed. In most situations, this is not a failure state, and this behavior is more in line with other scoped commands (e.g. `ls`, `bootstrap`).
https://github.com/lerna/lerna/issues/859
Manual invocations of the command with scopes that do and don't contain the target npm script.
> lerna run: Don't error if no scoped packages are matched

- src/Command.js
- src/commands/BootstrapCommand.js
- src/commands/CleanCommand.js
- src/commands/ExecCommand.js
- src/commands/ImportCommand.js
- src/commands/InitCommand.js
- src/commands/LsCommand.js
- src/commands/PublishCommand.js
- src/commands/RunCommand.js
- src/commands/UpdatedCommand.js
- test/Command.js
- test/ExecCommand.js
Fixes #895.
The solution to this requires that we stop using yargs defaults because we have several different ways of specifying options. If we specify yargs defaults, then they get set as flags and override any specified in the lerna.json. To get around this, we have to put defaults last in the chain by specifying them per command, as opposed to yargs which comes first in the chain as they merge user-defined options passed as flags with the corresponding defaults.
Unless I'm missing something (definitely could be), there's no way for us to insert our `lerna.json` options in between the options yargs parses and the defaults that we specify for them.
I've updated each command to:
1. Properly declare boolean options, if they weren't already specified (some weren't).
2. Ensure boolean …
> fix: Fix issue where Yargs default would override durable options.

- src/NpmUtilities.js
- test/NpmUtilities.js
Run `yarn` in non-interactive mode using `--non-interactive` switch. This is the same behavior as for `npm` client.
`lerna bootstrap` command hangs when there's unknown package version and `yarn` is used as a `npmClient`. `npm` runs in non-interactive mode and just throws an error, but `yarn` tries to suggests different versions by default. This change makes `yarn` to throw an error as `npm` does.
Fixes https://github.com/lerna/lerna/issues/885
Tested in a local repository. I tried to copy minimal testing fixture into the project, but it seems that all tests mock or stub any `yarn` command calls.
> Fix: Run yarn in non-interactive mode

- src/commands/LsCommand.js
- test/LsCommand.js
- test/__snapshots__/LsCommand.js.snap
- test/fixtures/LsCommand/undefined-version/lerna.json
- test/fixtures/LsCommand/undefined-version/package.json
- test/fixtures/LsCommand/undefined-version/packages/package-1/package.json
When a package's `version` key is missing, Lerna would print `vundefined` when listing it via `lerna ls`. That's slightly jarring to see, so I replaced the string with `n/a` instead. I also right-aligned the version numbers because it looked slightly neater:
The output looked ugly before. 😄 
I've included a snapshot test for this behaviour.
> Print n/a when a package has no version key.

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
** hold on, getting this explanation in order :)
This small change adds the possibility for the user to add his own mutex setting.
The current rc of lerna defaults lerna to the use of `--mutex network:424242`. 
With this commit the user can add a 'mutex' setting to lerna.json to choose for himself what type of setting he prefers.
```
{
"lerna": "2.0.0-rc.4",
"packages": [
"packages/*"
],
"mutex": "file:/path/to/file",
"npmClient": "yarn",
"version": "independent"
}
```
A limitation with this approach seems to be that the mutex has to be called with a path that is located outside the main packages, if not, the lock is created in de package dir itself and so for every package, which off course defeats the purpose. The path either needs to be absolute or located in the parent-packages …
> Allow custom yarn mutex from lerna.json config

- README.md
- src/Command.js
- src/UpdatedPackagesCollector.js
- src/commands/ExecCommand.js
- src/commands/RunCommand.js
- test/Command.js
- test/ExecCommand.js
- test/RunCommand.js
- test/__snapshots__/RunCommand.js.snap
- test/__snapshots__/UpdatedCommand.js.snap
- test/fixtures/UpdatedCommand/basic/packages/package-5/package.json
- test/integration/__snapshots__/lerna-publish.test.js.snap
The `--since` option applies to all commands that accept `--scope`.
By default `--since` will scope the command to all packages that have been updated since the latest tag. If a ref is passed (i.e. `--since ref`), then it will scope the command to all packages that have been updated since the specified ref.
Currently we have a fairly large repo of packages (currently 68) and the builds take quite awhile to complete because when CI runs, it uses `lerna run` and that executes on all packages. This means our build only gets slower as we add more packages.
Since we only care about packages that have actually changed, we can theoretically use `--scope` to filter the packages that should be run. However, in practice, this isn't very simple because we have to figure out which packages have been …
> Add --since flag to all commands that accept --scope

- README.md
- src/commands/ExecCommand.js
When you want to run a script located in the root dir in a complicated dir structure, when there is no fixed pattern for the distance of the sub-dir level  from the root dir.
```sh
root-dir/
packages/
cool-package/
@some-scope/
some-package/
other-package/
scripts/
lerna.json
package.json
```
```sh
/root-dir/packages/cool-package$ node ../../scripts/some-script.js
```
```sh
/root-dir/packages/@some-scope/some-package$ node ../../../scripts/some-script.js
```
```sh
/root-dir$ lerna exec node ../{???}/scripts/some-script.js
```
If there is a environment variable that contains the root path dir, it is possible to run scripts that are located in the root dir easily.
```sh
/root-dir$ cross-env lerna exec node $LERNA_ROOT_PATH/scripts/some-script.js
```
> [Feature] Root path dir environment variable

- README.md
- src/NpmUtilities.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/NpmUtilities.js
- test/fixtures/BootstrapCommand/npm-client-args-1/lerna.json
- test/fixtures/BootstrapCommand/npm-client-args-1/npm
- test/fixtures/BootstrapCommand/npm-client-args-1/package.json
- test/fixtures/BootstrapCommand/npm-client-args-1/packages/package-1/package.json
- test/fixtures/BootstrapCommand/npm-client-args-2/lerna.json
- test/fixtures/BootstrapCommand/npm-client-args-2/npm
- test/fixtures/BootstrapCommand/npm-client-args-2/package.json
- test/fixtures/BootstrapCommand/npm-client-args-2/packages/package-1/package.json
- test/integration/__snapshots__/lerna-bootstrap.test.js.snap
- test/integration/lerna-bootstrap.test.js
Allow to pass npmClient arguments.
https://github.com/lerna/lerna/issues/813
```sh
{ lerna: '2.0.0-rc.4',
npm: '3.10.10',
ares: '1.10.1-DEV',
http_parser: '2.7.0',
icu: '57.1',
modules: '48',
node: '6.9.4',
openssl: '1.0.2j',
uv: '1.9.1',
v8: '5.1.281.89',
zlib: '1.2.8' }
Darwin pstrashkin-mbp 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
```
> Pass extra arguments to npmClient during bootstrap

- README.md
- src/NpmUtilities.js
- src/Repository.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/LsCommand.js
- test/__snapshots__/LsCommand.js.snap
- test/fixtures/BootstrapCommand/yarn-workspaces/.yarnrc
- test/fixtures/BootstrapCommand/yarn-workspaces/lerna.json
- test/fixtures/BootstrapCommand/yarn-workspaces/package.json
- test/fixtures/BootstrapCommand/yarn-workspaces/workspaces/package-1/package.json
- test/fixtures/BootstrapCommand/yarn-workspaces/workspaces/package-2/package.json
- test/fixtures/LsCommand/yarn-workspaces/.yarnrc
- test/fixtures/LsCommand/yarn-workspaces/lerna.json
- test/fixtures/LsCommand/yarn-workspaces/package.json
- test/fixtures/LsCommand/yarn-workspaces/workspaces/package-1/package.json
- test/fixtures/LsCommand/yarn-workspaces/workspaces/package-2/package.json
Yarn has a Workspaces feature that implements Lerna's bootstrap logic in a nice "more atomic" and more native from a package manager point of view way.
The progress and all the links to the feature is here https://github.com/yarnpkg/yarn/issues/3294.
Workspaces are still considered "experimental" but we are moving forward and are ready to turn it on for a couple of projects, e.g. https://github.com/facebook/jest/pull/3906.
This PR integrates Yarn workspaces with Lerna by replacing all the bootstrap/hoisting logic with a simple call to `yarn install`.
Also it makes Lerna use package.json/workspaces field as Yarn does.
1. Manual:
- update to Yarn 0.27.2
- checkout jest with this PR https://github.com/facebook/jest/pull/3906
- run `../lerna/bin/lerna.js bootstrap`
- verify that workspace …
> Support Yarn workspaces to replace bootstrap command

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
This change changes the `canary` semantics and bumps the minor version, as well as overloading it allowing the user to pass a value that will be used for the meta suffix instead i.e. `--canary=beta`, which results in a `x.x.x-beta.<sha>` version tag.
This is especially useful in CI scenarios where you want to publish an `alpha`, `beta`, and/or `rc` version depending on the branch you're building i.e. `1.1.0-beta.e5fg52` for the `develop` branch.
BREAKING CHANGE: Now bumps to the next `minor` version instead of using current version, as per `GitVersion` and other such tools. This prevents issues the alphabetical ordering outlined in #277 
Currently the `canary` option has a few limitations:
* Hard codes an `alpha` meta suffix on the resulting version
* Uses the current version, not the …
> feat(canary): Improved canary option functionality

- package.json
- test/Command.js
- test/UpdatedCommand.js
- yarn.lock
Fixed unit test failures on Windows by replacing native touch commands with a node touch implementation
The unit tests that invoke the touch command fail on Windows, as Windows does not have a native touch command. 
`npm run test` on Windows 10
> Fix unit tests failures on Windows

- src/PackageUtilities.js
- test/PackageUtilities.js
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/lerna.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/package.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/packages/package-1/package.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/packages/package-2/package.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/packages/package-3/package.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/packages/package-4/package.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/packages/package-5/package.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/packages/package-6/package.json
- test/fixtures/PackageUtilities/cycles-and-repeated-deps/packages/package-7/package.json
This is a very small change to fix a performance issue when using the include-filtered-dependencies flag in a large, cyclic repository.
The old behaviour would cause packages to be returned multiple times, hence bootstrapped multiple times.
The change was just to add the extra check that you havent seen a package before you add it to the list.
Major performance concerns in bootstrapping
I have run this in our repo (>60 packages) and have found a 33-50% decrease in bootstapping times
For one small package it went from 24s to 14s (10 packages bootstrapped -> 6 packages bootstrapped), for another it went from 214s to 145s (58 packages boostrapped -> 36 packages bootstrapped)
I've also added another test fixture with a very specifically crafted set of deps that tests three things
* A package …
> Fixes #939 Bootstrap performance issue with --include-filtered-dependencies in large, cyclic repos

- test/fixtures/BootstrapCommand/integration-lifecycle/package-1/package.json
- test/fixtures/BootstrapCommand/integration/package-1/package.json
- test/fixtures/ExecCommand/exec-test
- test/fixtures/ExecCommand/exec-test.bat
- test/fixtures/ExecCommand/exec-test.js
- test/helpers/initExecTest.js
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/lerna-exec.test.js
Changes the integration tests to support running on both Windows and Linux environments by removing the need to have `ls` and `cp` commands available. 
For the exec tests `ls` has been replaced with a shell script/windows batch file, that calls `node  exec-test.js`  `exec-test.js` just lists the current package, any args supplied and all the files in the package. 
With this approach, it is easier to verify if `lerna exec`  is respecting the command line flags.
For example, If passing args with `--` was broken, the output would clearly show the args that are/aren't passed to each package: `lerna exec exec-test -- -1 ` 
broken:
```
package-1 -1
file-1.js
package.json
package-2
file-2.js
package.json
```
working:
```
package-1 -1
file-1.js
package.json
package-2 -1
file-2.js
package.json
``` …
> Platform independent integration tests

- src/cli.js
- test/helpers/serializePlaceholders.js
- test/integration/_setupTestFramework.js
…that won't just match any old instance of "2.0.0"
**Caution: I also increased the timeout for the integration tests from 70s to 300s.**  I know it's probably a bad idea, but some of those tests seem to take forever on node v.8
A slightly-too-complicated regular expression.  The `.` characters present in `constants.LERNA_VERSION` will still match any character, but…
[Here's more info on the regexp I added.](https://regex101.com/r/E8GYA8/1)
I had considered bumping all the version numbers in the snapshots up into the `1000000.0.0` range, but when I thought about it some more I saw that the existing regexp here would match `1000002.0.0`.  Since there are versions from `0.0.0` through `6.0.0` in the snapshots, I figured this was the safest approach (at least until lerna gets to `6.0.1`, at …
> Avoid false positives during integration test filtering

- src/ChildProcessUtilities.js
- test/ChildProcessUtilities.js
`ChildProcessUtilities.registerChild()` attaches itself to an `execa` thenable, but then there is no catch, so if command executed fails, there is an `unhandledRejection`. Given `execa` promise is returned/handled via callback, it's ok to swallow error.
Not clean - using `lerna` api for an extension and get unhandled rejections in tests:)
Cleaned-up tests, I could add regression test though.
> Swallow promise rejection in registerChild as it is handled via callback

- package.json
- yarn.lock
New version of load-json-file have better error reporting.
Fixes #854.
> Bump load-json-file

- src/ConventionalCommitUtilities.js
- src/commands/PublishCommand.js
- test/ConventionalCommitUtilities.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
- test/fixtures/PublishCommand/normal-exact/package.json
- test/fixtures/PublishCommand/normal/package.json
This PR adds support for --conventional-commits in fixed mode. When the --conventional-commits 
flag is used, the highest bump from the changed packages will be used as the new version. 
Eg 
package-1 1.0.0 -> feat
package-2 1.0.0 -> fix
`lerna publish --conventional-commits`
Results in package-1 and package-2 being updated to 1.1.0 
This is accomplished by only using the `"-l", pkg.name` arguments (lerna mode) to conventional-recommended-bump/conventional-changelog-cli in independent mode. 
The CHANGELOG.md files for each package are also created/updated on each publish. 
The order of commands in `src/commands/PublishCommand.js` has been updated to group by option type first, then independent/fixed, which improves readability. 
This PR allows lerna to be used to publish new versions in …
> Support --conventional-commits in fixed versioning mode

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
This updates the `lerna publish` command to accept any semver-compatible release type for `--cd-version` and allows you to use `--canary` and `--cd-version` together. It fixes #915 and #567 (and #936), and conflicts with #958 😬 .
Here are the changes to the publish command:
1. Any semver-compatible release type is for the value of `--cd-version`, rather than whitelisting "major", "minor", and "patch". The value coercion only fails if `semver.inc("1.0.0", choice)` throws an error.
1. The `--preid` option can be used to specify the semver prerelease identifier (`major.minor.patch-prerelease`), e.g. with:
```
lerna publish --cd-version=prerelease --preid=beta
```
1. The `--canary` option now works with `--cd-version` to change how everything up to the prerelease identifier is changed, so you …
> Improve support for semver prerelease identifiers when publishing

- doc/troubleshooting.md
Adds troubleshooting info for the publish command when lightweight tags have been created manually, rather than annotated tags. 
The Github web ui creates lightweight tags instead of annotated tags, which can cause issues when `lerna publish` is run. 
N/A
> Add troubleshooting info for GitHub lightweight tags

- src/Command.js
- src/commands/PublishCommand.js
- src/commands/UpdatedCommand.js
- test/CleanCommand.js
- test/ImportCommand.js
- test/integration/__snapshots__/lerna-publish.test.js.snap
- test/integration/lerna-publish.test.js
In most contexts, exiting early is not an error, so exit 0 and don't write a lerna-debug.log file.
Fixes #853
Removing bad flags from the integration test revealed the issue, and thus the fix.
> Exit properly when there is nothing to publish

- src/Command.js
- src/commands/DiffCommand.js
- src/commands/PublishCommand.js
- test/Command.js
- test/DiffCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
- test/helpers/yargsRunner.js
Use the _actual_ arg parser that creates _actual_ command instances when run via the CLI during unit tests, an amazing concept.
Our artificial constructor arguments have led to several bugs, most recently (and egregiously) #989 (from #960).
This also _drastically_ simplifies the tests and makes them much more readable.
a whole bunch (the first push will intentionally fail with a #989 repro)
> Use yargs parser in unit tests for greater fidelity

- src/commands/PublishCommand.js
- test/fixtures/PublishCommand/normal-no-inter-dependencies/lerna.json
- test/fixtures/PublishCommand/normal-no-inter-dependencies/package.json
- test/fixtures/PublishCommand/normal-no-inter-dependencies/packages/package-1/package.json
- test/fixtures/PublishCommand/normal-no-inter-dependencies/packages/package-2/package.json
- test/integration/__snapshots__/lerna-publish.test.js.snap
- test/integration/lerna-publish.test.js
Fix --conventional-commits in fixed mode recommending versions that have already been released. 
Overrides the version of a package when asking for a version bump if it is < the current fixed version, ie the version field in lerna.json 
Fixes https://github.com/lerna/lerna/issues/988
Manually, following the repro steps in https://github.com/lerna/lerna/issues/988
Added new Integration tests for `--conventional-commits`
> Fix --conventional-commits recommending already released version

- src/ConventionalCommitUtilities.js
Fix silly level log output for --conventional-commits changelog generation
Silly level logging was outputting `updateIndependentChangelog` even when running in fixed mode. 
N/A
> Fix silly level log output for --conventional-commits

- README.md
- src/commands/BootstrapCommand.js
- test/integration/__snapshots__/lerna-bootstrap.test.js.snap
Followup to #499
Handle more lifecycle events during bootstrap - pairing in the behaviour with latest npms
Handle correctly specified lifecycle events for npm4+. At the moment behaviours for regular npm install and lerna bootstrap are out of sync, which cause problems with preparation scripts i.e. not being run at all.
Fixes #421
Ran lerna's test suite + used this on my own project to check if added scripts are getting executed during bootstrap.
cc @wzrdzl and @evocateur
> Run "prepare" lifecycle script during bootstrap

- package.json
- src/Repository.js
- src/commands/DiffCommand.js
- test/DiffCommand.js
- test/Repository.js
- yarn.lock
Contrary to the description of `lerna diff`, we weren't properly filtering the general case.
We pass the root directory paths of all configured `packages` locations to `git diff -- [dirs..]`, which acts as a filter for the diff output.
It wasn't doing anything useful, moreso than anyone could do with `git diff v1.0.0..HEAD`.
Also, lockfiles are extreeeemely noisy nowadays, and it was bugging me.
updated tests
> Only diff package locations, not the entire repository

- README.md
- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- src/commands/LinkCommand.js
- src/index.js
- test/LinkCommand.js
- test/__snapshots__/LinkCommand.js.snap
- test/fixtures/LinkCommand/basic/lerna.json
- test/fixtures/LinkCommand/basic/package.json
- test/fixtures/LinkCommand/basic/packages/package-1/package.json
- test/fixtures/LinkCommand/basic/packages/package-2/cli.js
- test/fixtures/LinkCommand/basic/packages/package-2/package.json
- test/fixtures/LinkCommand/basic/packages/package-3/cli1.js
- test/fixtures/LinkCommand/basic/packages/package-3/cli2.js
- test/fixtures/LinkCommand/basic/packages/package-3/package.json
- test/fixtures/LinkCommand/basic/packages/package-4/package.json
[![Sponsored by Immowelt](https://img.shields.io/badge/sponsored%20by-immowelt-yellow.svg?colorB=ffb200)](https://stackshare.io/immowelt-group/)
@evocateur
This commit adds a new 'link' command to the CLI which will create symlinks across the lerna package dependencies. This command was requested in #341 and solves issues with using 'npm prune' with lerna based repositories, e.g. 'npm prune' removes extranous packages, which include the symlinks of lerna.
Since the bootstrap command is a bit heavy, especially while hoisting, I opted for a seperate command since the bootsrap command is pretty complex as of now anyway and I don't think it will be particularly usefull to add option after option.
I also refactored most of the code, e.g. made it more purely functional, regarding the …
> Add `lerna link` command

- src/Command.js
- src/commands/BootstrapCommand.js
- test/Command.js
Changes the output for failing bootstrap commands
Instead of using npm log to continue logging with extra lerna prefixes and relying on the formatting of npmlog, just use the available logs from the failing command to convey meaningful information.
**Original Output**
```
lerna info version 2.0.0
lerna info Bootstrapping 2 packages
lerna info lifecycle preinstall
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna ERR! execute Error: Command failed: npm run prepublish
lerna ERR! execute [18:21:31] 'build-package (workbox-core) ["dev"]' errored after 68 ms
lerna ERR! execute [18:21:31] Error: Unexpected token
lerna ERR! execute     at error (/home/matt/Projects/Code/workbox/node_modules/rollup/dist/rollup.js:177:12)
lerna ERR! …
```
> Improve logging of package lifecycle errors during bootstrap

- README.md
`lerna init` will initialize a Git repo. It doesn’t create a `packages` folder but it should be fixed in https://github.com/lerna/lerna/pull/970
> Update installation instructions to match lerna init behavior

- README.md
- doc/troubleshooting.md
- src/commands/ImportCommand.js
- test/ImportCommand.js
Add option "--flatten" to import each merge as a single change the merge introduced
Instead of doing "git format-patch", patches can be created by "git log" with a certain set of options that mimic format-patch, but with git log some additional options are available, like "--first-parent", which only follows main branch, so that side branch commits are not taken in separately, but instead only the merge commit is imported containing all changes from all branches commits that were merged there.
This is required for situations when there were merge commits containing merge conflict resolutions in imported project. In the current implementation, "lerna import" fails because "git format-patch" does not include merge commits and its resolution, so such projects can't be imported. If …
> Add --flatten option to use when merge conflicts cannot be imported

- src/commands/PublishCommand.js
- test/.eslintrc.yaml
- test/PublishCommand.js
- test/fixtures/PublishCommand/lifecycle/lerna.json
- test/fixtures/PublishCommand/lifecycle/package.json
- test/fixtures/PublishCommand/lifecycle/packages/package-1/package.json
- test/fixtures/PublishCommand/lifecycle/packages/package-2/package.json
Following the guidelines here: https://docs.npmjs.com/cli/version
Lerna will now call preversion, version, and postversion scripts at the appropriate times in each package when running `lerna publish`.
This allows more hooks into the lerna publish command. For example, I want to run a custom changelog generation script after package.json version is updated, but before the git commit.
Closes: https://github.com/lerna/lerna/issues/774
Added some tests to verify that the three lifecycle scripts are called. 
I wanted to mock Package.js but found no easy way to do that - the changes I was working on ended up affecting many of the tests in Publish.js, since it doesn't import or have access to the Package class directly.
This may be a breaking change because it now calls version scripts on …
> Call version lifecycle scripts during publish

- src/NpmUtilities.js
- src/Package.js
- src/commands/PublishCommand.js
- test/NpmUtilities.js
- test/Package.js
- test/PublishCommand.js
follow up for https://github.com/lerna/lerna/pull/1029 and https://github.com/lerna/lerna/issues/774
Makes npm preversion/version/postversion scripts synchronous
Add Package.runScriptSync, NpmUtilities.runScriptInDirSync
Converted Publish.js to use these to run lifecycle scripts at appropriate times
The prior pr ran the scripts async, which is slightly confusing when a preversion/version script performs side effects like `git add abc`.
Added tests for all three edited files.
It would be nice to run all the preversion/version/postversion scripts in parallel instead of sequentially, but still block on them. I thought about doing this but there were significant code changes needed that would add promises everywhere. If that's preferred I can do that too.
> Add runScriptSync for use in version lifecycle methods

- src/UpdatedPackagesCollector.js
- test/UpdatedPackagesCollector.js
- test/integration/__snapshots__/lerna-publish.test.js.snap
- test/integration/lerna-publish.test.js
The docs say [we should be able to override the meta suffix by passing the canary flag as a string value](https://github.com/lerna/lerna#--canary--c).  lerna takes this value and tries to use it to work out what range of commits it should consider when publishing a package so you can't actually override the meta suffix unless you use a commit id to do this.  Considering the commit id is added to the version number for canary releases anyway this seems redundant.
eg:
This works:
```
lerna publish --canary
...
Changes:
- package-1: 1.0.0 => 1.1.0-alpha.0a2f1a97
- package-1: 1.0.0 => 1.1.0-alpha.0a2f1a97
```
According to the docs this should work but doesn't:
```
lerna publish --canary=beta
...
lerna ERR! initialize Error: fatal: bad revision 'beta^..beta'
*kaboom!*
```
It would be useful to …
> Use --canary=<value> as prerelease tag, not commit-ish

- src/Command.js
- test/Command.js
Almost unique among our CLI flags, `--loglevel` is not currently supported as a "durable" config via lerna.json. This PR fixes that.
Additionally, only emit logging once `run()` has been called on a command.
Fixes #1035
added a unit test
> Support durable --loglevel config from lerna.json

- src/commands/PublishCommand.js
It's quite weird to see some logging about prereleases when you're actually publishing a stable version.
> Rename `npmPublishAsPrerelease` to `npmPublish` to avoid confusion

- README.md
1. Normally we lower case the header
2. The scope of a release should be just release
(See the angular repo)
> docs(README): tweak conventional message

- src/NpmUtilities.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/NpmUtilities.js
Refactor bootstrap to use same code path for all installs (eventually) and move internal npmGlobalStyle parameter into options property.
Fixes #1032
added unit tests
> Pass npmClientArgs to yarn workspaces install command

- src/Command.js
- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
When attempting to publish in a branch restricted by `--allow-branch`, the error should be thrown (and the publish process halted) _before_ the version selection prompt is rendered.
Also, `--canary` releases should _always_ be allowed, even if the branch isn't whitelisted by `--allow-branch`. Effectively, we should consider `--allow-branch` to describe "the branch (or branches) allowed to publish non-canary versions on".
It makes the error cases much less confusing, since you don't spend a lot of effort choosing versions and whatnot before the validation error occurs.
added unit tests, local testing
> Throw publish validation errors before version selection

- README.md
- package.json
- src/Command.js
- src/GitVersionParser.js
- src/Package.js
- src/PackageGraph.js
- src/PackageUtilities.js
- src/Repository.js
- src/UpdatedPackagesCollector.js
- src/VersionSerializer.js
- src/commands/PublishCommand.js
- test/Command.js
- test/GitVersionParser.js
- test/Package.js
- test/PackageGraph.js
- test/Repository.js
- test/VersionSerializer.js
- yarn.lock
This PR introduces optional support for package dependency version to be stored as url to [git hosted](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) repositories in `package.json` eg. given `package-1` that depends on `package-2`, a `package.json` of the former might look like:
```
// packages/package-1/package.json
{
version: "0.0.1",
...
dependencies: {
"package-2": "git://github.com/user/package-2.git#v0.0.1"
}
}
```
- implementation is based around the idea that `package.json` file contains a `serialized` version of package dependency versions, as full urls, that are read internally as semver ones ie. eg. `0.0.1`.
- uses `useGitVersion` and `gitVersionPrefix` options in `lerna.json` to enable the feature and optionally configure it
```
{
"lerna": "2.2.0", …
```
> Add support for git-hosted urls as sibling package dependencies

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/__snapshots__/BootstrapCommand.js.snap
- test/fixtures/BootstrapCommand/basic/package.json
- test/fixtures/BootstrapCommand/basic/packages/package-1/package.json
I introduced a performance regression in v2.3.0 with incorrect application of the `--global-style` argument to `npm install`. This fixes that.
Fixes #1050
improvements to existing unit tests
> When hoisting, only install with --global-style in leaf nodes, not root

- src/Command.js
- src/commands/PublishCommand.js
npmlog has a weird habit of repeating itself when serializing error objects passed to any level method (e.g., `log.error()`). To avoid the stutter, we must pass the stack directly (if it exists).
To address needless verbosity in the now-deduplicated stacks, do a little string splitting to only output the stack trace from the beginning of the command execution lifecycle. This keeps yargs out of the stack, for example.
The endless drama of spammy error logs.
trying to do bad things in a lerna-managed monorepo
> Truncate stack (or pass directly) when logging errors

- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- test/PackageUtilities.js
Adds a warning when you bootstrap a project where 2 or more packages share the same name.
Example:
Closes #1046
"Lerna does some weird things if there are multiple packages with the same name, like leaving one directory empty and the other one full of things, while creating symlinks correctly."
Has unit tests.
Tested with 2 existing projects that utilise Lerna to ensure it doesn't warn when packages are name uniquely. Tested it with a dummy project that had packages that shared the same name and it did show the correct warning.
Tested on Mac OSX 10.12.4, node 5.8.0
> Warn about two or more packages having the same npm package.json name

- package.json
- src/GitUtilities.js
- src/commands/ImportCommand.js
- test/Command.js
- test/GitUtilities.js
- test/ImportCommand.js
- test/UpdatedCommand.js
- test/helpers/gitInit.js
- test/integration/lerna-publish.test.js
- yarn.lock
Originally this just contains the fixes for handling issues detecting in https://github.com/lerna/lerna/issues/1058
- Outputting added for errors when something unintended happens during importing of projects.
- Added new handling to automatically skip empty commits. These are an anti-pattern I figure, but I saw them accidentally in some of my own repositories. As `git` does not seem to have a useful parameter for its `am` command we have to `skip` the command when detecting the empty commits error (my approach analyzes the error message from `git`).
- Disabling GPG signing of all "git commit" runs as this seems to break the system. Lerna should not rely on the user to disabling this behavior manually.
- We have some tests which compare the exact output of some commands. As these commands …
> Improve "import" edgecases + (i18n fixes + git tweaks)

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/yarn-hoist/lerna.json
- test/fixtures/BootstrapCommand/yarn-hoist/package.json
* add a plausibility check for cases where `typeof options.hoist === 'string'` and `options.npmClient === 'yarn'`
* Fail for this case printing a detailed error message pointing to the `yarn + lerna` guide
* `yarn` and hoisting produces unexpected results by using `npm` for nested installs #852
* The solution implemented was proposed via #1053
* Added a test case for this in `test/BootstrapCommand.js`
* Test case performs operation on prepared fixture `test/fixtures/BootstrapCommand/yarn-hoist`
* No additional effects on rest of code base expected
Debateable, my guess:
> fix: fail when --hoist and --yarn are used together

- README.md
- src/UpdatedPackagesCollector.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
- test/fixtures/PublishCommand/republish-prereleased/lerna.json
- test/fixtures/PublishCommand/republish-prereleased/package.json
- test/fixtures/PublishCommand/republish-prereleased/packages/package-1/package.json
- test/fixtures/PublishCommand/republish-prereleased/packages/package-2/package.json
- test/fixtures/PublishCommand/republish-prereleased/packages/package-3/package.json
- test/fixtures/PublishCommand/republish-prereleased/packages/package-4/package.json
- test/fixtures/PublishCommand/republish-prereleased/packages/package-5/package.json
- test/integration/__snapshots__/lerna-publish.test.js.snap
When you publish with --cd-version pre-*, and then publish with --cd-version major/minor/patch, some of your packages will still have prerelease version numbers, which is not desirable.
When you're finished with all your changes, all your packages should have non-prerelease version numbers.
This change updates the code to make it release both changed and prereleased versions if the version increment is a non-prerelease increment.
Fixes #567
I manage a lerna monorepo with ~150 packages. Our current strategy for getting rid of prerelease version numbers is to run `lerna publish --force-publish=*`. Because of this, we often get stuck in merge hell when merging feature branches, because that updates every package's package.json file. Making this change means having conflicts in only a few …
> Republish prereleased packages during subsequent non-prerelease publish

- src/ConventionalChangelogContext.js
- src/ConventionalCommitUtilities.js
- src/commands/PublishCommand.js
- test/ConventionalCommitUtilities.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
- test/integration/lerna-publish.test.js
The integration of [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) into lerna (via the `--conventional-commits` flag) currently generates one `CHANGELOG.md` file per package.
This is fine as long as lerna is configured in "independent mode", but when using lerna in "fixed mode" it might be desirable to additionally generate a consolidated `CHANGELOG.md` in the root directory of the repository.  
This "root changelog" contains changes for all packages, while the per package changelogs only list changes affecting their package.
Based on the discussion in #1015 
* Added unit tests for changelog generation
* Updated unit tests for publish command
* locally tested this in a repository
* updated integration tests, activated them, compared snapshots and …
> Generate root changelog in fixed mode

- README.md
- src/Command.js
- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- src/commands/ExecCommand.js
- src/commands/PublishCommand.js
- src/commands/RunCommand.js
- test/PackageUtilities.js
* When `--reject-cycles` is provided, `lerna` will stop with a non-zero exit code if a cycle is detected
* When a cycle is detected, the error message lists the package names in the cycle
See #1085
1. Created a local `lerna` project with a cycle
2. Reproduced the "error in cycle" warning without `--reject-cycles`
3. Ensured that `lerna` stops immediately if `--reject-cycles` and a cycle is found
> Add --reject-cycles parameter, logging packages when found

- .eslintrc.yaml
- CONTRIBUTING.md
- package.json
- src/Command.js
- src/GitUtilities.js
- src/commands/ImportCommand.js
- test/GitUtilities.js
- Added eslint rule to enforce block spacing
- Alphabetized package.json scripts and added a `watch` command for testing
- Ensured that paths are normalized so that when diffing occurs, changes show up on Windows systems
Allows devs on Windows machines to utilize features such as `lerna updated`.
- Ran the test command multiple times
- Had a coworker run my code on his Mac
- Used my changes in a repo that was not showing diffs, and after adding my changes I'm now seeing a list of updated modules after running `lerna updated`
> Fixed diffing on Windows

- test/fixtures/ExecCommand/exec-test
- test/fixtures/ExecCommand/exec-test.bat
- test/fixtures/ExecCommand/exec-test.cmd
- test/helpers/initExecTest.js
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/__snapshots__/lerna-run.test.js.snap
- test/integration/lerna-bootstrap.test.js
- test/integration/lerna-exec.test.js
- test/integration/lerna-run.test.js
- yarn.lock
Adding flags and customizing the PATH env extension to make the Windows CI stop flapping all over the place.
Getting rid of all the spurious build failures.
Painfully, waiting for Appveyor to chug through it each time I had a wild idea.
> Make integration tests less flaky on Windows

- test/ImportCommand.js
Currently, `lerna import --flatten` fails to import repositories with empty commits. This PR fixes this by detecting the case and skipping any empty commits.
This patch skips empty commits when `lerna import --flatten` is used. This is done by detecting empty patches and using `git am --skip`.
Using `lerna import --flatten` on repos with empty commits yields a cryptic error, because `git am` does not support importing of empty commits:
```
lerna ERR! execute callback with error
(node:24090) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'split' of undefined 
```
I added a unit test, and used the new import on a repository that previously failed with the above error.
> Add test for skipping empty patches during import --flatten

- src/commands/ImportCommand.js
- test/ImportCommand.js
Currently when you import a repo that follows a commit message convention that prefixes commits with something between brackets; e.g. `[TICKET-123] something changed`, the prefix is stripped due to how `git am` (or actually `git mailinfo`) works.
Since these prefixes are relevant, since they often refer to a project management system, or define the category of the commit, they should not be stripped. 
Especially since the README states the following:
> Original commit authors, dates and **messages** are preserved.
I ran the `git am` command in the `ImportCommand.js`, and tested with the command arguments, where the `--keep-non-patch` argument (forwarded as `git mailinfo -b ...`) resulted in the desired effect of only the `[PATCH]` prefix being stripped, and other prefixes remained.
~I …
> Keep non-patch subject parts when importing repository

- README.md
- src/ConventionalCommitUtilities.js
- src/commands/PublishCommand.js
- test/PublishCommand.js
…gular`
Lerna uses `angular` as changelog preset, in my case my lerna repo is hosted on a private `bitbucket` server. For the `angular` preset is built for usage with `github` in my case I want to use some other preset such as `angular-bitbucket`
this issue has already been highlighted in  #850
Unit Tests
> Add --changelog-preset option to customize --conventional-commits output

- src/FileSystemUtilities.js
- src/Package.js
- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- test/PackageUtilities.js
- test/fixtures/PackageUtilities/links/lerna.json
- test/fixtures/PackageUtilities/links/package.json
- test/fixtures/PackageUtilities/links/packages/package-1/package.json
- test/fixtures/PackageUtilities/links/packages/package-2/cli.js
- test/fixtures/PackageUtilities/links/packages/package-2/package.json
- test/fixtures/PackageUtilities/links/packages/package-3/cli1.js
- test/fixtures/PackageUtilities/links/packages/package-3/cli2.js
- test/fixtures/PackageUtilities/links/packages/package-3/package.json
- test/fixtures/PackageUtilities/links/packages/package-4/package.json
- test/helpers/pkgMatchers.js
`lerna boostrap` and `link` successfully create required symlink in dependent `node_modules/.bin/` directories. The linked files are not guaranteed to be executable, which can produce permission errors.
> Set chmod for linked binaries

- README.md
- src/commands/ExecCommand.js
- test/ExecCommand.js
- test/NpmUtilities.js
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/lerna-exec.test.js
At the moment when you run `lerna exec --parallel` You will have detailed information on where the command is running by the means of `Stout`, example each log message will be prefixed by the package name.
However, this is not the case when --parallel flag is not used. I want to make these consistant. 
I tested the changes by linking
> Add `--stream` option to `lerna exec`

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
Bad things happen during `lerna bootstrap --npm-client yarn` when `useWorkspaces` is not enabled _and_ a `workspaces` field exists in the root package.json. Instead of silent corruption, throw an informative error when this edge-case crops up.
Fixes #1124
additional tests
> Throw error in bootstrap when Yarn workspaces is misconfigured

- package.json
- src/GitUtilities.js
- test/GitUtilities.js
Added code to transform file paths used in `git add` to OS- (POSIX vs Windows) neutral form, for improved portability. 
See issue #1133
Added two tests to the `GitUtilities` test suite.
Also `npm link`ed the package to my monorepo project to verify that my changes resolve the problem in #1133
> All new and existing tests passed
Actually some tests were failing on my Windows 7 Pro system after a fresh clone and install. Ignoring those, yes, all new and existing tests passed. I expect tests to pass on CI.
> Normalize path used for `git add` in respect to OS/environment

- src/ConventionalCommitUtilities.js
`conventional-recommended-bump` cannot accept custom preset and thus this should always be `angular` or `eslint` https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-recommended-bump/presets
When pass a custom preset is passed it this shouldn't be passed to `conventional-recommended-bump` because an error will be thrown `Error: Preset: "custom-preset" does not exist `
Described above.
Unit tests
> fix: Error: Preset: "custom-preset" does not exist

- README.md
This is my first time to use Lerna, but after follow the docs, I fall into the doubt of **"command" or "commands", which is the right one?**
After searched in the source code, I knew that both "command" and "commands" are supported. But I will suggest to  **always use "commands" in the docs** to avoid ambiguity for users.
> docs: replace "command" with "commands" to avoid ambiguity

- src/commands/PublishCommand.js
This change introduces an optional, root-level `postversion` script that can be run when publishing. This happens after all per-package `postversion` scripts have been called.
Currently, `postversion` hooks can only be run per-package. It's useful to have a `postversion` hook immediately before publishing _and_ after version bumping to rebuild or do anything else which might need to use the updated global version number. In my particular circumstance, I'm using Rollup to build all the packages at the top-level and not relying on `lerna run` (for performance and memory reasons). While my circumstance is admittedly somewhat specific, the utility of adding a hook here seems pretty generalized. 
It has been run locally within a project by running `lerna publish --skip-npm` within a project. …
> Add support for root-level version lifecycle

- src/NpmUtilities.js
- src/Package.js
- src/commands/PublishCommand.js
- src/commands/RunCommand.js
- test/BootstrapCommand.js
- test/NpmUtilities.js
- test/Package.js
- test/PublishCommand.js
- test/RunCommand.js
Contribute to Lerna by solving an issue where `npm` is the hard-coded npm client while a user can choose to use `yarn`
Issue #1057 
Ran all the "yarn test" options
Added tests to verify the configuration params I added
> run/publish: Use npmClient instead of hardcoded npm

- src/VersionSerializer.js
- src/commands/PublishCommand.js
- test/Package.js
- test/PackageGraph.js
- test/PublishCommand.js
- test/VersionSerializer.js
- test/fixtures/BootstrapCommand/peer/packages/package-1/package.json
- test/fixtures/PublishCommand/normal/packages/package-3/package.json
- test/integration/__snapshots__/lerna-publish.test.js.snap
Changes to a peer version range are always semver major, and should be as broad as possible.
Until we can get fancier, we should never automatically modify them to match the new version being published (which is the current incorrect behavior).
see #1018
new test assertions
> Completely ignore peerDependencies during publish

- src/NpmUtilities.js
- src/commands/PublishCommand.js
- test/NpmUtilities.js
- test/PublishCommand.js
This avoids an unfortunate interactive prompt due to a questionable
conflation of the "version" and "publish" commands.
Fixes #1200
> Avoid interactive prompt during yarn publish

- src/GitUtilities.js
- src/commands/ImportCommand.js
- test/GitUtilities.js
- test/ImportCommand.js
- test/fixtures/ImportCommand/lerna-not-in-root/subdir/lerna.json
- test/fixtures/ImportCommand/lerna-not-in-root/subdir/package.json
Fix for #1197 
The code in the import command was computing a `targetDir` relative to the Lerna root directory, and using that in the Git patches. If the Lerna root directory wasn't in the Git root directory, that produced incorrect import locations.
This fix is needed in order to enable Lerna to import correctly if Lerna is not based in the root of the Git workspace.
Fixes issue #1197 
1. New unit test added to import command tests.  The test creates a Lerna environment where Lerna is in a subdirectory of the Git workspace, and checks that the import works correctly.  It failed before I fixed the code, and now passes.  I've added a sibling 'describe' that configures an environment where Lerna isn't in the root, in order to avoid touching all the existing tests.
1. I've manually run the …
> Fix import command so it works if Lerna root is a subdir of git root

- src/commands/RunCommand.js
- test/RunCommand.js
- test/__snapshots__/RunCommand.js.snap
Fix for #1142 
Don't know why `lerna run test` was treated differently from other commands.
This PR makes it behave "normally" and thus fixes #1142, read comment https://github.com/lerna/lerna/issues/1142#issuecomment-357299896
Fix has been tested against my code base (https://github.com/tkrotoff/react-form-with-constraints) with 2.6 (npm) and 2.7 (`"npmClient": "yarn"`)
> Treat 'lerna run test' like any other command

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
Added %v as an placeholder for the version in the commit message.
See #1196.
Added a test similar to the test for %s.
> Add %v as placeholder for raw version in `--message`

- src/Command.js
- src/utils/ValidationError.js
- src/utils/filterFlags.js
Due to changes in #1193, any verbose or silly logs called before any custom loglevel was configured were silently dropped. They were still included in lerna-debug.log, but omitted entirely from the CLI.
- Ensures error logs in ValidationError are emitted
- Filters out context callback from yargs argv
> Avoid dropping early logs below default level

- package.json
- test/InitCommand.js
- test/helpers/copyFixture.js
- test/helpers/initFixture.js
- test/integration/lerna-bootstrap.test.js
- test/integration/lerna-init.test.js
- yarn.lock
Except for yargs 10, which needs a patch release before my local stash can go forward.
Many of these deps have dropped node v4 support, thus being gated behind lerna v3.0.
Builds off of #1210, #1209, #1208, and #1207. Rebasing is fun times.
Existing tests pass.
> Bump major versions of dependencies

- src/Repository.js
- test/Repository.js
- test/__snapshots__/Repository.js.snap
- test/fixtures/Repository/yarn-workspaces/lerna.json
- test/fixtures/Repository/yarn-workspaces/package.json
If you add `useWorkspaces` to your lerna config but don't make the necessary changes in your `package.json`, `lerna bootstrap` will fail [here](https://github.com/lerna/lerna/blob/d0e8d9c5af654f52634119d2c2bd2a888b9488f0/src/PackageUtilities.js#L58).
This PR adds a validation error to make it clearer where the problem is, rather than pointing at the call to `some` on an `undefined` value for example.
Potentially it should throw if not an `Array<string>` too?
There didn't appear to be any repo workspace tests so added an example for future use using the naming convention that seemed to exist. Added one test to confirm workspaces were correctly returned as a default and another for when `useWorkspaces` is configured only.
As an aside all tests run and pass for me if I use `yarn test` but …
> Throw friendly error when workspaces are not configured correctly

- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/fixtures/PublishCommand/fixed-root-conventional/lerna.json
- test/fixtures/PublishCommand/fixed-root-conventional/package.json
- test/fixtures/PublishCommand/fixed-root-conventional/packages/package-1/package.json
- test/fixtures/PublishCommand/fixed-root-conventional/packages/package-2/package.json
This covers an edge case when the root package is also published.
The ability to publish the root package.json will be removed in v3.0.
Fixes #1215
> Avoid duplicate root changelog entries

- src/GitUtilities.js
- test/Command.js
- test/GitUtilities.js
- test/ImportCommand.js
- test/UpdatedCommand.js
- test/helpers/gitInit.js
- test/integration/lerna-publish.test.js
#1059 included an incorrect fix for avoiding testing issues for those that sign their commits by default (without an agent, apparently). It should have been a local config override, not a universal change.
Fixes #1175 
Tests updated and pass.
I started signing my commits locally, and the test suite still passes.
> Remove --no-gpg-sign from `git commit`

- src/GitUtilities.js
- test/GitUtilities.js
At the moment lerna is publish is trigger a precommit hook and a commitmsg hook
At the moment lerna triggers precommit hooks which for publishing shouldn’t be triggered I think.
> Avoid triggering pre-commit and commitmsg hooks during publish

- README.md
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/__snapshots__/BootstrapCommand.js.snap
- test/fixtures/BootstrapCommand/ignored-scripts/lerna.json
- test/fixtures/BootstrapCommand/ignored-scripts/package.json
- test/fixtures/BootstrapCommand/ignored-scripts/packages/package-postinstall/package.json
- test/fixtures/BootstrapCommand/ignored-scripts/packages/package-preinstall/package.json
- test/fixtures/BootstrapCommand/ignored-scripts/packages/package-prepare/package.json
- test/fixtures/BootstrapCommand/ignored-scripts/packages/package-prepublish/package.json
This is quite a simple change - as in the title of the PR.
Fixes #1178 . Our packages have configured lifecycle scripts, but having them ran during bootstrap in monorepo only takes time for us. We later use source files between packages within webpack, jest etc (by aliasing packages).
Snapshot test was added.
> Add --ignore-scripts flag to bootstrap command

- bin/lerna.js
- package.json
- src/Command.js
- src/cli.js
- src/commands/AddCommand.js
- src/commands/BootstrapCommand.js
- src/commands/DiffCommand.js
- src/commands/ExecCommand.js
- src/commands/ImportCommand.js
- src/commands/RunCommand.js
- src/utils/filterFlags.js
- test/Command.js
- test/ExecCommand.js
- test/PublishCommand.js
- test/helpers/yargsRunner.js
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/lerna-exec.test.js
- yarn.lock
- Enable `strict()`, with typo recommendations
- Better logging of CLI errors
- Command's runner promise is now a complete chain, not weird
- Improved help output for various commands
- Add yargs-parser `populate--` config
BREAKING CHANGE: Extra flags to certain commands must now be passed behind `--`,
they cannot be implicitly passed with other lerna-specific flags.
Foundation for future option refactoring, etc.
tests updated and pass
> feat: Upgrade to yargs 11

- src/Repository.js
Use the new `workspaces.packages` key in `package.json` when available. Otherwise fall back to current behavior.
This allows use of yarn's new [`nohoist` feature](https://github.com/yarnpkg/yarn/pull/4979)
My current project has the following relevant versions:
* `node@9.5.0`
* `yarn@1.4.1-20180208.2355` (nightly)
* `lerna@2.8.0` (with my patch)
I've only had time to test this manually in my current project. Here's what happened.
1) I enabled and used the `nohoist` feature. For more detail on how I did this see [my PR to create-react-app](https://github.com/facebook/create-react-app/pull/4001)
2) At this point, `lerna run start` failed with:
```sh
EPACKAGES Errored while collecting packages and package graph
TypeError: packageConfigs.some is not a function
```
3) I applied this patch. The …
> Add support for new yarn workspaces config format

- package.json
- src/Command.js
- src/Package.js
- src/PackageGraph.js
- src/PackageUtilities.js
- src/UpdatedPackagesCollector.js
- src/VersionSerializer.js
- src/commands/BootstrapCommand.js
- src/commands/ExecCommand.js
- src/commands/LinkCommand.js
- src/commands/PublishCommand.js
- src/commands/RunCommand.js
- src/commands/UpdatedCommand.js
- test/Command.js
- test/LinkCommand.js
- test/Package.js
- test/PackageGraph.js
- test/PackageUtilities.js
- test/UpdatedPackagesCollector.js
- test/VersionSerializer.js
- yarn.lock
A lot of existing code was re-calculating stuff that should live inside the PackageGraph; namely, the relationships between packages (localDependencies and localDependents). I made PackageGraph a subclass of Map, mostly because it already had a `.get()` method, and now it can be iterated and such. It's a lot more elegant, overall.
A big piece of the new relationship logic is based on [`npm-package-arg`](https://github.com/npm/npm-package-arg#result-object) parsing, which resolves a lot of previously half-baked logic. It's no longer necessary to pass the git version parser to the graph constructor, for example. `npm-package-arg` will also facilitate future graph manipulations, such as recognizing relative `file:` specifiers correctly.
* The package `bin` field now properly resolves an …
> PackageGraph is a Map, its nodes store relationship Sets

- src/commands/BootstrapCommand.js
- src/utils/npm-install.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/integration/package-1/build.js
- test/fixtures/BootstrapCommand/integration/package-1/package.json
- test/integration/__snapshots__/lerna-bootstrap.test.js.snap
- test/integration/lerna-bootstrap.test.js
- test/utils-npm-install.test.js
Instead of nuking the entire package.json, just edit what we don't want installed (the sibling packages that are instead symlinked). This helps avoid incorrect `package-lock.json` output due to missing `package.json` properties (name and version, specifically).
* Adds an actual integration test for `lerna bootstrap --hoist`
* Replaces bloated `cash-cp` fixture dep with basic node.js copy
Credit @compulim for the initial idea, #1287
Fixes #1136
> Preserve package.json structure during bootstrap mangling

- src/cli.js
Another conditional during CLI execution to avoid interpolating log output into piped results.
```
lerna run env --scope my-pkg | grep npm_
lerna ls | wc -l
```
Currently, both of these commands will randomly interpolate bits of log text, such as the success message and the lerna version info. It's not the end of the world, and it _doesn't_ alter the results of the piped commands (all the logging is on a different pipe, `stderr`), but it's sloppy and visually confusing.
Ran the commands above in a few local monorepos. It's just log output.
> Disable all non-error logging when stdout is piped

- commands/publish/__tests__/__fixtures__/relative-file-specs/packages/package-1/package.json
- commands/publish/__tests__/publish-command.test.js
- commands/publish/index.js
- integration/__snapshots__/lerna-publish.test.js.snap
- integration/lerna-publish.test.js
This mimics [read-package-json](https://github.com/npm/read-package-json/blob/b5a9f47c437d9b01d4e86372a3fc1bd04a89313f/read-json.js#L327)'s annotation of the current git `HEAD` during `npm publish`.
This helps users and automated processes understand "when" a given version was published in terms of a raw SHA1. Sometimes the tags get nuked, mutated, or otherwise perverted. The SHA of a git revison (theoretically) is simpler to back-track.
Updated tests.
> Add gitHead property to package.json before publish

- commands/publish/index.js
- core/git-utils/__tests__/git-utils.test.js
- core/git-utils/index.js
- integration/lerna-publish.test.js
Check the git remote upstream for changes before attempting to publish. Exit with an error if upstream changes are detected. 
Partly fixes #1177, in the case that there are remote changes at the time when `lerna publish` is run.
It is still possible that during the publish to npm, changes are added to the remote; which would make the git push fail. 
- unit tests
- manually publishing locally with `lerna publish --skip-npm`
> feat: Check for upstream changes before attempting to publish

- commands/publish/__tests__/publish-command.test.js
- commands/publish/index.js
Added a warning when `--skip-git` or `--skip-npm` arguments are used
When you use a --skip-git or --skip-npm, there is now a message:
- `lerna info Skipping git...` when `--skip-git` is used
- `lerna info Skipping npm...` when `--skip-npm` is used
Issue #1314  
I tested this change by myself ([log](https://hastebin.com/ofewinerat)):
1. I linked local Lerna on my computer
2. I cloned `https://github.com/ElemeFE/mint-ui` repository on my computer
3. I launched `lerna bootstrap`
4. I launched `lerna publish --skip-git --skip-npm`. The messages `Skipping git...` and `Skipping npm...` appeared
5. I launched `lerna publish --skip-npm`. The messages `Skipping npm...` appeared
6. I launched `lerna publish --skip-git`. The messages `Skipping git...` appeared
> feat(publish): added warning when skip-git or skip-npm are used

- core/git-utils/__tests__/git-utils.test.js
- core/git-utils/index.js
When location is the same as the cwd, return '.' instead of empty string
otherwise git diff will fail
refs #1322
Using path.relative is not enough for git params as when comparing two identical paths (`path.relative`) it will return an empty string
Fixes #1322
I added a test case and was not able to reproduce it as in #1322 anymore
> fix(utils): Use safe relative path when calling git diff

- commands/publish/__tests__/__fixtures__/lifecycle/package.json
- commands/publish/__tests__/__fixtures__/lifecycle/packages/package-1/package.json
- commands/publish/__tests__/publish-command.test.js
- commands/publish/index.js
- utils/npm-publish/__tests__/npm-publish.test.js
- utils/npm-publish/npm-publish.js
Changes Lerna to run the following [npm lifecycle scripts][1] when running `lerna publish`:
1. in root package:
1. `prepublish`
2. `prepare`
3. `prepublishOnly`
2. sequentially in each subpackage:
1. `prepublish`
2. `prepare`
3. `prepublishOnly`
3. parallel in each subpackage:
1. (the npm package is published)
2. `postpublish`
4. in root package:
1. `postpublish`
[1]: https://docs.npmjs.com/misc/scripts#description
These scripts will only be run when the `--skip-npm` flag is **not** preset and after creating git commits, so `preversion`, `version` and `postversion` scripts will execute before these. This means that a failing `prepublish` will not prevent the creation of git commits or tags, but will prevent any of the packages from being published to npm.
Lifecycle scripts are standard …
> feat: Execute atomic publish lifecycle during lerna publish

- README.md
- src/ChildProcessUtilities.js
- src/NpmUtilities.js
- src/commands/ExecCommand.js
- src/commands/RunCommand.js
- test/NpmUtilities.js
- test/integration/__snapshots__/lerna-exec.test.js.snap
- test/integration/__snapshots__/lerna-run.test.js.snap
- test/integration/lerna-exec.test.js
- test/integration/lerna-run.test.js
By default, stream output is prefixed with the originating package name. This flag allows us to disable the prefix (`--no-prefix`) so that the output can be parsed by a tool like Visual Studio Code to highlight the result by type for all packages in the same project.
We set up the monorepo with npm scripts so that we can run `tsc` and `mocha`. When the scripts are 
triggered inside Visual Studio Code, the stream prefix gets in the way and `tsc` problem matcher cannot
recognize the output.
A few test cases are added to the PR.
> feat: Support --no-prefix for streaming output

- core/git-utils/index.js
When using the `lerna publish` command the `--skip-git` option is not taking in consideration.
In this case, even when using the `--skip-git` option, before the `npm publish`, lerna is trying to get and create the tag for the publishing.
Passing the `s=--skip-git` option should avoid the git interaction on this flow.
Related to https://github.com/lerna/lerna/issues/16
- Current state:
`lerna publish --skip-git` will check and create the tags before publishing the packages
- This PR:
`lerna publish --skip-git` will skip the tags check and creation and publish the modules to NPM
- [-] I have added tests to cover my changes.
- [-] All new and existing tests passed.
Some tests are not passing, but looks like it is not related to my changes.
I need some help writing a test to cover this flow.
> fix(publish): Allow tag check to fail with strong warning

- core/git-utils/index.js
Adds the `--no-verify` flag to the git argument in `pushWithTags()`
Also, condenses the two `git push` calls into one call.
Closes #1366
#1366
This function has tests to check that the tags were pushed.
@evocateur stated in #1366 that an integration test to check for the `--no-verify` change would be unnecessary.
> fix(git-utils): Pass --no-verify to `git push`

- commands/list/__tests__/__snapshots__/list-command.test.js.snap
- commands/list/__tests__/list-command.test.js
- core/command/index.js
- core/filter-options/index.js
- core/package-graph/index.js
Adds a `--include-filtered-dependents option` which mirrors the `--include-filtered-dependencies` option.
https://github.com/lerna/lerna/issues/611
I've tested the CLI with a local lerna repo. Unfortunately, I haven't been able to run `npm test` (even on master) locally, I'm not sure what's wrong with my environment.
> feat(filters): Add `--include-filtered-dependents` flag

- src/Command.js
- src/PackageGraph.js
- src/PackageUtilities.js
- test/LsCommand.js
- test/__snapshots__/LsCommand.js.snap
Repeat of https://github.com/lerna/lerna/pull/1393 for 2.x
Adds a `localDependents` attribute to `PackageGraphNode`, modifies `addDependencies` to operate more like 3.x and rely on `PackageGraphNode`, and re-uses the BFS for `addDependents`
#611 
Tested the cli on a local repository and added a unit test.
> Add --include-filtered-dependents option

- doc/troubleshooting.md
Lerna throws a Git error when current project has uncommitted changes.
fixes: #763 
Addresses issue https://github.com/lerna/lerna/issues/763
To have better troubleshooting experience
NA
> doc(import): add note around uncommitted changes

- README.md
The `npmClient` option is already used for publish, but not written in doc
So I added it.
Documents additions from #1145
> docs: Update `--npm-client` details

- appveyor.yml
- helpers/cli-runner/index.js
- integration/lerna-exec.test.js
- integration/lerna-init.test.js
I've noticed the `master` build [is failing](https://travis-ci.org/lerna/lerna/jobs/377976519). I'm trying to fix the problem.
1. When ran on Node 10, there is a warning about `fs.promises` being experimental. This warning fails two tests, which rely on exact string matching. The warning is irrelevant in the testing context. I turned off the warnings per advice under this PR.
2. Several tests failed on Windows, because they could not find git binaries in PATH (specifically `git-receive-pack`). I found a working solution in the [go-git's AppVeyor config](https://github.com/src-d/go-git/blob/master/appveyor.yml).
3. The Windows builds were failing on `integration\lerna-exec.test.js`. It is a super weird issue with environment variables and to me it seems like a bug in Node or AppVeyor. It …
> fix(tests): Special handling for Windows CI issues

- commands/publish/__tests__/get-current-branch.test.js
- commands/publish/__tests__/is-anything-commited.test.js
- commands/publish/__tests__/publish-command.test.js
- commands/publish/index.js
- commands/publish/lib/is-anything-commited.js
- helpers/init-fixture/index.js
Running the publish command on a new initialized lerna repo, e.g. with no commits at all, will lead to an error message as reported in issue #773. This change will add a test if there are any commits and will exit the publish command with a more elaborated error message in order to push the user in the right direction what happened and why publish won't proceed.
The issue is described in #773. The error message leads the user in a wrong direction what the issue with the failing publish really is: there are no commits, therefore there's nothing to publish.
I refactored the init-fixture in order to prepare the test environment without any commits. Afterwards I wrote the tests for the added functionality, which is located in `commands/publish/lib/is-anything-commited.js` and updated the …
> fix(publish): Exit early when publishing w/o commits

- commands/add/README.md
- commands/add/__tests__/add-command.test.js
- commands/add/command.js
- commands/add/index.js
- commands/add/lib/get-range-to-reference.js
- helpers/pkg-matchers/index.js
This PR adds an `--exact` flag to `lerna add` for installing dependencies at a fixed version, and it ensures that `config.commands.add.exact` is able to override the setting.
Both `npm install` and `yarn add` are able to install dependencies at a fixed version using `--save-exact` and `--exact`, respectively. `lerna` has an `exact` option available in `init` and `publish`, and some users expect that behavior to also exist in `add`.
Closes #1470
I updated the unit tests to cover the new functionality. I also `yarn link`ed lerna and tested on a local monorepo:
**Setup**
- macOS 10.13
- Node v8.11.2
- npm 6.1.0
- yarn 1.7.0
During the course of updating the unit tests, I noticed that the `pkg-matchers` `extend` matchers were not actually returning the correct objects, so I fixed those up as …
> feat(add): Add `--exact` option to `lerna add`

- commands/bootstrap/README.md
The current hoist document link in bootstrap command README file is wrong, this PR fix it.
Modify the relative path to a correct one.
This correction could help developers find out hoist document quickly. 
Document change, tested on my fork README page.
> docs: Fix link to hoist docs in bootstrap README

- commands/list/README.md
Clarify docs like mentioned in #1559 
It wasn't clear that `list` accepted all filter options. Just changed the wording to make it more clear
> docs: Clarify that lerna list takes all filter flags

- commands/version/__tests__/version-bump-prerelease.test.js
- commands/version/index.js
in order to switch a prerelease id from alpha version to rc I needed to change condition to prioritize preid insteed of an existing preid
I juste change order of OR statement to take first preid
const resolvePrereleaseId = existingPreid => preid || (isPrerelease && existingPreid) || "alpha";
On my continuous integration workflow version my app on alpha prerelease, then on it goes to release candidate, so I try tu use lerna version prerelease --preid rc but because my previous tag was  dam/library-client@0.1.1-alpha.10 lerna 3.0.4 used my existing preid.
The solution was to change order on the test statement.
It has been test on my project, it works 👍
> fix(version): Prioritize `--preid` over existing prerelease ID

- FAQ.md
I also noticed the `using yarn as an npm client` link doesn't go anywhere anymore, but couldn't find a new url for it
> docs: Update links to commands in FAQ

- commands/add/README.md
- commands/add/command.js
Uses `yargs` [`.examples`](https://github.com/yargs/yargs/blob/HEAD/docs/api.md#examplecmd-desc) to add the examples of the readme into the CLI `--help` + also adds an example for the glob case
fixes https://github.com/lerna/lerna/issues/1608
manually by `npm link`-ing and inspecting the output of `lerna add --help`
If accepted, this method of using `.examples` could be used in the other commands as well.
It also _could_ be beneficial to generate the README's as to have a single source of truth.
> feat(add): Add examples to `--help` output

- LICENSE
In this PR, the following text has been added to the existing MIT license:
```
The following license shall not be granted to the following entities or any
subsidiary thereof due to their collaboration with US Immigration and Customs
Enforcement ("ICE"):
- "Microsoft Corporation"
- "Palantir Technologies"
- "Amazon.com, Inc."
- "Northeastern University"
- "Ernst & Young"
- "Thomson Reuters"
- "Motorola Solutions"
- "Deloitte Consulting LLP"
- "Johns Hopkins University"
- "Dell Inc"
- "Xerox Corporation"
- "Canon Inc"
- "Vermont State Colleges"
- "Charter Communications"
- "LinkedIn Corporation"
- "United Parcel Service Co"
```
I have already spoken to @kittens and @evocateur about this privately, but I do need @kittens to give us permission to make this change.
Over the last year I've been …
> Add text to MIT License banning ICE collaborators

- LICENSE
- package.json
This reverts #1616
I would like to apologize to the Lerna community for a number of things, so I guess I'll start at the beginning. Above all, I appreciate your patience as I make mistakes and learn how to become a better open source maintainer.
First, I apologize for making the rash decision to support the addition of an unenforceable clause to the project's MIT license. I failed to accurately assess the _impact_ of this change, which led me to (incorrectly) focus on the _intent_. Despite the most noble of intentions, it is clear to me now that the impact of this change was almost 100% negative, with no appreciable progress toward the ostensible goal aside from rancorous sniping and harmful drama.
I am reverting the license changes. In the future, such changes (if any) will go through a …
> chore: Restore unmodified MIT license

- commands/import/__tests__/__fixtures__/files-with-spaces/package.json
- commands/import/__tests__/import-command.test.js
- commands/import/index.js
CC @evocateur
Fixes #432
Update replace pattern when rewriting commit history to support files with spaces in them. ~Still has some edge cases where this issue will happen (see [this comment](https://github.com/lerna/lerna/issues/432#issuecomment-418580015))~
Ran my new test before and after the pattern update. Confirmed it failed before, and passes after. Also have confirmed this fix works on a repo of my own
> fix(import): Handle filepaths with spaces more robustly

- README.md
Added more info to how to run lerna in Independent mode
Just having `--independent` doesn't tell you what command to run it against (ie.g. `lerna init`).
Also it wrongly said it ignores the `version` in the `lerna.json` but you actually have to change it to `independent`.
N/A
Documentation only
> docs(readme): update independent mode instructions

- README.md
This PR adds missing `lerna create` command to `README.md`
I've noticed that `create` command exists in `commands` directory but is missing from `README.md`
`README.md` is rendering with added line
Possibly the `website` repository could be updated with this as well https://github.com/lerna/website/blob/master/index.html
> docs: Add 'lerna create' command to README.md

- README.md
I just recently downloaded and ran `lerna`, and attempted to follow the README by running `lerna`, but it returned the following error:
```
ERR! lerna A command is required. Pass --help to see all available commands and options.
```
This PR updates the README to reflect this.
> docs: Update README.md to use `lerna --help` instead of just `lerna`

- FAQ.md
- README.md
It was a little difficult to find how to set the `npmClient` to yarn in the docs (and there was a broken link on the FAQ page). This clarifies how to do so by adding `npmClient` to the `lerna.json` section of the main README and fixes the broken link in FAQ.
It was somewhat difficult to figure out how to use `yarn` as my build and package tool so this clarifies that a little bit.
Only changes are to the docs.
> docs: Clarify `npmClient` configuration

- doc/hoist.md
Before enabling an option, I want to know what are the advantages and disadvantages of doing so.
Documented one possible disadvantage of hoisting:
- Accidentally require-ing a common dependency without adding it to `package.json`
I created three packages, two with a common dependency, and one without.
The third without was still able to require the common dependency, although it had not specified it in its `package.json`.
If there are any disadvantages which are not documented here, please let me know. I may be able to add them.
> docs: note some disadvantages with hoisting

- commands/version/README.md
There are certain cases when a package will always be published, even if it's ignored using the `--ignore-changes` option:
1. The latest release of the package is a `prerelease` version, as seen here: https://github.com/lerna/lerna/blob/v3.4.3/utils/collect-updates/collect-updates.js#L62
2. One or more linked dependencies of the package have changed, as seen here: https://github.com/lerna/lerna/blob/v3.4.3/utils/collect-updates/collect-updates.js#L72
This PR updates the documentation for `version` to include this information.
I had some issues publishing a package because my `--ignore-changes` options were not being honored. After some searching, I found a comment on an issue which mentions that packages with dependents that have changes will always be published: …
> docs(version): Add cases in which --ignore-changes does not ignore a package

- commands/publish/__tests__/publish-command.test.js
- commands/publish/__tests__/publish-licenses.test.js
- commands/publish/__tests__/publish-lifecycle-scripts.test.js
- commands/publish/__tests__/publish-relative-file-specifiers.test.js
- commands/publish/__tests__/publish-tagging.test.js
- commands/version/__tests__/remote-branch-exists.test.js
- commands/version/__tests__/version-allow-branch.test.js
- commands/version/__tests__/version-bump-prerelease.test.js
- commands/version/__tests__/version-bump.test.js
- commands/version/__tests__/version-command.test.js
- commands/version/__tests__/version-conventional-commits.test.js
- commands/version/__tests__/version-git-hosted-siblings.test.js
- commands/version/__tests__/version-ignore-changes.test.js
- commands/version/__tests__/version-lifecycle-scripts.test.js
- commands/version/__tests__/version-message.test.js
- commands/version/index.js
- commands/version/lib/__mocks__/remote-branch-exists.js
- commands/version/lib/remote-branch-exists.js
Fix for a cryptic error that `lerna version` currently throws when the branch is missing in the remote. 
If the current branch doesn't exist in the remote, lerna throws the following error:
```
lerna ERR! Error: Command failed: git rev-list --left-right --count origin/xyz...xyz
lerna ERR! fatal: ambiguous argument 'origin/xyz...xyz': unknown revision or path not in the working tree.
lerna ERR! Use '--' to separate paths from revisions, like this:
lerna ERR! 'git <command> [<revision>...] -- [<file>...]'
...
``` 
This PR adds a check when `lerna version` is ran, so that it is verified first that the remote branch exists. If it doesn't exist, a new ValidationError (EMISSREMOTEBRANCH) will be thrown, i.e.:
`Branch 'foo' doesn't exist in remote 'origin'. If this is a new branch, please make …
> fix(version): Add friendly error message when remote branch is missing

- commands/import/README.md
- commands/import/__tests__/__fixtures__/multi-packages/lerna.json
- commands/import/__tests__/__fixtures__/multi-packages/package.json
- commands/import/__tests__/import-command.test.js
- commands/import/command.js
- commands/import/index.js
Add --dest option to import command, to specify import destination
We want to import repository into a specific location in a project that have multiple package directories.
lerna default the import destination to the first directory in the package list.
Unit tested in `__test__/import-command.test.js`.
Command line tested
> feat(import) Add `--dest` option to explicitly specify import destination

- commands/publish/README.md
- commands/publish/__tests__/publish-canary-no-git-reset.test.js
- commands/publish/command.js
- commands/publish/index.js
- helpers/git-status/index.js
- helpers/git-status/package.json
- integration/lerna-publish-canary.test.js
- package-lock.json
- package.json
Adds a flag which allows the user to specify whether or not the working tree should be reset or not. Defaults to true so the tree is always reset.
When used in CI (specifically for my staging builds), I want lerna to be able to publish canary versions of my packages which can then be consumed in a subsequent docker build step. Right now, once the package versions are bumped, the working tree is then reset meaning that the docker build of the package which depends on the bumped package, refers to the original package version.
Relates to this comment https://github.com/lerna/lerna/issues/962#issuecomment-440826826 in #962.
Added a unit test to ensure that when `--no-git-reset` is specified, `gitCheckout` isn't called.
Added an integration test to ensure that when `--no-git-reset` is …
> feat(publish): Add option `--no-git-reset` to leave unstaged changes in working tree

- commands/publish/index.js
- integration/lerna-publish-custom-tag.test.js
Filter out tags that are not distribution tags generated by lerna when
running publish --from-git
Our repository has an extra (unrelated) tag, and lerna fails with:
```
lerna notice cli v3.4.3
lerna info versioning independent
lerna info Verifying npm credentials
lerna http fetch GET 200 https://artifactory.in.here.com/artifactory/api/npm/verity-npm-sandbox/-/whoami 95ms
lerna ERR! TypeError: Cannot destructure property `pkg` of 'undefined' or 'null'.
lerna ERR!     at updates.map (/root/.npm/_npx/55/lib/node_modules/lerna/node_modules/@lerna/publish/index.js:219:43)
lerna ERR!     at Array.map (<anonymous>)
lerna ERR!     at chain.then.updates (/root/.npm/_npx/55/lib/node_modules/lerna/node_modules/@lerna/publish/index.js:219:39)
lerna ERR! lerna Cannot destructure property `pkg` of …
```
> fix(publish): Ignore non-release tags when detecting `from-git`

- core/command/__tests__/command.test.js
- core/command/index.js
- core/command/lib/log-package-error.js
Omits stdout/stderr output printed after a command fails, if run with `--stream`. 
Since streaming mode prints stdout/stderr as it happens, printing it again after the command completes produces a duplicate copy.
Addresses https://github.com/lerna/lerna/issues/1790.
* Manually tested with a few projects I have, passing `--stream` and not, to ensure that only a single copy of stdout/stderr is produced in each case
* Added a unit test for `Command` to ensure that extra output is not printed when `--stream` is passed. (inverse case is already covered in the unit test above it)
* Checked to make sure that `logPackageError` was not called anywhere except `Command`, and that it would produce the same behavior if it was missing the `stream` argument.
(this would only be considered a breaking …
> fix: Do not print duplicate stdio after a streaming command errors

- commands/version/README.md
- commands/version/__tests__/version-conventional-commits.test.js
- commands/version/command.js
- commands/version/index.js
Introduces a new `--no-changelog` flag that skips changelog generation when using conventional commits.
Closes #1852
Unit tests added for `fixed` and `independent` modes.
> feat(version): implement --no-changelog flag

- commands/import/README.md
I was facing this issue and found the solution on 3rd google search result. Thought it would be nice to have it in the docs itself.
> docs(import): Add a note for importing on fresh repos

- commands/import/__tests__/__fixtures__/root-packages/lerna.json
- commands/import/__tests__/__fixtures__/root-packages/package.json
- commands/import/__tests__/import-command.test.js
- commands/import/index.js
- helpers/init-named-fixture/index.js
- helpers/init-named-fixture/package.json
- package-lock.json
- package.json
Fixes `lerna import` to work in the case where packages are housed at the root level of a lerna-managed repo and use a configuration like `["myapp-*"]` for the packages configuration.
I changed the `getPackageDirectories()` method inside the import command so that any path ending in `*` is considered a package root location instead of just the ones ending in `/*`.
This fixes #1872. The change makes it possible to use `lerna import` when your packages are located at the root directory of a lerna-managed repo.
I added a new test that covers the exact case failing in the issue I reported. The test makes a new lerna repo with the `myapp-*` config, imports a subpackage, and then verifies the new history and file contents.
I had to add a new testing helper since having a static name for the …
> fix(import): Ensure compatibility with root-level package globs

- commands/publish/__tests__/publish-licenses.test.js
- commands/publish/index.js
Previously, the missing license warning just indicate that packages were missing a license. This change modifies the message to indicate it is looking for a root LICENSE file, making it easier for users to understand how to fix the problem.
Modified the error warning to be clearer. I mostly just used the language in the test description, since it seemed to make sense to me.
Resolves issue #1666 (https://github.com/lerna/lerna/issues/1666)
`npm i` + `npm test`
> fix(publish): Make the missing license warning clearer and more actionable

- core/command/__tests__/command.test.js
- core/command/index.js
- core/global-options/README.md
- core/global-options/index.js
The PR makes little changes to set concurrency option to count of logical CPU cores by default.
`--concurrency` option is set to `4` by default what can be not the best value with different count of CPUs.
Setting the option to specific number isn't good options cause the same script can be run on different servers.
Fixes #1929 
Unfortunately, my computer have 4 logical CPU what was the value before my changes, so for now I didn't test what is effected. I'm going to run lerna tests in virtual environments with different count of CPU cores.
> feat(global-options): Default concurrency to logical CPU count

- package-lock.json
- utils/npm-publish/__tests__/npm-publish.test.js
- utils/npm-publish/npm-publish.js
- utils/npm-publish/package.json
Parse the `@scope` from the full package name using `npm-package-arg` and set `projectScope`. 
The `projectScope` parameter is used by `libnpmpublish` to set the `HTTP_NPM_SCOPE` header.
When publishing scoped packages with Lerna, the `projectScope` used by `libnpmpublish` was being set using the full package name (`@scope/name`). 
This behavior caused some third-party registries to fail when verifying the `HTTP_NPM_SCOPE` header which was expected to match the package `@scope`.
These changes have been tested against the official npm registry and third-party registries to ensure that only the `@scope` parameter will go through `libnpmpublish` as the `projectScope`. 
Updated tests in `npm-publish.test` to include `@scope`.
Fixes #1968
> fix(publish) Pass only the project scope to libnpmpublish

- commands/publish/README.md
- commands/version/README.md
> fix(docs): Add missing docs for `--tag-version-prefix`

- commands/exec/index.js
- integration/lerna-exec.test.js
Thanks for the awesome project!
Handle node string error codes before setting process.exitCode in implementation of `lerna exec` command.
Added a switch statement based on the result exit code type that does the following:
- in case of a number exit code simply returns it
- in case of a string error code looks it up in `os.constants.errno` and returns a number from there
- in case of another type throws a `TypeError`
Also added a unit test, but since it can only fail under windows, and lerna does not seem to run tests under windows, I'm not sure how useful that test will be.
Yesterday I ran into a problem with `lerna exec` under windows 10 (this does not seem to happen under linux). I do the following:
```bat
lerna exec --concurrency=1 --no-bail -- custom-command
```
Where …
> fix(exec): Handle node string error codes before setting process.exitCode

- commands/import/index.js
Resolves issue when color in the output would create invalid output
Resolves the same or similar problem described here:
https://github.com/lerna/lerna/issues/1644
Basically, calling `git log` would contain colorized output that leads to problems when calling `git am ...`
Note: It resolves only when the `--flatten` parameter is set!
Kudos to random StackOverflow dude who pointed me in the direction of the right fix:
https://stackoverflow.com/a/53191568/747678
I checked out the lerna repos locally, made the change, used `npm link` and ran `lerna import --flatten some-dir` that way to see the import worked successfully.  Also ran integration test `npm run integration -- lerna-import`.
> fix(import): Avoid "unrecognized input" error from colors when using `--flatten`

- commands/version/index.js
Fixes #2025
This PR modifies the `resolvePrereleaseId` function to use the package's prerelease identifier as the default identifier when it exists, not only when when the `bump` CLI arg is an increment keyword.
Currently, the existing prerelease identifier is only used when `lerna version` is provided an increment bump. This means that if the current version is `1.0.0-beta.2`, the "Custom Prerelease" prompt's default value is `alpha`.
I ran the existing tests, but haven't added any new ones yet. I was looking at the tests in [`prompt-version.test.js`](https://github.com/lerna/lerna/blob/c599c64b11f06afe2fa16ed2c448b16de7da147a/commands/version/__tests__/prompt-version.test.js), but those use a custom `resolvePrereleaseId` function. I'd be happy to add a test, but I'm not sure what the …
> fix(version): Resolve prerelease for version without bump

- package-lock.json
- utils/check-working-tree/CHANGELOG.md
- utils/check-working-tree/__tests__/check-working-tree.test.js
- utils/check-working-tree/lib/check-working-tree.js
- utils/collect-uncommitted/CHANGELOG.md
- utils/collect-uncommitted/README.md
- utils/collect-uncommitted/__tests__/collect-uncommitted.js
- utils/collect-uncommitted/lib/collect-uncommitted.js
- utils/collect-uncommitted/package.json
This PR attempts to remedy (#1860) by adding a `utils/collect-uncommitted` that will resolve an array of uncommitted changes, for use in the error message in `utils/check-working-tree`, and anywhere else it may come in handy.
I am not 100% on the formatting for the error message and would love input on the best way to display the uncommitted changes to the user.
- adds `utils/collect-uncommitted` with tests
- require `collectUncommitted` in check-working-tree, when tree is dirty `collectUncommitted` changes for display to user in error message.
See (#1680)
Add tests in `utils/collect-uncommitted`, modify existing test in `utils/check-working-tree`, run `npx jest`, `npm run integration`. All tests pass in CI.
> feat(publish): display uncommitted changes in check-working-tree

- commands/import/README.md
- commands/import/__tests__/import-command.test.js
- commands/import/command.js
- commands/import/index.js
Hopefully this helps to digest the diff:
- [main change](https://github.com/lerna/lerna/pull/2079/commits/d70be0fd93059932b384040ff074d1144b1c1019)
- [tests](https://github.com/lerna/lerna/pull/2079/commits/b92ee16d5d301695f7a4247ae76ddb63e7af4b8b)
- [cleanup since I added a util](https://github.com/lerna/lerna/pull/2079/commits/4524624bb445bc00df7814ebeaae75e059b83479)
Direct quote from my update to the README:
> Each git commit has an **author** and a **committer** (with a separate date for each). Usually they're the same person (and date), but since `lerna import` re-creates each commit from the external repository, the **committer** becomes the current git user (and date). This is *technically* correct, but may be undesireable, for example, on Github, which displays both the …
> feat(import): Add --preserve-commit

- commands/publish/__tests__/publish-command.test.js
- commands/publish/index.js
- core/otplease/README.md
- core/otplease/__tests__/otplease.test.js
- core/otplease/otplease.js
- core/otplease/package.json
- package-lock.json
- utils/npm-publish/__tests__/npm-publish.test.js
- utils/npm-publish/npm-publish.js
- utils/npm-publish/package.json
Adds a prompt for a one-time-password (OTP) when requested from registries that use two-factor authentication (2FA).
It is currently marginally possible to publish using 2FA without this prompt, however this requires setting an environment variable prior to calling `lerna publish`, which could expire during the process of publishing packages.
I've added tests for `@lerna/otplease` and have tested publishing a monorepo for an account that requires a one-time password.
Fixes: #1091
> Add OTP prompt during publish

- commands/bootstrap/__tests__/__snapshots__/bootstrap-command.test.js.snap
- commands/bootstrap/__tests__/bootstrap-command.test.js
- commands/bootstrap/index.js
Before this change, `--force-local` option was not respected and monorepo-local packages outside of the defined --scope were still installed from the npm registry.
This commit fixes the code handling `--force-local` logic, so that:
- Local packages are resolved as links within the monorepo, as one would expect.
- The following warning IS NOT printed anymore:  _Installing local packages that do not match filters from registry_
In https://github.com/strongloop/loopback-next, we have a test that runs `lerna bootstrap --scope {pkg}` to bootstrap a single package. I noticed that our test starts to fail when the code in the package depends on changes made elsewhere in the monorepo and those changes were not released to the npm registry yet.
After further digging I found that lerna is installing …
> fix(bootstrap): respect --force-local option

- commands/__mocks__/@lerna/gitlab-client.js
- commands/version/README.md
- commands/version/__tests__/version-gitlab-release.test.js
- commands/version/command.js
- commands/version/index.js
- commands/version/lib/create-release.js
- commands/version/package.json
- core/project/__fixtures__/extends-deprecated/lerna.json
- core/project/__tests__/project.test.js
- core/project/lib/deprecate-config.js
- integration/lerna-init.test.js
- package-lock.json
- utils/gitlab-client/CHANGELOG.md
- utils/gitlab-client/README.md
- utils/gitlab-client/__tests__/GitLabClient.test.js
- utils/gitlab-client/__tests__/gitlab-client.test.js
- utils/gitlab-client/index.js
- utils/gitlab-client/lib/GitLabClient.js
- utils/gitlab-client/package.json
* Deprecate `version --github-release` in favour of `version --create-release=[gitlab|github]`.
* Add `GitLabClient` w/ `createReleases` method to create releases using GitLab API. 
* Add `createRelease` function to DRY GitLab and GitHub releases.
I think it's pretty much all there. Let me know if you need any more info.
https://docs.gitlab.com/ee/user/project/releases/index.html
https://docs.gitlab.com/ee/api/releases/index.html
I use https://gitlab.com and self-hosted GitLab instances to host my favouritestest repos. I would like the releases feature to work for them.
There are tests for deprecation, `GitLabClient` and `--create-release=gitlab`. _(`--create-release=github` is tested in existing `--github-release` tests)_
Tested locally with:
```
$ GL_TOKEN=[TOKEN] npx lerna version …
```
> Add gitlab releases to version

- commands/add/README.md
Addition to docs
lerna add only supports adding one package at a time, compared to yarn or NPM.  Makes sense to note this in the docs
It's a common mistake from developers to run code like:
```
lerna add --scope=axy express webpack
```
and then see it fail.  The docs can now show that only 1 package can be added at a time
N/A
> docs(add): Highlight single-argument limitation

- commands/publish/README.md
- commands/publish/__tests__/publish-command.test.js
- commands/publish/command.js
- commands/publish/index.js
Allow for configuration of a specific graphType, so that users can opt-in to using devDependencies when building a package graph during publish.
Closes #1437.
Added a new option, graph-type, to the publish command. The default value for this option does not change any existing behaviour.
Not sure what tests I should add for this change though. 
See #1437.
Ran the existing test suite.
> fix(publish): Add `--graph-type` option to control packages included in topological sort

- commands/bootstrap/README.md
- commands/bootstrap/__tests__/bootstrap-command.test.js
- commands/bootstrap/command.js
- commands/bootstrap/index.js
Add an option that will throw an error after printing out the hoist warnings (if there were any) to allow the bootstrap process to stop if there are version conflicts.
Fixes #2139 (and #667 although that was closed long ago).
I added a unit test, and tried it out in our project (after spending a decent chunk of time dealing with trying to get linking working...), seemed to work just great.
Please let me know if I did something that I shouldn't have or things to adjust :)
> feat(bootstrap): Add `--strict` option to enable throwing when `--hoist` warns

- CONTRIBUTING.md
This is something I ran into when beginning work on https://github.com/lerna/lerna/issues/2198. I'm happy to update the docs to only allow forking if that's the contribution model we'd rather see here, but wanted to start the discussion.
> docs: add pull request section to CONTRIBUTING.md

- commands/bootstrap/index.js
- commands/bootstrap/package.json
- package-lock.json
This PR updates `@lerna/bootstrap` so that it used `runTopologically` instead of the old `batchPackages`
`@lerna/batch-packages` and `@lerna/run-parallel-batches` aren't used anymore by any other package of the monorepo, but I don't know which is the process needed to remove them.
While updating lerna in the Babel repo, I noticed that the old cycles warnings (which should have been disappeared after https://github.com/lerna/lerna/pull/2185) were still there.
After investigating a bit, I realized that the old `partitionCycles` method was still used by `@lerna/batch-packages`.
Only using the tests in this repo
> fix(bootstrap): Run lifecycle scripts in topological queue instead of batches

- README.md
When using a custom registry, like github packages, you can change leerna.json to force publishing there, lerna already supports this but it wasnt in the reeadme.
Found an issue where this was hinted at, but there was no mention in the docs for others
n/a
> docs: Add `command.publish.registry` example

- core/filter-options/__tests__/get-filtered-packages.test.js
- core/filter-options/index.js
- core/filter-options/lib/get-filtered-packages.js
- utils/filter-packages/filter-packages.js
- Added new param `continueIfNoMatch` in `filterPackages()` to prevent an exception from being thrown if all filters did not match any package.
- Added `--continue-if-no-match` as a Filter option to enable/disable new param.
- Added documentation to the method and param. Because this option is hidden by design (because it is not really a filter), I'd like to hear what the reviewers may suggest.
My motivation is being able to execute the same command in one or more Lerna-managed mono repos, which may or may not contain the same scopes. As long as every team follows the definition of scopes, the same CI can be applied to every team.
For example:
```
lerna-repo-1/
package.json
team-a/
lib-1/
package.json
service-1/
package.json
team-b/
service-1/
package.json
service-2/
package.json …
```
> feat(filter-options): Allow command to continue if no packages are matched

- commands/publish/README.md
Fixed minot typo issue in publish README file
> docs(publish): Fix typo in option heading

- commands/add/README.md
- commands/add/__tests__/add-command.test.js
- commands/add/command.js
- commands/add/index.js
- helpers/pkg-matchers/index.js
Added peer option in add command.
Pretty similar to devDependencies.
A lot of packages need to define peerDependencies as well as other options. Currently, only manual option is available.
#1947 
- Link lerna to local machine
- Run add command with peer flag
- check peerDependencies in your package
Mac OS 10.15 Catalina, Node 12.
Added one more expect to check if peerDependency added.
> feat(add): Add `--peer` option to save target in `peerDependencies`

- __fixtures__/toposort/packages/package-cycle-extraneous-1/package.json
- __fixtures__/toposort/packages/package-cycle-extraneous-2/package.json
- commands/exec/__tests__/exec-command.test.js
- commands/run/__tests__/run-command.test.js
- utils/collect-updates/__helpers__/build-graph.js
- utils/collect-updates/__tests__/collect-updates.test.js
- utils/collect-updates/__tests__/lib-collect-dependents.test.js
- utils/collect-updates/__tests__/lib-collect-packages.test.js
- utils/collect-updates/lib/collect-dependents.js
In case of cyclic dependencies, some packages of the modified package are skipped.
packages:
```
package-cycle-1
localDependents:
package-cycle-2
package-cycle-extraneous-1
package-cycle-extraneous-2
package-cycle-2
localDependents:
package-cycle-1
package-cycle-extraneous-2
```
Let's say we changed `package-cycle-2` then the following will happen:
1. `package-cycle-2` is current node. Check local dependents of `package-cycle-2`
2. Check `package-cycle-1`
3. Add `package-cycle-1` to changed. Remember that we visit it.
4. Dive to the level below. Check local dependents of `package-cycle-1`
5. Skip `package-cycle-2` because it is current node. Remember that we visit it.
6. Skip `package-cycle-extraneous-1` because local dependents of `package-cycle-1` include `package-cycle-2`. Remember …
> fix(collect-dependents): Avoid skipping dependents of cyclic dependencies

- commands/version/lib/git-push.js
Fix #2392
Pass `--atomic` to `git push`. See [git's doc](https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-atomic)
As #2392 said.
Tested manually.
```
% git push --follow-tags --atomic --no-verify origin master
error: atomic push failed for ref refs/heads/master. status: 2
fatal: the remote end hung up unexpectedly\nTo git.easyops.local:anyclouds/next-libs.git
! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@git.easyops.local:anyclouds/next-libs.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
> fix(version): pass `--atomic` to `git push`

- commands/version/README.md
- I was looking for `--create-release` option and thought it was odd that the list of options in this README is _almost_ alphabetized.
- Looks like it started out in alphabetical order in but went out of order at some point. 
- Was confused for a few seconds because I didn't see `--create-release` and `--yes` options where I expected them to be. 
- Hopefully this shaves off a few seconds of people who read this README.
N/A.
> docs(version): Alphabetize list of options

- commands/import/__tests__/__fixtures__/files-with-non-ascii-char/package.json
- commands/import/__tests__/__fixtures__/files-with-non-ascii-char/檔案
- commands/import/__tests__/import-command.test.js
- commands/import/index.js
When importing, if any file path contain non-ascii char like Chinese, it will occur an error.
```
ValidationError: Failed to apply commit f60aec4.
Command failed: git am -3 --keep-non-patch
error: mode change for packages/91b633aa89e0fab2957cc60ec58fe8c5/"\346\252\224\346\241\210", which is not in current HEAD
error: could not build fake ancestor
Applying: rename
Patch failed at 0001 rename
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```
Because git will wrap non-ascii file path by `"`, the path replacement does not handle this.
Fix by checking `"` in regular expression in …
> fix(import): Support non-ASCII characters in file paths

- package-lock.json
- utils/github-client/__tests__/github-client.test.js
- utils/github-client/package.json
This change upgrades the octokit/enterprise-rest plugin to v6
Currently, Lerna is using v3 of the plugin and that doesn't support Github enterprise 2.18
Updated test to use GHE_VERSION 2.18
> fix(deps): upgrade octokit/enterprise-rest to v6

- commands/version/__tests__/git-push.test.js
- commands/version/lib/git-push.js
Lerna --atomic fallback now checks if the environment variable GIT_REDIRECT_STDERR has been configured. This configuration is necessary to handle a questionable Windows Server 2019 behavior. More details [here](https://github.com/lerna/lerna/pull/2393#issuecomment-589444164)
This change is necessary to support Azure Pipelines on Windows Server 2019.
* Unit testing.
* Using a modified lerna version in an Azure Pipeline.
> fix(version): --atomic fallback when GIT_REDIRECT_STDERR is enabled

- commands/publish/lib/get-unpublished-packages.js
When no versions are published, the `lerna publish` command resulted the following exception:
```
lerna ERR! TypeError: Cannot read property '0.1.11' of undefined
lerna ERR!     at /home/circleci/project/node_modules/@lerna/publish/lib/get-unpublished-packages.js:20:31
lerna ERR!     at tryCatcher (/home/circleci/project/node_modules/bluebird/js/release/util.js:16:23)
lerna ERR!     at Promise._settlePromiseFromHandler (/home/circleci/project/node_modules/bluebird/js/release/promise.js:547:31)
```
Ran unit tests, checked first publish locally.
> fix(publish): exception when publishing 1st ver

- core/conventional-commits/__tests__/__fixtures__/major-zero/lerna.json
- core/conventional-commits/__tests__/__fixtures__/major-zero/package.json
- core/conventional-commits/__tests__/__fixtures__/major-zero/packages/package-0/package.json
- core/conventional-commits/__tests__/__fixtures__/major-zero/packages/package-1/package.json
- core/conventional-commits/__tests__/conventional-commits.test.js
- core/conventional-commits/lib/recommend-version.js
According to [semver](https://semver.org), major version zero (`0.y.z`) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable. The version `1.0.0` defines the (initial stable) public API.
In my opinion formed by my experience building https://github.com/strongloop/loopback-next, in order to allow monorepos to use major version zero meaningfully, the transition from `0.x` to `1.x` must be explicitly requested by the user. Breaking changes MUST NOT automatically bump the major version from `0.x` to `1.x`.
The usual convention is to use semver-patch bumps for bugfix releases and semver-minor for everything else, including breaking changes. This matches the behavior of `^` operator as implemented by `npm` (see [docs of the semver …
> feat: preserve major version zero on breaking changes (when using conventional commits)

- README.md
Add a note to the README about the `lerna publish` functionality when using a version number where the major revision is `0`.
This fixes #2487
I'm not sure if this note describes what "should" happen, but it accurately
describes the current functionality.
The current Fixed/Locked mode documentation is not accurate when using a major version 0.  This ammendment now makes the documentation accurate for both zero and non-zero major version revisions.
This cannot be tested.
> doc(readme): Add note about fixed mode w/major version zero

- commands/version/README.md
- core/conventional-commits/__tests__/__fixtures__/fixed/scripts/config-builder-preset.js
- core/conventional-commits/__tests__/conventional-commits.test.js
- core/conventional-commits/lib/get-changelog-config.js
> fix(conventional-commits): Support modern config builder functions

- commands/create/__tests__/__snapshots__/create-command.test.js.snap
- commands/create/index.js
When creating a binary without the ES-module flag, the created CLI uses the wrong variable name when requiring `yargs`.
With the ES-module flag, however, it works.
This commit fixes the binary by using the same variable name when requiring, as the ES-module CLI does when importing.
It fixes the created CLIs
Changed it, created a new binary and it worked.
> fix(create): Use correct variable name in generated CLI output

- commands/import/index.js
Removed check for hard-coded "Patch is empty." git message in favor of `git diff COMMIT^!` check.
Fixes #2351 , fixes #2587
Command `lerna import --flatten <path/to/repo>` fails if `LANG` environment variable set to `ru_RU.UTF-8` (default value on macOS in Russia).
Example output:
```
lerna ERR! import Rolling back to previous HEAD (commit fff5b779833c57820df2f76c812fd0e89641de07)
lerna ERR! EIMPORT Failed to apply commit ef18c6c.
lerna ERR! EIMPORT Command failed: git am -3 --keep-non-patch
lerna ERR! EIMPORT Патч пустой.
lerna ERR! EIMPORT Когда вы устраните эту проблему, запустите «git am --continue».
lerna ERR! EIMPORT Если вы хотите пропустить этот патч, то запустите «git am --skip».
lerna ERR! EIMPORT Чтобы вернуться на предыдущую ветку и остановить применение изменений, запустите …
```
> fix(import): Better handling of "Patch is empty"

- README.md
Change link Greenkeeper to Snik on readme.md
Greenkeeper since June 2020 is no longer an open source project.   
Snyk not only has a generous free plan for Open Source repos and small organisations, but also offers dev-friendly security features that Greenkeeper didn’t have. They’re good people, and your repos will be in competent and caring hands.
Don't needed test
> docs: Change link to Snyk

- README.md
This PR adds a note about the state of this amazing project, as per [discussion](https://github.com/lerna/lerna/issues/2703#issuecomment-1071111156).
This project has been struggling to keep up with the growing number of issues due to the lack of active maintainers, the size of the codebase and the dependence on package managers.  Whilst technically Lerna commands still work, the stability and the overall user experience of using Lerna alongside up-to-date versions of package managers degrades with every release of npm, yarn and/or pnpm — as is indicated by a growing number of issues.
The large user base coming here risks adopting a workflow and toolset which is not future proof.
This note merely states the facts from https://github.com/lerna/lerna/issues/2703 and aims at assisting new …
> docs: add maintenance note to README

- .github/workflows/ci.yaml
- README.md
- package-lock.json
- package.json
Current issues on `main`:
```
1 critical, 10 high, 2 moderate
```
After this PR:
```
0 critical, 2 high, 1 moderate
```
---
- Mostly involved going through audit report and applying independent `npm update ...` commands and ensuring existing tests still passed unmodified.
- Addressing the final vulnerabilities involves causing tests to break and/or requiring Node 10 to be dropped, so will need dedicated focus
> fix: resolve most dependency audit issues

- commands/bootstrap/lib/has-dependency-installed.js
- commands/bootstrap/package.json
- package-lock.json
- package.json
This will require dropping support for node 10.
Allows us to fix one major source of deprecation warnings. read-package-tree was fully abandoned in favour of @npmcli/arborist
> fix: replace read-package-tree with @npmcli/arborist

- package-lock.json
- package.json
- setup-unit-test-timeout.js
- utils/npm-conf/lib/defaults.js
- utils/run-lifecycle/__tests__/run-lifecycle.test.js
- utils/run-lifecycle/package.json
- utils/run-lifecycle/run-lifecycle.js
BREAKING CHANGE
We are classing this as a breaking change because the APIs of `npm-lifecycle` and `@npmcli/run-script` are significantly different, despite `@npmcli/run-script` being the official successor to `npm-lifecycle`.
We have successfully made the integration test suite we inherited pass with this change, but there may potentially be aspects related to it which are not covered by the tests and are breaking. If you encounter any issues you believe are related to this change please open a new issue with a dedicated reproduction for us to look into!
> fix!: replace npm-lifecycle with @npmcli/run-script

- commands/publish/README.md
- core/conventional-commits/__tests__/__fixtures__/fixed/scripts/config-builder-preset.js
- core/conventional-commits/__tests__/__fixtures__/fixed/scripts/legacy-callback-preset.js
- core/conventional-commits/__tests__/__fixtures__/fixed/scripts/local-preset.js
- core/conventional-commits/__tests__/__fixtures__/fixed/scripts/null-preset.js
- core/conventional-commits/__tests__/__fixtures__/fixed/scripts/old-api-preset.js
- core/otplease/otplease.js
It appears git.io was a URL shortener service used in a few places within the workspace.
An automated issue #3116 flagged up that the service is being discontinued, so this PR simply expands the shortened URLs to their original forms.
Closes #3116
> chore: remove references to git.io

- e2e/lerna-init/lerna-init.spec.ts
- e2e/utils/index.ts
- package-lock.json
- package.json
- scripts/build.sh
Add e2e tests to cover the `lerna init` options.
- Add end to end test cases to `e2e/lerna-init/lerna-init.spec.ts` that cover the options for `lerna init`, specifically `--independent` and `--exact`. 
- Extract a util function for running `lerna init` within the e2e tests.
- Change build script to use `node-jq` (https://www.npmjs.com/package/node-jq) instead of globally-installed `jq`.
This change adds additional confidence in the consistent performance of `lerna init` over time. The build script change allows for easier contributions to the project by removing the need to manually install `jq`.
I began with failing e2e test cases, added the appropriate flag to the command run in the test, then confirmed that the test succeeded. For the build script changes, I ensured that the files …
> chore(e2e): Add e2e tests for lerna init options

- commands/bootstrap/README.md
Add a note for "--hoist" that multiple string values no longer accepted into the bootstrap command readme.
I had the same problem as the author of the issue (https://github.com/lerna/lerna/issues/2307). I spent a lot of time to find a solution. But it was so easy.
I think it should be documented.
There are no changes for code, only for documentation.
> chore: document that multiple string values no longer accepted for --hoist

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- e2e/lerna-init/lerna-init.spec.ts
- e2e/lerna-run/lerna-run.spec.ts
- e2e/utils/index.ts
Add e2e tests to cover `lerna run`.
- Add end to end test cases for the `lerna run` command.
- Extract a util function "runCLI" for running any lerna command.
- Refactor `lerna init` e2e tests to use the runCLI util.
- Update the PR template to include the "chore" change type
This change adds additional confidence in the consistent performance of lerna run over time.
I began with failing e2e test cases, added the appropriate flag to the command run in the test, then confirmed that the test succeeded. I also confirmed that the init tests succeeded after refactoring them to use the runCLI utility.
macOS Monterey v12.4, zsh shell
The testing environment is set up automatically by the e2e tests via scripts run by npm run e2e.
> chore(e2e): Lerna run e2e tests

- core/package-graph/index.js
In our monorepo with 219 packages, `lerna exec` takes 5 minutes
to check for cycles in our package graph.
Most of time is spent checking and re-checking the same nodes over
and over again.
Add a double-work breaker (a `Set` of already-visited nodes) to only
visit every package once.
Brings the time taken down to virtually nothing.
> fix: drastically reduce time taken to check for cycles

- utils/npm-install/__tests__/npm-install.test.js
- utils/npm-install/npm-install.js
This PR fixes preservation of the indentation style used in `package.json` files by copying `package.json` files to their backup location, instead of renaming them. This works because write-pkg will use the same indentation style as the `package.json` file that it is about to overwrite.
Running `lerna bootstrap` always converts spaces to tabs in `package-lock.json` indentations. This happens because Lerna temporarily replaces package.json with a tab-indented file before running `npm install`. It would be better if Lerna preserved the indentation style, like npm and write-pkg do.
Fixes #2845 
I ran `npm link` with my local copy and tested it in my project by running `npm link lerna` and `lerna bootstrap`. My `package-lock.json` files were saved with space indentations, as expected.
> fix(bootstrap): preserve indentation style in package-lock.json when running bootstrap

- .github/workflows/website-deploy.yml
It adds a new Github workflow enabling us to deploy Lerna's website to `lerna/website` repository (and thus deploy to lerna.js.org). Repository settings have been updated to create tokens and ssh keys accordingly.
> chore: add website deploy workflow

- e2e/lerna-changed/lerna-changed.spec.ts
- e2e/utils/index.ts
Add e2e tests to cover list options for the changed command.
This change adds additional confidence in the consistent performance of lerna over time.
I began with failing e2e test cases, added the appropriate flag to the command run in the test, then confirmed that the test succeeded.
> chore(e2e): add e2e tests for list options of `changed`

- commands/publish/README.md
This simple PR adds an additional info regarding how to  handle NPM automation tokens when using lerna to the README of the publish command.
Comments/suggestions welcome!
The is an issue whilst using lerna publish with the npm automation token. References issue #2788.
NPM automation tokens work only with `--no-verify-access` flag provided. That was tested by me and other users (look into the issue linked above).
Hard to tell really. That's just a documentation change, so I guess it's the closest to the new functionality than to bug fix or breaking change 🤷 
- [] Bug fix (non-breaking change which fixes an issue)
- [] My change requires a change to the documentation.
> docs: add info about npm automation tokens

- commands/run/__tests__/__fixtures__/powered-by-nx/packages/package-1/package.json
- commands/run/__tests__/run-command.test.js
- commands/run/index.js
- e2e/tests/lerna-run/lerna-run.spec.ts
Adds double-quotes around script target when running with Nx.
Closes #3215 
[Issue #3215](https://github.com/lerna/lerna/issues/3215)
[References issue in Nx](https://github.com/nrwl/nx/pull/10400)
New unit test added to test suite for command/run.  Tested with node 16, npm 8
> fix(run): add double quotes around script target containing colon

- .eslintrc.json
- __fixtures__/independent/package.json
- __fixtures__/independent/packages/package-1/package.json
- __fixtures__/independent/packages/package-2/package.json
- __fixtures__/independent/packages/package-3/package.json
- __fixtures__/independent/packages/package-4/package.json
- __fixtures__/independent/packages/package-5/package.json
- __fixtures__/normal/package.json
- __fixtures__/normal/packages/package-1/package.json
- __fixtures__/normal/packages/package-2/package.json
- __fixtures__/normal/packages/package-3/package.json
- __fixtures__/normal/packages/package-4/package.json
- __fixtures__/normal/packages/package-5/package.json
- commands/publish/__tests__/__fixtures__/integration/package-1/package.json
- commands/publish/__tests__/__fixtures__/integration/package-2/package.json
- commands/publish/__tests__/__fixtures__/integration/package.json
- commands/version/__tests__/__snapshots__/version-command.test.js.snap
- core/conventional-commits/__tests__/__snapshots__/conventional-commits.test.js.snap
- core/conventional-commits/__tests__/conventional-commits.test.js
- core/conventional-commits/package.json
- helpers/serializers/serialize-changelog.js
- integration/lerna-publish-fixed.test.js
- integration/lerna-publish-independent.test.js
- package-lock.json
- package.json
All `npm audit` warnings specific to the workspace itself will be resolved by this update
NOTE: `npm audit` warnings for userland workspaces have already been resolved
> chore: update conventional-changelog-core

- commands/publish/README.md
- commands/publish/__tests__/get-npm-username.test.js
- commands/publish/__tests__/publish-command.test.js
- commands/publish/command.js
- commands/publish/index.js
- commands/publish/lib/get-npm-username.js
Default `verifyAccess` to false for `publish`. Improve error message when encountering a npm automation token with verifyAccess=true.
Lerna will no longer try to verify the user's access (to the npm packages they are publishing) by default during `lerna publish`. Setting the verifyAccess option will still perform the verification as before. This also removes the need to ever use `--no-verify-access`, since that is now the default behavior.
This is important because the standard for authentication to npm in a CI/CD pipeline is using a [npm automation token](https://docs.npmjs.com/creating-and-viewing-access-tokens). These tokens do not support the `verifyAccess` option, due to the automation token's lack of read permissions. This PR also adds a more detailed error for the user when this …
> feat(publish): disable legacy `verifyAccess` behavior by default

- __fixtures__/cycle-intersection/lerna.json
- __fixtures__/cycle-parent/lerna.json
- __fixtures__/cycle-separate/lerna.json
- __fixtures__/licenses-missing/lerna.json
- __fixtures__/licenses/lerna.json
- __fixtures__/lifecycle/lerna.json
- __fixtures__/normal/lerna.json
- __fixtures__/toposort/lerna.json
- commands/bootstrap/__tests__/__fixtures__/ci/lerna.json
- commands/init/__tests__/init-command.test.js
- commands/init/index.js
- commands/init/package.json
- commands/run/index.js
- commands/version/__tests__/__snapshots__/version-command.test.js.snap
- core/cli/index.js
- core/command/__fixtures__/basic/lerna.json
- core/lerna/package.json
- core/package/index.js
- core/project/__tests__/project.test.js
- core/project/index.js
- e2e/tests/lerna-init/lerna-init.spec.ts
- e2e/utils/fixture.ts
- integration/__fixtures__/lerna-add/lerna.json
- integration/__fixtures__/lerna-clean/lerna.json
- integration/__fixtures__/lerna-run/lerna.json
- integration/lerna-init.test.js
- integration/lerna-publish-fixed.test.js
- package-lock.json
- website/docs/getting-started.md
When initializing lerna for the first time with `lerna init`, workspaces and nx will both be enabled by default. 
For lerna init:
- default useNx to true
- default useWorkspaces to true
- automatically add nx as a dev dependency if useNx will be true
- automatically add workspaces property to package.json if useWorkspaces will be true
- explicitly set useNx to false if lerna.json already exists and useNx is not set
- explicitly set useWorkspaces to false if lerna.json already exists and useWorkspaces is not set
- fix a bug where useNx was being reset to false whenever lerna init was run on an existing workspace with useNx: true
- refactor ensurePackageJson() and ensureLernaConfig() into one ensureConfig() function to reduce surface area for bugs in configuration that spans both config …
> feat(init): default useNx and useWorkspaces to true for new lerna workspaces

- commands/bootstrap/package.json
- package-lock.json
- package.json
- utils/pack-directory/lib/pack-directory.js
- utils/run-lifecycle/package.json
- utils/run-lifecycle/run-lifecycle.js
During the difficult migration from `npm-lifecycle` to `@npmcli/run-script` (because of lack of details from `npm`) we missed the fact (because it is undocumented) that `npm-lifecycle` actually maintains a queue for lifecycle processes and so even though they are eagerly invoked they will complete in series.
This PR adds back some equivalent behavior to the new usage with `@npmcli/run-script` by utilizing the existing `p-queue` library that lerna depends upon.
It also enables a streaming/process inheritance based approach for the "let lerna publish do all the things case".
---
PS. This issue was discovered as a result of troubleshooting why it was that ionic needed to downgrade from v4 to v5 here: https://github.com/ionic-team/ionic-framework/pull/25497
The reason this issue doesn't …
> fix(run-lifecycle): lifecycle events should run to completion in series

- commands/publish/__tests__/publish-canary.test.js
- commands/publish/__tests__/publish-command.test.js
- commands/publish/__tests__/publish-from-git.test.js
- commands/publish/__tests__/publish-from-package.test.js
- commands/publish/index.js
- core/lerna/schemas/lerna-schema.json
Users can still opt into the old behavior of ignoring `devDependencies` until v6 by passing `--graph-type=dependencies`, or setting it in their `lerna.json`.
---
Note: For the unit test _updates_ it's down to the fact that in the relevant fixture, `package-3` has a devDependency on `package-2`, so it now comes after it in the ordering.
> feat(publish): include all dependencies in package graph by default, allow no-sort

- e2e/package.json
- e2e/project.json
Some necessary npm scripts were missing when performing an ad hoc local publish outside of the e2e test flow, per our CONTRIBUTING.md guidelines
> chore: fix local publish

- commands/create/__tests__/__snapshots__/create-command.test.js.snap
- commands/create/__tests__/create-command.test.js
- commands/create/index.js
- commands/create/lib/lerna-module-data.js
- e2e/tests/lerna-diff/lerna-diff.spec.ts
When running `lerna create`, the generated files will now include a test that is actually runnable via `lerna run test`. 
Before this change, running `lerna run test` on a newly created package would produce an error that told the user to "run tests from the root", which makes no sense. This change improves developer experience when using `lerna create` by leaving the user's workspace in a runnable state immediately after package creation.
This has been tested manually, with and without --es-module, on a test lerna workspace. New unit tests have also been added as well as existing ones updated appropriately.
> fix(create): Default test script no longer errors

- core/package-graph/index.js
the fix of not touching a node twice (https://github.com/lerna/lerna/pull/2874) has a side effect so that not all scirpts are executed anymore.
this fixes it by still improving / keeping the performance benefits of the other pr.
fixes https://github.com/lerna/lerna/issues/3233
> fix(package-graph): ensure to touch all nodes

- commands/version/index.js
- e2e/tests/lerna-version/npm-workspaces.spec.ts
Fixes an issue where npm install lifecycle scripts were being run during the version command.
This change passes the --ignore-scripts option to the `npm install` command used to update the lockfile during the version command. 
This prevents npm lifecycle scripts from running, which can cause CI workflows to fail.
An end to end test has been created to cover the case of having failing lifecycle scripts during a version command. I also manually tested the change against a local environment with install scripts and git commit hooks (with [husky](https://typicode.github.io/husky/#/)).
> fix(version): Ignore npm lifecycle scripts on package lock update

- commands/create/index.js
- commands/create/package.json
- package-lock.json
- package.json
- utils/gitlab-client/__tests__/GitLabClient.test.js
- utils/gitlab-client/__tests__/gitlab-client.test.js
- utils/gitlab-client/index.js
- utils/gitlab-client/lib/GitLabClient.js
- utils/gitlab-client/package.json
Remove the `whatwg-url` dependency that is no longer needed. Also fixes a lint error with the GitLabClient constructor.
Node v10 and above has native support for the WHATWG url specification via the global "URL" class, so a dedicated package for it is no longer needed.
Unit tests cover the creation of all URLs that were affected by this change (`GitLabClient.test.js` and `create-command.test.js`). Unit tests also cover the creation of the GitLabClient, whose arguments were rearranged for the lint fix. GitLabClient itself is not exported from the utility library, so it has no public consumers to worry about.
> chore: remove unnecessary whatwg-url dependency

- core/package-graph/__tests__/package-graph.test.js
- core/package-graph/index.js
Prevents the validation error when the Package Graph is constructed without all of the dependencies listed by all packages.
This PR also removes an unused function from the package-graph unit tests.
During the changelog update of `version` and `publish`, the package graph is constructed with only the changed packages, so it can't make assumptions based on the existence of other packages in the workspace. In short, there is not enough information to properly validate what the validation error was asserting in all use cases of PackageGraph.
https://github.com/lerna/lerna/issues/3317
This change reverts a previously-added validation error. Tests checking for that validation error have been removed and all other unit/integration/e2e tests have passed. Lerna version and publish have also been …
> fix(core): prevent validation error in version/publish with `workspace:` prefix

- commands/run/command.js
- commands/run/index.js
- core/command/__tests__/command.test.js
- core/command/index.js
- core/lerna/schemas/lerna-schema.json
- e2e/tests/lerna-run/lerna-run-nx-include-dependencies.spec.ts
When nx.json is not present, packages being run will no longer include their dependencies when those dependencies would be filtered out by --scope. Using the flag `--include-dependencies` will cause them to be included again, as expected.
This preserves the default behavior of `lerna run --scope` when `useNx` is `true` and nx.json does not exist.
https://github.com/lerna/lerna/issues/3289
https://github.com/lerna/lerna/issues/3298
End to end tests have been added that cover this behavior. The functionality was also manually tested.
> fix(run): Exclude dependencies with --scope when nx.json is not present

- commands/run/index.js
- e2e/tests/lerna-run/lerna-run-nx-incompatible-options.spec.ts
- website/docs/recipes/using-lerna-powered-by-nx-to-run-tasks.md
- website/sidebars.js
Makes `lerna run` warn the user when --sort, --no-sort, --include-dependencies, and --parallel are used with a nx.json file.
This change is necessary to communicate that specific options are not available when using nx with a custom nx.json file. 
This has been tested manually and covered by e2e tests.
> fix(run): warn on incompatible arguments with useNx

- .eslintrc.json
- commands/info/README.md
- core/command/index.js
- core/lerna/commands/repair/command.js
- core/lerna/commands/repair/index.js
- core/lerna/index.js
- core/lerna/migrations.json
- core/lerna/migrations/noop/noop.js
- core/lerna/migrations/noop/noop.test.js
- core/lerna/package.json
- e2e/tests/lerna-repair/lerna-repair.spec.ts
- nx.json
- package-lock.json
Adds a new command: `lerna repair`. This command will run any available migrations which have been designed to bring a lerna workspace up to date with the latest and greatest.
This PR does not ship with a real implementation of such a migration, so instead a `noop` example migration is provided to concretely illustrate how a migration is both written and unit tested within the `lerna` package.
NOTE: the implementation for the `repair` command is intentionally inlined into the `lerna` package. Because of the way migrations are orchestrated, having `repair` be its own package would result in a cyclical dependency between it and the core package. Plus, in general, we are not looking to continue with the pattern of having an ever-increasing number of tiny published packages.
> feat(repair): add lerna repair command

- commands/run/index.js
- e2e/tests/lerna-run/lerna-run-nx-include-dependencies.spec.ts
- e2e/tests/lerna-run/lerna-run-nx-incompatible-options.spec.ts
- website/docs/lerna-and-nx.md
- website/docs/recipes/using-lerna-powered-by-nx-to-run-tasks.md
Change lerna run to only pass target dependencies to Nx when there are not target defaults already defined in nx.json
Follow up / partial reversion of:
https://github.com/lerna/lerna/pull/3345
This has been covered by e2e tests for the run command.
> fix(run): only defer to Nx when targetDefaults are defined in nx.json

- core/package-graph/__tests__/package-graph.test.js
- core/package-graph/index.js
- e2e/tests/lerna-version/independent-pnpm.spec.ts
Prevent "cannot read property 'version' of undefined" when using pnpm with independent versioning. 
Update the package graph so that if it encounters a workspace alias (workspace:\*/~/^) and cannot find the package in its provided packages, it will default to "*" instead of erroring.
There are times when the package graph needs is created without the full list of all packages in the workspace, such as when using `runTopologically` to perform versioning actions when versioning independently.
Though "*" is not equivalent to the real version of the package being referenced, it should not matter for these cases, since the package-graph is only being used to determine the order in which to perform actions on the packages.
#3343 
This has been tested manually as well as covered by e2e tests and …
> fix(core): fix "cannot read property 'version' of undefined" for pnpm + independent versioning

- commands/bootstrap/__tests__/__fixtures__/yarn-workspaces-cyclic/.yarnrc
- commands/bootstrap/__tests__/__fixtures__/yarn-workspaces-cyclic/lerna.json
- commands/bootstrap/__tests__/__fixtures__/yarn-workspaces-cyclic/package.json
- commands/bootstrap/__tests__/__fixtures__/yarn-workspaces-cyclic/workspaces/package-1/package.json
- commands/bootstrap/__tests__/__fixtures__/yarn-workspaces-cyclic/workspaces/package-2/package.json
- commands/bootstrap/__tests__/bootstrap-command.test.js
- commands/bootstrap/index.js
when the --reject-cycles flag is set and the repo is using workspaces,
run `collapseCycles()` to detect cycles before installing root package dependencies.
Currently the --reject-cycles flag does not have any effect when using workspaces.
Without workspaces it is evaluated during `runLifecycleInPackages()`, but as far as I can tell this code-path is never reached with workspaces.
This would also fix the open issue [2776](https://github.com/lerna/lerna/issues/2776)
added a test-case including fixture for yarn workspace with cyclic dependency
for local testing I have published to verdaccio with `e2e:local-publish`.
output before:
```
❯ npx lerna bootstrap --reject-cycles
lerna notice cli v5.1.1
lerna info bootstrap root only
up to date, audited 604 packages in 754ms
52 packages are looking …
```
> fix(bootstrap): reject-cycles when using workspaces

- utils/npm-publish/__tests__/npm-publish.test.js
- utils/npm-publish/npm-publish.js
Alias `strict-ssl` npm configuration setting to `strictSSL` publish `opts`.
Since lerna 4, `npm_config_strict_ssl=false` is not respected by the publish process. My team publishes to an internal private registry for CI builds to avoid polluting our `npm view [package] versions` unnecessarily, but we don't (currently?) have SSL working on that garbage heap.
While `strict-ssl` is resolved out of environment and npm settings in `@lerna/npm-conf`, there's nothing downstream looking for that. [`libnpmpublish`](https://www.npmjs.com/package/libnpmpublish) passes all extra arguments directly down to [`npm-registry-fetch`](https://www.npmjs.com/package/npm-registry-fetch), but `npm-registry-fetch` is reading for `strictSSL` rather than `strict-ssl`.
closes #2942 
I monkey patched\* the changes …
> fix(npm-publish): Allows disabling of strict SSL checks

- commands/bootstrap/README.md
This PR explains that the `--use-workspace` will cause yarn to ignore `--scope` and `--ignore`.
This PR addresses the confusion caused by --scope, --ignore being broken in project that use yarn workspace.
N/A - just doc change
> Update README.md re --use-workspace

- utils/get-npm-exec-opts/get-npm-exec-opts.js
- utils/npm-install/__tests__/npm-install.test.js
- utils/npm-run-script/__tests__/npm-run-script.test.js
The modern task runner powered by Nx has already been setting `LERNA_PACKAGE_NAME` for a while, but the legacy task runner never had this support added.
Community PR #3107 added the initial code change, but without tests, and it went a little stale so added here just so we can land it ASAP.
> fix(run): always set env LERNA_PACKAGE_NAME environment variable

- core/child-process/index.js
Replaced color wheel's `"red"` color with `"brightBlue"`.
When running a script/command on multiple packages, the output of each package may be prefixed with the package's name. 
This prefix of each package is colored differently, but the color wheel is limited to six colors in the following order: `"cyan"`, `"magenta"`, `"blue"`, `"yellow"`, `"green"` and `"red"`. The color `"red"` is used every six packages, but this color is generally associated to error messages.
Whenever I see lerna output parts of the text in red, I believe an error happened. But that is not what actually happened.
Only removing the color red would leave the color wheel with even fewer options.
Remove prefix coloring also seems not to be a good alternative, as the colors are helpful when reading the output.
As I …
> Replace `"red"` color with `"brightBlue"` on package's output prefix

- core/lerna/commands/add-caching/README.md
- core/lerna/commands/add-caching/index.js
- core/lerna/commands/repair/README.md
- website/docs/api-reference/commands.md
Adds readme files for `lerna add-caching` and `lerna repair`
And fixes a typo in the `add-caching` wizard
> docs(core): readmes for add-caching and repair

- website/docusaurus.config.js
It removes the announcement bar at the top of lerna.js.org.
> docs(core): remove announcement bar

- website/package-lock.json
- website/package.json
It upgrades Docusaurus dependencies version to the current latest `2.1.0` for Lerna documentation site.
> docs(core): upgrade docusaurus dependencies

- commands/publish/index.js
- core/package/index.js
- e2e/tests/lerna-publish/lerna-publish-npm-workspace-prefix.spec.ts
- e2e/tests/lerna-publish/lerna-publish-workspace-prefix.spec.ts
Properly removes the workspace prefix with `lerna publish`.
Pass a flag to the package graph when updating for a publish so that workspace prefixes are properly overwritten.
#3393 
An e2e test has been added to cover this case.
> fix(publish): remove workspace prefix on publish

- commands/version/lib/git-add.js
Only invoke `prettier` on changed files if the user has explicitly listed it in their root `package.json`.
It is theoretically possible that a user could end up with a copy of `prettier` in their `node_modules` despite not being a direct user of it. This situation might cause unwanted formatting changes to their files when running `lerna version`.
Nobody has explicitly reported this case to us, but it is theoretically possible and we might have seen it be indirectly reported via a community blog post.
> fix(version): only apply prettier if it was explicitly installed

- commands/publish/index.js
- e2e/tests/lerna-publish/lerna-publish-npm-workspace-prefix.spec.ts
Adds a guard to prevent interpreting all local dependencies as workspace links when a single workspace link is detected.
#3412
Lerna was assuming that if any one package is linked with the workspace: prefix, then all packages in the workspace are linked that way. This change allows workspaces to be more flexible and iterative when adopting the workspace: prefix standard. After this PR, `lerna publish` will no longer break when publishing a package with inconsistent usage of the workspace prefix for linking local dependencies.
This has been tested manually and covered by an e2e test.
> fix(publish): support inconsistent workspace prefix usage

- .github/actions/install-node-and-dependencies/action.yml
- package-lock.json
- package.json
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> chore: migrate deprecated set-output usage in actions workflows

- website/docusaurus.config.js
- website/src/components/about-lerna.module.css
- website/src/components/hero-upgrade.module.css
- website/src/components/hero-upgrade.tsx
- website/src/components/how-to-upgrade.module.css
- website/src/components/how-to-upgrade.tsx
- website/src/components/modern-lerna.module.css
- website/src/components/modern-lerna.tsx
- website/src/components/powered-by-nx.module.css
- website/src/css/custom.css
- website/src/pages/upgrade.tsx
It adds a new `/upgrade` page dedicated to showing Lerna users how to upgrade seamlessly their workspaces.
> docs(website): add lerna upgrade page

- website/docs/introduction.md
This PR removes `Babel` from the list of projects that depend on `Lerna`.
It's no longer true that `Babel` uses `Lerna` since [Babel replaced Lerna with a custom Yarn plugin](https://github.com/babel/babel/pull/12138).
Not applicable
> docs(website): remove Babel from introduction.md

- website/docusaurus.config.js
It adds the state of JS survey link on the banner for lerna.js.org.
> docs(website): add state of js banner

- website/docs/concepts/task-pipeline-configuration.md
remove the reference to `test:["build"]`, it's confusing
A tiny docs update.
n/a
n/a
> docs(website): Update task-pipeline-configuration.md

- website/docs/concepts/task-pipeline-configuration.md
On page https://lerna.js.org/docs/concepts/task-pipeline-configuration, let's explain what caret means in front of task names.
I suspect it means an "upstream dependency", just like in `turbo`, but I leave up to you maintainers to word it.
I set "allow edits by maintainers"; please take over and edit further as you like 👍 
- Let's explain what `^` means in "`^build`"
- Let's ensure we also place the noun "caret" on this page, in case somebody searches for it
We should explain all unfamiliar concepts found on the page.
n/a
> docs(website): explain the meaning of the caret symbol

- core/lerna/schemas/lerna-schema.json
This references the version 2.2.0 from the following repository. https://github.com/conventional-changelog/conventional-changelog-config-spec
The current schema only allow for a string based "changelogPreset", but lerna also supports an object syntax for this property.
Linked the proposed changes to one of my monorepos' `lerna.json` by adding a `$schema` at the beginning of the file, it works.
> fix(schema): add the other format changelogPreset can assume

- utils/npm-install/npm-install.js
check validity of bundledDependencies before iteration
According to NPM, bundledDependencies can also be a Boolean which stands for "all dependencies".
When using BundledDependencies according to NPM instructions, lerna fails to bootstrap, showing this error:
`TypeError: collection is not iterable`
I Just added an extra safety test, so before you try to iterate a value, you should first validate that it's actually an array.
> fix(utils): check validity of bundledDependencies before iteration

- commands/publish/index.js
The function `verifyWorkingTreeClean()` should have a error catch.
Just like the process in `detectFromPackage`, the function `detectCanaryVersions` and `detectFromGit` should also have the same error catch.
Run `lerna publish from git` when my monorepo packages have something in the working tree.
> chore: add catch error for verifyWorkingTree

- commands/version/README.md
- commands/version/command.js
- commands/version/index.js
- core/lerna/schemas/lerna-schema.json
- e2e/tests/lerna-version/npm-client-args.spec.ts
- e2e/version/src/npm-client-args.spec.ts
Adds configured npmClientArgs to the npm install command that happens at the end of lerna version.
#3386
Tested manually and covered by e2e tests.
> feat(version): use npmClientArgs in npm install after lerna version

- commands/version/README.md
- commands/version/__tests__/git-tag.test.js
- commands/version/command.js
- commands/version/index.js
- commands/version/lib/git-tag.js
Added support to override the executed command for `git tag` via CLI options and `lerna.json` entry.
Some CD/CI systems have no direct write access to the repository and are not able to tag the normal way via git. An optional wrapper command/alias might be defined.
- Added  unit-tests
- `./core/lerna/cli.js version -h` shows new option
> feat(version): support custom command for git tag

- e2e/run/task-runner/src/multiple-targets/assertions.spec.ts
- e2e/run/task-runner/src/multiple-targets/exec.sh
- e2e/run/task-runner/src/multiple-targets/init.ts
- libs/commands/run/src/command.ts
- libs/commands/run/src/index.ts
- libs/commands/run/src/lib/run-command.spec.ts
- website/docs/features/run-tasks.md
Because the modern task-runner in lerna understands how tasks relate to one another we can safely trigger multiple script targets at once.
This can be a really nice convenience and avoid the need to use a utility such as `npm-run-all` just for this case.
> feat(run): allow multiple script targets to be triggered at once

- e2e/publish/src/from-git-recover-from-error.spec.ts
- libs/commands/publish/README.md
- libs/commands/publish/src/index.ts
- libs/core/src/lib/npm-publish.test.ts
- libs/core/src/lib/npm-publish.ts
- libs/e2e-utils/src/lib/fixture.ts
- website/docs/faq.md
Catches the EPUBLISHCONFLICT error from npm when a version already exists. In this case, Lerna assumes that you have already published the package. 
This allows `lerna publish from-git` to be idempotent. If one or more packages fail to publish, then you can rerun `lerna publish from-git` to publish the packages that failed. 
#455
This has been tested manually and is covered by e2e tests.
> feat(publish): recover from network failure

- e2e/publish/src/from-git-recover-from-error.spec.ts
- e2e/publish/src/publish-private-packages.spec.ts
- libs/commands/create/README.md
- libs/commands/publish/README.md
- libs/commands/publish/src/command.ts
- libs/commands/publish/src/index.ts
- libs/commands/publish/src/lib/get-unpublished-packages.ts
- libs/core/src/lib/package.ts
- packages/lerna/schemas/lerna-schema.json
Adds an option `--include-private` to `lerna publish`. This allows packages marked as `"private": true` in package.json to be published. Since npm does not allow publishing packages with `"private": true`, lerna will strip out the property before the publish.
The option accepts a list of package names to be included in the publish. The packages provided are only published if those packages are deemed necessary to publish, as is consistent with lerna's existing publish behavior. Alternatively, a "*" can be provided, telling lerna to allow any private package to be published.
```sh
$ lerna publish from-git --include-private my-private-package my-other-private-package
$ lerna publish from-git --include-private "*"
```
This allows for the ability to publish packages that are currently …
> feat(publish): add --include-private option for testing private packages

- e2e/version/src/yarn-lockfiles.spec.ts
- libs/commands/version/src/index.ts
Updates yarn.lock after `lerna version` when on a version of yarn >= 2.0.0.
Yarn versions before 2.0.0 (all non-berry releases) don't put workspace dependencies in the lock file, so they do not need to be updated.
#3551
This has been tested manually and covered by an e2e test.
> fix(version): update yarn lock for versions of yarn >= 2.0.0

- integration/__tests__/lerna-publish-relative-file-spec.spec.ts
- integration/__tests__/lerna-publish-transitive.spec.ts
- libs/commands/publish/src/index.ts
fixed  error when run "lerna publish from-package"  in package.json scripts
when verifyWorkingTreeClean error happend set exitCode to 0
1、add  publish:'lerna publish from-package" to package.json->"scripts"
2、exec "npm run publish" in terminal
3、everything well done
> fix(publish): ensure zero exit code when EWORKINGTREE warning occurs

- .github/actions/install-node-and-dependencies/action.yml
Our node 16 nightly was broken because it was only respecting the package.json, now it will respect the given node 16 value
> chore: fix nightly node loading logic

- e2e/run/task-runner/src/multiple-targets/assertions.spec.ts
- e2e/run/task-runner/src/multiple-targets/exec.sh
- libs/commands/run/src/index.ts
Update the run command to use `runMany` when a single package matches the filter, but multiple targets are provided.
Nx's `runOne` function cannot accept multiple targets. Because of this, Lerna currently errors in the following case:
```
$ lerna run --scope="my-specific-package" script1,script2
```
This fix makes this case use `runMany` instead, which can accept multiple targets.
This has been tested manually and an e2e test has been added to cover this case. All existing tests pass.
> fix(run): only use run-one when not passing multiple scripts

- libs/commands/init/src/index.ts
- libs/commands/init/tsconfig.json
- libs/core/src/lib/package.ts
Removed some ts-ignore comments and any types
Make init command lib more typesafe
Existing unit and regression test.
> chore(init): enable strict type checking for init cmd

- .github/workflows/ci.yml
Reactivates unit test which failed in the past
Reactivates unit test which failed in the past
Re-activate ignored unit tests to achieve higher test coverage and regression testing.
> chore(test): reactivate unit tests previously failing on windows os platform

- website/docs/troubleshooting.md
I noticed that all flags, except for the `--conventional-commit` flag, were presented as code blocks which is why I aligned the formatting.
To ensure consistency and draw attention to the flag, I aligned the formatting.
I looked the the Markdown preview here on GitHub.
> docs: use code block for conventional commit flag

- website/docs/features/version-and-publish.md
Adds clarity around how to accomplish synchronized fixed versions in Lerna.
#3569 
N/A
> chore(docs): add --force-publish to docs for versioning strategies

- libs/commands/publish/src/index.ts
- libs/commands/publish/src/lib/publish-from-package.spec.ts
Add a warning log entry when `lerna publish` fails that includes the package name.
Sometimes there error returned from the registry doesn't include the package name. For instance `ERR! E402 You must sign up for private packages`.
> feat: Add name of package that fails to publish

- e2e/publish/src/custom-publish-directories.spec.ts
- libs/commands/publish/README.md
- libs/commands/publish/src/index.ts
- libs/core/src/lib/package.ts
- website/docs/concepts/configuring-published-files.md
- website/sidebars.js
Adds support for a "lerna.publish" config option in package.json files. This tells Lerna which directory to publish for the package and if any assets should be copied to the directory before publishing.
This allows for publishing directories outside of the source directory of the package. This is especially helpful for patterns where the output of a package is written to a `dist/packages/...` directory in the root of the workspace.
This has been tested manually and covered by e2e tests
> feat(publish): support custom directory per-package

- e2e/publish/src/custom-publish-directories.spec.ts
- libs/commands/publish/src/index.ts
- website/docs/concepts/configuring-published-files.md
The auto-copying feature introduced in v7.0.0 adds unexpected behaviour to the traditional contents option and in general is too magical, reverting and updating docs accordingly.
Fixes #3731
> fix(publish): revert auto-copying of assets to custom contents/directory

- packages/lerna/migrations.json
- packages/lerna/project.json
- packages/lerna/src/migrations/remove-invalid-lerna-config/remove-invalid-lerna-config.test.ts
- packages/lerna/src/migrations/remove-invalid-lerna-config/remove-invalid-lerna-config.ts
In a very old lerna.json config I discovered this:
```sh
{
"lerna": "2.0.0-rc.5",
"packages": [
"packages/*"
],
"version": "0.0.0"
}
```
We do not do anything with a `"lerna"` field in `lerna.json` so this migration removes it if it is present
> feat(repair): add migration to remove unused "lerna" field from lerna.json

- libs/commands/publish/src/index.ts
Catches another possible form of publish conflict error from npm.
Some permission setups on npm were causing a 403 error instead of the EPUBLISHCONFLICT code, and this ensures they are caught appropriately.
This has been tested manually by publishing packages to npm with conflicts, observing the error in Lerna, then testing it again with this change and observing Lerna properly swallow the error.
> fix(publish): catch publish conflict 403 error from npm

- libs/commands/publish/src/lib/fetch-config.ts
- libs/commands/publish/src/lib/get-projects-with-unpublished-packages.spec.ts
- libs/commands/publish/src/lib/get-projects-with-unpublished-packages.ts
fixes #3746 
There is a missing mapping of strict-ssl for unpublished projects lookup.
This results into falsy unpublished projects.
We are using lerna to automatically determine which packages are unpublished. We have encountered the issue it tries to publish packages again and again regardless if they are already published.
With debugging I have found out there is an issue using the given strict-ssl attribute. It is not passed to pacote correctly.
In general it is the same issue like here #2952 
I have debugged everything and also tried to write an unit test which should cover this scenario.
- there are some tests failing (perhaps of my Windows environment)
> fix: fix strict-ssl mapping for node-fetch-registry during unpublished projects lookup

- libs/commands/publish/README.md
- website/docs/features/version-and-publish.md
Adds clarification to the docs about Lerna always using `npm` to publish packages.
#2460
> chore(publish): clarify that `npm` is always used to publish packages

- e2e/watch/src/watch-with-nx.spec.ts
- e2e/watch/src/watch.spec.ts
- libs/commands/version/src/lib/git-add.ts
Use async functions from prettier in order to support prettier 3+
#3765 
This has been tested manually against workspaces on prettier 2.8.8 and 3.0.0.
> fix(version): use async functions to support prettier 3+

- integration/__tests__/lerna-publish-conventional-fixed-prerelease.spec.ts
Updates the publish integration tests to reflect the bug that was fixed in semver - https://github.com/npm/node-semver/pull/533
Semver used to consider the difference between "v1.0.0" and "v1.0.0-alpha.0" to be a prerelease. Now it considers that a major version bump. This change means that Lerna will now consider "v1.0.0-alpha.0" to "v1.0.0" a major version bump and therefore breaking change, which triggers the release of all other packages when in fixed mode.
I believe that Lerna's new behavior (due to this semver change) makes sense and is consistent with Lerna's existing pattern of publishing all packages when a breaking change is made.
> chore(version): update tests to reflect new behavior of semver

- libs/commands/version/src/lib/git-add.ts
PR #3766 brought prettier 3 support by using asynchronous prettier APIs, but missed one `await` when calling `.format(...)`.
Because of this, `fs.writeFileSync(...)` is called with a Promise instead of a string and throws an exception:
> TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type
> string or an instance of Buffer, > TypedArray, or DataView. Received
> an instance of Promise
This exception is caught by the try/catch, and the file is never written.
Worse, when formatting files that are not supported by prettier (ex: yarn.lock), `.format(...)` fails and the promise rejection isn't handled, which lead to the following exception:
> UndefinedParserError: No parser could be inferred for file "..."
and Node terminates the process, which is probably the cause of #3788 …
> Fix file formatting on git add

- e2e/init/src/init-npm.spec.ts
- e2e/init/src/init-pnpm.spec.ts
- e2e/init/src/init-yarn.spec.ts
- e2e/init/src/init.spec.ts
- integration/__tests__/lerna-init.spec.ts
- libs/commands/init/README.md
- libs/commands/init/src/command.ts
- libs/commands/init/src/index.ts
- libs/e2e-utils/src/lib/fixture.ts
- package-lock.json
- packages/legacy-structure/commands/create/package.json
Detects the package manager during `lerna init` by looking for existing lockfiles. Also makes the `init` command perform an installation task after the initialization to ensure Lerna is downloaded from the registry.
This makes it easier to add Lerna to a project that is managed by Yarn or Pnpm.
This has been tested manually and covered by e2e tests.
> feat(init): detect existing package manager and auto-install packages

- website/docs/recipes/using-pnpm-with-lerna.md
When I add the `useWorkspaces` field following this guide I get the following error:
```bash
lerna notice cli v7.1.5
lerna ERR! ECONFIGWORKSPACES The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration. Alternatively, you can manually provide a list of package globs to be used instead via the "packages" option in lerna.json.
```
> docs: removal of deprecated field

- website/docs/api-reference/commands.md
I reported an issue in [https://github.com/lerna/lerna/issues/3807](https://github.com/lerna/lerna/issues/3807) which was resolved by NX folks that happened when running a Lerna command without installing the project dependencies. @fahslaj wrote on the same issue that although this may work, it is not recommended. Lerna commands should always run in a project with all its dependencies installed. This PR adds the docs to state that limitation
Boot up the website locally and check the limitation section in `/api-reference/commands` page.
> docs(website): adds hotloading limitation section to commands

- libs/commands/publish/README.md
This updates the readme to include information about how the preid appendix is generated since the user cannot control that piece.
When setting up and learning Lerna, I was not able to find any documentation as to what caused preids to increment. This made it very hard to setup an appropriate dev/ci workflow for my team. I had to look at the source code and use trial and error to tell people that in their local env, they cannot release-amend-release. Additionally release-rebase-release may or may not work depending on the history length.
(Separately, it may be worth evaluating a development workflow that's sha based instead of commit count based to address cases where amends or rebases happen)
Hope others find this addition useful. Please feel free to add additional context I've missed …
> Update README.md to discuss preid appendix

- e2e/publish/src/custom-publish-directories.spec.ts
- libs/commands/publish/README.md
- libs/commands/publish/src/index.ts
- libs/commands/version/README.md
- libs/commands/version/src/command.ts
- libs/commands/version/src/index.ts
- libs/core/src/lib/package.ts
- packages/lerna/schemas/lerna-schema.json
Usually in our CI we do `lint` -> `test` -> `built` -> `publish`  
but it has been a pain to build package contents (in other directory like `./dist`)
and then sync the generated version by `lerna publish` with a `version` hook in the root of the monorepo.
In case we configure a publish directory different than the source folder  
we will need a custom script to sync the new version, otherwise the old version will be published.
I've tested it in my monorepo with the build output of this branch and it worked:
the config interpolation happens earlier than before and sync the `dist` output.
> feat(version): sync the version of the package contents

- libs/commands/version/README.md
- libs/commands/version/src/command.ts
- libs/commands/version/src/index.ts
- packages/lerna/schemas/lerna-schema.json
Option to not pass `--ignore-scripts` while updating the lock file after the version bump.
Currently I'm using the old `lerna bootstrap` and I noticed that when versioning/publishing the npm lock file gets incomplete as `lerna version` is ignoring the scripts by default while updating it.
I've used `patch-package` to remove this code locally and it works as expected.
> fix(version): option to not ignore scripts on lock update

- libs/commands/version/src/index.ts
When instructing lerna to sign tags, `gpg` often runs out of memory because it isn't designed to be run in parallel ([see similar issue on another repository](https://github.com/sbt/sbt-pgp/issues/168)). Thus, when `signGitTag` is set to true, signing must be carried out serially.
If `gitTagSign` is set to true, this PR will sign tags one after another, omitting the race condition
Signing git tags
I'm not sure how to test it, as we'd need to somehow mock `gitTag` to check if we call it concurrently or not.
- https://github.com/lerna/lerna/issues/2554
> Fix crash in `lerna version` when using `gitSignTag`

- package-lock.json
- package.json
- packages/child-process/package.json
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
Updates package.json files to properly exclude Node 14.
Node 14 reached end of life on Apr 30th, 2023 (https://endoflife.date/nodejs), which was two months before the release of Lerna v7. Lerna v7 never intended to support Node 14 and the persistence of ^v14.17.0 in the package.json `engines.node` property for Lerna@^7 was an oversight.
> fix(core): update package engines.node to correctly include only >=16

- libs/commands/version/src/index.ts
Right now the lock-file is updated before the root `version` script, but if we edit some custom stuff in that hook (with `lerna exec --since` then it won't be possible to include those changes in the lock file and that seems undesirable.
Tested locally with a custom hook updating the package.json files of the changed packages.
> fix(version): update lock files after the version hook

- e2e/version/src/positional-arguments.spec.ts
- libs/commands/version/README.md
- libs/commands/version/src/command.ts
- libs/commands/version/src/index.ts
- libs/commands/version/src/lib/version-command.spec.ts
- libs/core/src/index.ts
- libs/core/src/lib/listable-format-projects.spec.ts
- libs/core/src/lib/listable-format-projects.ts
- packages/lerna/schemas/lerna-schema.json
Outputs projects which reveive a new version in json format.
Follwoing json format is supported:
```json
[
{
"name": "footer",
"version": "0.0.4",
"private": false,
"location": "/home/ammo/git/lerna-getting-started-example/packages/footer",
"newVersion": "0.0.5"
},
{
"name": "header",
"version": "0.0.4",
"private": false,
"location": "/home/ammo/git/lerna-getting-started-example/packages/header",
"newVersion": "0.0.5"
},
{
"name": "remixapp",
"version": "0.0.4",
"private": true,
"location": "/home/ammo/git/lerna-getting-started-example/packages/remixapp",
"newVersion": "0.0.5"
}
]
```
#3720
> feat: add json option to version command

- libs/commands/diff/src/command.ts
- libs/commands/diff/src/index.ts
- packages/lerna/src/commands/diff/command.ts
- packages/lerna/src/commands/diff/index.ts
- packages/lerna/src/commands/diff/lib/get-last-commit.ts
- packages/lerna/src/commands/diff/lib/has-commit.ts
- ensures that typechecks are executed for diff command during build
using require does not execute type checks during `npx nx run-many -t build --parallel=3`
Ensure typechecking during build for libs as well. Remove warnings/errors from eslint regarding `require` statements
All unit tests and integration tests still pass.
> chore: use import instead of require for bundling diff command

- libs/core/src/lib/conventional-commits/__fixtures__/fixed/scripts/local-preset-async.js
- libs/core/src/lib/conventional-commits/get-changelog-config.ts
- libs/core/src/lib/conventional-commits/index.spec.ts
- package-lock.json
- packages/lerna/package.json
new 7.x.x versions of conventional changelog presets use async factory functions createPreset (see https://github.com/conventional-changelog/conventional-changelog/pull/1045)
Fixes #3871
#3871
unit and e2e tests
- [x I have added tests to cover my changes.
> fix: support changelog-presets using async factory funcs

- e2e/version/src/yarn-lockfiles.spec.ts
Updates the assertion in yarn-lockfiles.spec.ts to match what yarn 4 produces.
Our e2e tests run on the latest version of Yarn berry, which is now 4.0.0. This version of Yarn changed lockfiles slightly.
> chore(e2e): update lockfile expectation to match yarn 4

- libs/commands/info/src/command.ts
- libs/commands/info/src/index.ts
- packages/lerna/src/commands/info/command.ts
- packages/lerna/src/commands/info/index.ts
- ensures that typechecks are executed for info command during build
using require does not execute type checks during `npx nx run-many -t build --parallel=3`
Ensure typechecking during build for libs as well. Remove warnings/errors from eslint regarding `require` statements
All unit tests and integration tests still pass.
> chore(info): use import instead of require for info cmd

- libs/commands/list/src/command.ts
- libs/commands/list/src/index.ts
- libs/commands/list/tsconfig.json
- packages/lerna/src/commands/list/command.ts
- packages/lerna/src/commands/list/index.ts
remove some ts-ignore. 
Use import instead of require to enable type checks during build
Make list command more typesafe.
All tests still pass.
> chore(list): enable strict type checking

- libs/commands/init/src/command.ts
- libs/commands/init/src/index.ts
- packages/lerna/src/commands/init/command.ts
- packages/lerna/src/commands/init/index.ts
ensures that typechecks are executed for init command during build
using require does not execute type checks during npx nx run-many -t build --parallel=3
Ensure typechecking during build for libs as well. Remove warnings/errors from eslint regarding require statements
All unit tests and integration tests still pass.
> chore(init): use import instead of require

- libs/commands/changed/src/command.ts
- libs/commands/changed/src/index.ts
- libs/commands/changed/src/lib/changed-command.spec.ts
- libs/commands/changed/tsconfig.json
- libs/commands/diff/src/lib/get-last-commit.ts
- libs/commands/diff/src/lib/has-commit.ts
- libs/commands/import/src/index.ts
- libs/commands/version/src/index.ts
- libs/core/src/index.ts
- libs/core/src/lib/check-working-tree.ts
- libs/core/src/lib/command/index.ts
- libs/core/src/lib/describe-ref.ts
- packages/lerna/src/commands/changed/command.ts
- packages/lerna/src/commands/changed/index.ts
remove some ts-ignore. 
Use import instead of require to enable type checks during build
Make changed command more typesafe.
All tests still pass.
> chore(changed): enable strict type checking

- libs/commands/exec/src/command.ts
- libs/commands/exec/src/index.ts
- libs/commands/exec/src/lib/exec-command.spec.ts
- libs/commands/exec/tsconfig.json
- libs/core/src/lib/command/index.ts
- packages/lerna/src/commands/exec/command.ts
- packages/lerna/src/commands/exec/index.ts
updated ts-config to enable strict type checking
Use import instead of require to enable type checks during build
Make exec command more typesafe.
All tests still pass.
> chore(exec): enable strict type checking

- .github/workflows/ci.yml
- e2e/version/src/sign-git-tag.spec.ts
- libs/commands/version/src/index.ts
Since `lerna@7.3.0`, running `lerna version` with independent versioning and the `--sign-git-tag` flag would always create `0`, `1`, ... `N` as tags instead of the actual version.
A recent fix done in #3832 introduced a new issue. In TypeScript, `for (const tag in tags)` would iterate through the array of tags. However, `for...in` returns a list of keys on the `tags` object, meaning that it iterates through the indices of the array, rather than the values. This means that regardless of what version number we are creating a tag for, that value will never be used - its index in the `tags` array will be used instead.
The issue is a bit niche, as it only happens when the repo is configured to use `independent` versioning and the `--sign-git-tag` flag is used.
This is an issue because your …
> fix(version): create correct independent tags when using --sign-git-tag

- e2e/version/src/tag-version-separator.spec.ts
- libs/commands/version/src/command.ts
- libs/commands/version/src/index.ts
- libs/core/src/lib/collect-updates/collect-project-updates.ts
- libs/core/src/lib/describe-ref.spec.ts
- libs/core/src/lib/describe-ref.ts
Allows users to customize the tag version separator for independent projects in cases where they do not want to use the default of `@`.
Example usage can be seen in the e2e test for this project.
Closes #3902 #3837
e2e and unit tests added.
> feat(version): custom tag-version-separator for independent projects

- libs/commands/list/src/index.ts
Fixes #3970.
Without this code, any code trying to consume the output of `lerna list` would only get the first 8k.
It has not yet been tested other than the simple repro I put into #3970 .
> fix(list): flush output before exiting

- libs/commands/version/src/index.ts
- libs/commands/version/src/lib/create-release.ts
After the [8.1.0](https://github.com/lerna/lerna/releases/tag/v8.1.0), the version command does not create a GitHub release when using a custom version seperator. This was because the `createRelease` function had a hard coded `@` in tag name filter.
Fixes: https://github.com/lerna/lerna/issues/3974
To test, I create a test repo made changes to a packages and commit them. I then ran:
```
node /tmp/lerna/dist/packages/lerna/dist/cli.js version --tag-version-separator '-' --conventional-commits --create-release github --yes
``` 
And was able to see the new GitHub release created with the appropriate tag
> fix(version): create release when using custom tag-version-separator

- website/docs/recipes/using-pnpm-with-lerna.md
`useWorkspaces` has been removed since 7.0.0 and should not be mentioned.
Mentioning `useWorkspaces` is confusing as it has been removed.
N/A
> fix(docs): remove mention of useWorkspaces

- website/docs/troubleshooting.md
❌ `conventional-commit`
✅ `conventional-commits`
ex)
https://github.com/lerna/lerna/blob/cbe01baf7b591f89d830b5526a6d7043d98a2047/integration/__tests__/lerna-publish-conventional-independent.spec.ts#L26
To prevent others from encountering the following error
> chore(docs): fix typo

- libs/commands/publish/README.md
- libs/commands/publish/src/command.ts
- libs/commands/publish/src/index.ts
- libs/commands/publish/src/lib/throttle-queue.spec.ts
- libs/commands/publish/src/lib/throttle-queue.ts
The aim is to provide a way to fix #3962 .
This is opened to validate the implementation design and get feedback on the specific values that should be used as defaults.
Currently known limits when uploading to NPM:
* Burst limit of 25/500 modules per 24h (depending on account/already-published modules)
Add three publishing options:
* `--throttle` to enable/disable throttling
* `--throttle-size`: the 'bucket size' to use when throttling
* `--throttle-delay`: Once the bucket is full, the minimum time between the end of a module upload and the start of an other module's upload
Throttling is enabled by default when publishing to NPM. The throttling implementation is designed to allow changes in the implementation/maintaining different implementations without too much trouble
See #3962: NPM …
> feat(publish): enable throttling when publishing modules

- libs/commands/version/src/index.ts
- libs/commands/version/src/lib/create-release.spec.ts
- libs/commands/version/src/lib/create-release.ts
This pull request introduces the truncateReleaseBody function, which ensures that release body content does not exceed the specified maximum length for GitHub and GitLab release descriptions, thereby preventing errors.
https://github.com/lerna/lerna/issues/3833
https://github.com/lerna/lerna/issues/3833
> fix(version): truncate release body based on maximum size of VCS client

- website/docs/lerna-and-nx-version-matrix.md
Lerna depends on nx < 20, not < 19, according to its current `package.json`.
I ended up with a weird nx version mismatch because `lerna` was installing v19 but I was installing v18 in my package.json. I ultimately removed `nx` and allowed `lerna` to manage `nx` itself, but the docs should still be updated.
N/A
> docs: update lerna-and-nx-version-matrix.md to allow nx v19

- package-lock.json
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
The credit should go to @ghiscoding - I'm just back-porting his fix to the same bug in lerna-lite to lerna here.
The newer version of cosmicconfig does not suffer from the issue that
it defaults to looking for .config.json the way 8.x does.
This upgrade implicitly fixes the underlying issue that lerna has for the
same reason.
Fixes #4061
lerna-lite used to have the same bug, you can read the full context here:
1. https://github.com/lerna-lite/lerna-lite/issues/729
2. https://github.com/cosmiconfig/cosmiconfig/issues/313
3. https://github.com/cosmiconfig/cosmiconfig/pull/311
`npm test && npm run integration`
The tests all passed, but for the integratin tests 2 of them failed with the logs pasted below. They were failing the same way on `main` prior to my changes so I'm assuming this to be …
> fix(core): avoid reading empty .config.json, upgrade cosmiconfig@v9.0.0

- libs/commands/publish/README.md
- libs/commands/publish/src/index.ts
- libs/commands/publish/src/lib/publish-command.spec.ts
Add possibility to provide a filepath to the `--summary-file` option in the publish command  
This PR introduces a new capability to the Lerna library, allowing users to specify a filepath instead of a directory path for the `--summary-file` option. 
Previously, users could only provide a directory path and the created filename is statically defined in the code as `lerna-publish-summary.json` , which limited the flexibility in defining the location and name of the summary file. 
With this change, users can now directly specify the full path, including the filename, where the summary should be saved.
In the `publish-command.spec.ts` file, adding a new test case where a filepath is passed as input parameter.
> feat(publish): support full file path for --summary-file

- packages/lerna/schemas/lerna-schema.json
Fixing warning "Property extends is not allowed" on "extends" property in user's lerna.json.
When user has "extends" property in user's lerna.json, for example,
```json
"extends": "my-base-config"
```
VS Code shows "squiggly" warning _"Property extends is not allowed"_ on the `extends` property:
Fix the VS Code warning on the `extends` property.
This is follow-up on the "extends" feature implemented the [commit](https://github.com/lerna/lerna/commit/0b28ef5fe8e4fc376870848acc8f6ccc0905a7b2), which was for [Issue #1281](https://github.com/lerna/lerna/issues/1281).
Use the updated `lerna-schema.json` file in the `lerna` package installation.  After the fix, VS Code no longer shows that warning:
> fix: add extends property in schema

- libs/commands/list/README.md
ndjson.org domain expired and has been taken over by a website with malware. This update will use the official ndjson spec readme.
Discussion: https://github.com/ndjson/ndjson.github.io/issues/24
> docs: use ndjson spec link instead of ndjson.org

- package-lock.json
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
This PR bumps `@octokit/rest` from `19.0.11` to `20.1.2` to resolve security vulnerabilities. There are no relevant breaking changes ([link](https://github.com/octokit/rest.js/releases/tag/v20.0.0)), since `lerna@8` already dropped support for Node 16 and below.
Resolves https://github.com/lerna/lerna/issues/4149.
N/A
> chore(deps): bump @octokit/rest from 19.0.11 to 20.1.2

- libs/core/src/lib/cli.ts
This PR fixes the lockfile bug as described here: https://github.com/lerna/lerna/issues/4167
When `NX_ISOLATE_PLUGIN` was set to `false`, it uncovered an issue where Nx defaults `npm_config_legacy_peer_deps` environment variable to `true`.  This means that subsequent `npm install` command is updating the lockfile (i.e. `package-lock.json`) in an unexpected manner.
Fixes #4167
Manually making the changes locally and testing it.
> fix(version): disable legacy peer deps behavior by default

- libs/core/src/lib/npm-publish.spec.ts
- libs/core/src/lib/npm-publish.ts
#4133 reported an issue about `README.md` not being visible in verdaccio when publishing. Looking into the issue I found https://github.com/lerna/lerna/issues/1843 that says that `verdaccio` requires `readmeFilename` field to exist on the package.json that is published. 
with the 8.1.5 release, the [read-package-json](https://www.npmjs.com/package/read-package-json) was swapped out for [@npmcli/package-json](https://www.npmjs.com/package/@npmcli/package-json), and the `npm-publish.ts` file was updated to use `load`, but it should be using `prepare` since the npm-publish needs to normalize the package.json data and the documentation states that `prepare` should be used before publishing.
Currently if you run the project locally and visit the verdaccio web ui there is no README.md file. Any …
> fix(publish): ensure README file names are populated on package.json

- e2e/version/src/positional-arguments-pnpm.spec.ts
- libs/core/src/lib/command/index.ts
- libs/legacy-core/src/lib/command/index.ts
- package-lock.json
- package.json
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
~~[`structuredClone`](https://nodejs.org/api/globals.html#structuredclonevalue-options) is natively available as of Node v17, so no need to have an extra dependency for this anymore~~
We could use Object spreading since we're only accessing root properties
---
I'm sure people from the wider @e18e ecosystem cleanup (like @43081j, @benmccann, @Fuzzyma, @outslept & @talentlessguy) will be very happy to see these kind of changes as well
> refactor: use native object spreading
