lerna/lerna

- lib/commands/updated.js
> pass in `--tags` argument to git describe

- lib/commands/publish/npmPublishAsPrerelease.js
- lib/commands/publish/npmUpdateAsLatest.js
- lib/commands/publish/publishChangedPackages.js
- lib/commands/publish/updateChangedPackages.js
- lib/commands/updated/index.js
- lib/utils/checkUpdatedPackages.js
> Added support for @org/packages

- lib/commands/bootstrap/linkDependenciesForPackage.js
> Revert symlinking packages

- bin/lerna.js
- lib/commands/bootstrap/bootstrapPackages.js
- lib/commands/bootstrap/index.js
- lib/commands/bootstrap/linkDependencies.js
- lib/commands/bootstrap/linkDependenciesForPackage.js
- lib/commands/publish/index.js
- lib/commands/publish/npmPublishSemiAtomic.js
- lib/commands/publish/npmUpdateAsLatest.js
- lib/commands/publish/publishChangedPackages.js
- lib/commands/publish/updateChangedPackages.js
- lib/init.js
- lib/utils/getPackages.js
> Add Independent mode

- lib/commands/publish/npmUpdateAsLatest.js
Apparently @kittens had no reason for this
> Remove stable tag

- lib/commands/bootstrap/linkDependencies.js
- lib/commands/publish/npmPublishAsTemp.js
- lib/commands/publish/npmUpdateAsLatest.js
- lib/utils/checkUpdatedPackages.js
- lib/utils/logger.js
- lib/utils/progressBar.js
Fixes #69 and replaces #70.
Basically this just removes and restores the progress bar whenever something gets logged.
cc @evocateur
> Make logger work with progress bar

- bin/lerna.js
- lib/init.js
- lib/utils/gitUtils.js
This just allows you to run lerna from any directory inside a git repo.
> Use git directory instead of cwd

- lib/commands/publish/index.js
- lib/commands/publish/npmPublishAsTemp.js
- lib/commands/publish/npmPublishSemiAtomic.js
- lib/commands/publish/npmUpdateAsLatest.js
- lib/commands/publish/publishChangedPackages.js
- lib/commands/publish/updateChangedPackages.js
- lib/utils/logger.js
- lib/utils/npmUtils.js
- package.json
See: https://www.dropbox.com/s/y33j4lh1tikfrxw/lerna-prompts.mov?dl=0
> Improve interactivity while publishing

- lib/commands/bootstrap/installExternalPackages.js
Happy to update using a different style of variable initialization if that's preferred.
This change fixed `lerna bootstrap` for me.
> Fixes #104: TypeError during lerna bootstrap

- src/GitUtilities.js
- test/PublishCommand.js
> Only push current branch on publish

- bin/lerna.js
- src/commands/PublishCommand.js
- test/PublishCommand.js
Resolves #106
This causes publish not to `git add/commit/tag/push` at all
cc @cpojer
> Add --skip-git flag

- src/commands/InitCommand.js
I'm just commenting this out for now because I want to figure out a way to add this unless people explicitly want it to be public.
> Temp remove adding private in package.json during init

- bin/lerna.js
- src/Command.js
- src/UpdatedPackagesCollector.js
- src/commands/PublishCommand.js
- src/commands/UpdatedCommand.js
- test/UpdatedCommand.js
I don't really like this name. Thoughts @hzoo?
> Replace FORCE_VERSION with --force-version flag

- src/commands/InitCommand.js
Fixes https://github.com/lerna/lerna/issues/154
@thejameskyle
> make sure lernaJson is defined

- README.md
> README: 2.x rewrite

- README.md
> README: fix small typo

- src/UpdatedPackagesCollector.js
- test/UpdatedCommand.js
> Fix --force-publish

- README.md
- bin/lerna.js
- src/commands/PublishCommand.js
- test/PublishCommand.js
> --yes flag for auto confirmation

- README.md
[As requested](https://twitter.com/left_pad/status/739253946846437377) 😄
> Update language in README.md

- src/Command.js
- src/GitUtilities.js
- src/Repository.js
- test/GitUtilities.js
fixes #175 
Thoughts on this approach?
> Run git init on lerna init

- .gitignore
This makes `git status` much nicer for vim users.
> Add *.swp files to .gitignore

- src/commands/BootstrapCommand.js
> Fix version mismatch in `lerna bootstrap`

- .travis.yml
- README.md
- package.json
- src/ChildProcessUtilities.js
- test/UpdatedCommand.js
- test/_initFixture.js
If we are going to support node 0.10
- 0.10 doesn't have child_process.execSync
---
Fixes https://github.com/lerna/lerna/issues/157
> Use sync-exec for node 0.10

- README.md
- bin/lerna.js
- src/commands/ImportCommand.js
- src/index.js
- test/ImportCommand.js
- test/_initExternalFixture.js
- test/_initForeignFixture.js
- test/fixtures/ImportCommand/basic/lerna.json
- test/fixtures/ImportCommand/basic/package.json
- test/fixtures/ImportCommand/external/package.json
- test/fixtures/ImportCommand/foreign/package.json
The problem:  I have a package in a stand-alone repository that I want to pull into a lerna repo.
The solution: `lerna import`.
Imports a package from a foreign repository _with commit history_.
> Lerna import

- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/basic/packages/package-2/package.json
> Revert "Bootstrap: copy `main` property from package.json"

- .travis.yml
wait till after dropping node 0.10, 0.12
> Test on all major versions of Node

- bin/lerna.js
Skip the "Invalid lerna command: undefined" error message.
<p align="center">⬇️ </p>
> Just emit usage when run with no command

- src/FileSystemUtilities.js
This just happened to catch my eye.
> Use `logifySync` decorator for `FileSystemUtilities.readdirSync`

- src/ChildProcessUtilities.js
- src/commands/RunCommand.js
> Log stdout on run command errors

- src/FileSystemUtilities.js
- src/Package.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/basic/packages/package-2/cli.js
- test/fixtures/BootstrapCommand/basic/packages/package-2/package.json
- test/fixtures/BootstrapCommand/basic/packages/package-3/cli1.js
- test/fixtures/BootstrapCommand/basic/packages/package-3/cli2.js
- test/fixtures/BootstrapCommand/basic/packages/package-3/package.json
- test/fixtures/BootstrapCommand/basic/packages/package-4/package.json
Minor refactor of some methods for easier to read code using `async.series`
> Handle packages with binaries

- appveyor.yml
- package.json
- src/ChildProcessUtilities.js
- src/FileSystemUtilities.js
- src/UpdatedPackagesCollector.js
- src/commands/BootstrapCommand.js
- src/commands/PublishCommand.js
- test/BootstrapCommand.js
- test/ChildProcessUtilities.js
- test/ImportCommand.js
- test/PackageUtilities.js
- test/PublishCommand.js
- test/_initExternalFixture.js
- test/_initFixture.js
> Add windows support

- src/FileSystemUtilities.js
- src/commands/InitCommand.js
* Add path check
* Remove second argument in call from InitCommand
> Make unlinkSync synchronous (fixes #324)

- README.md
- bin/lerna.js
- src/commands/ExecCommand.js
- test/ExecCommand.js
> Add ignore support to exec

- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/PackageUtilities.js
- test/fixtures/BootstrapCommand/basic/packages/package-1/index.src.js
- test/fixtures/BootstrapCommand/basic/packages/package-1/package.json
- test/fixtures/BootstrapCommand/lifecycle-scripts/lerna.json
- test/fixtures/BootstrapCommand/lifecycle-scripts/package.json
- test/fixtures/BootstrapCommand/lifecycle-scripts/packages/package-postinstall/package.json
- test/fixtures/BootstrapCommand/lifecycle-scripts/packages/package-preinstall/package.json
- test/fixtures/BootstrapCommand/lifecycle-scripts/packages/package-prepublish/package.json
- test/fixtures/PackageUtilities/toposort/lerna.json
- test/fixtures/PackageUtilities/toposort/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-cycle-1/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-cycle-2/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-cycle-extraneous/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-dag-1/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-dag-2a/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-dag-2b/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-dag-3/package.json
- test/fixtures/PackageUtilities/toposort/packages/package-standalone/package.json
Fixes #73, #279. Lays some groundwork for #342.
> Run pre/post install scripts during bootstrap

- src/commands/LsCommand.js
- test/LsCommand.js
- test/fixtures/LsCommand/basic/packages/package-5/package.json
as mentioned in #402, this pr will bring private repos to _lerna ls_.
* test for LsCommand is running
* eslint 0 erros 🙂
> issue #402: display private packages in lerna ls

- src/ChildProcessUtilities.js
* Increase maxBuffer
* Make maxBuffer value a constant
Ported from https://github.com/asini/asini/pull/16.
Fixes https://github.com/lerna/lerna/issues/278.
Need to merge non-squash to preserve @rygine's authorship.
> Increase maxBuffer

- README.md
small update to the examples to list the most recent beta version
> Update README examples with current beta version

- .travis.yml
- appveyor.yml
- package.json
> Drop support for node 0.10 and node 0.12

- README.md
Fixes typo introduced in https://github.com/lerna/lerna/pull/390.
> Update README.md (s/--exclude/--ignore/)

- README.md
- bin/lerna.js
- src/GitUtilities.js
- src/commands/PublishCommand.js
- test/PublishCommand.js
> [Feature] Allow git remote to be changed for publish

- .travis.yml
- appveyor.yml
- package.json
- src/commands/BootstrapCommand.js
- test/BootstrapCommand.js
- test/fixtures/BootstrapCommand/zero-pkgs/lerna.json
- test/fixtures/BootstrapCommand/zero-pkgs/package.json
> 467: lerna bootstrap succeeds with 0 packages

- README.md
> Document --yes flag for clean

- README.md
- bin/lerna.js
> Document the publish --exact flag

- README.md
> Add a note about lerna-wizard.

- package.json
- src/ChildProcessUtilities.js
- src/Package.js
- src/commands/InitCommand.js
- yarn.lock
> Drop `object-assign`.

- test/BootstrapCommand.js
Looks like the merge of https://github.com/lerna/lerna/pull/507 was a little rocky; my apologies.  Here's a fix to the broken tests.
> Fix broken hoisting tests

- lerna.json
> redo labels [skip ci]

- src/Package.js
> Use correct logger method in Package method.

- package.json
- src/ChildProcessUtilities.js
- test/UpdatedCommand.js
- test/_initExternalFixture.js
- test/_initFixture.js
- yarn.lock
> Remove `sync-exec`.

- test/PublishCommand.js
I broke the build :cry:.  This fixes it.  Thanks to @gigabo for [catching it](https://github.com/lerna/lerna/pull/599#issuecomment-280487962)
> Fix midair collision

- src/commands/ImportCommand.js
- test/ImportCommand.js
Fixes #477 and #478. Let me know how to approach testing; I'd prefer not to go backwards on coverage.
> Use package paths to determine import target directory

- CHANGELOG.md
Want to we want to put here to explain the issue/how it's solved?
cc @Gongreg, @spudly
> changelog [skip ci]

- README.md
either comment it or just remove this
> updates [skip ci]

- src/UpdatedPackagesCollector.js
- test/UpdatedCommand.js
Allows you to update versions in private packages, even if no public packages have changed. Fixes #570.
> Include private packages in the list of updated packages

- src/NpmUtilities.js
- test/PublishCommand.js
> Merge current process.env when using --registry flag

- README.md
- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/fixtures/PublishCommand/normal-exact/lerna.json
- test/fixtures/PublishCommand/normal-exact/package.json
- test/fixtures/PublishCommand/normal-exact/packages/package-1/package.json
- test/fixtures/PublishCommand/normal-exact/packages/package-2/package.json
- test/fixtures/PublishCommand/normal-exact/packages/package-3/package.json
- test/fixtures/PublishCommand/normal-exact/packages/package-4/package.json
- test/fixtures/PublishCommand/normal-exact/packages/package-5/package.json
> Add support for `exact` flag in lerna.json

- src/NpmUtilities.js
- test/BootstrapCommand.js
Fixes comment from PR https://github.com/lerna/lerna/pull/654#issuecomment-285215839 intended to fix #652.
> fix(env): fix issue where env isn't merged with --registry flag

- yarn.lock
Not sure how I missed this, perhaps future validation of some sort is in order?
> chore: update lockfile with changes from #665

- test/BootstrapCommand.js
Turns out order-sensitive data structures do not play well with non-deterministic, slow-as-molasses Windows filesystems.
> Fix flapping test

- README.md
- src/commands/ExecCommand.js
- test/ExecCommand.js
This is a rebased #276 that I was unable to force-push an update to.
Fixes #275
> exec: Add LERNA_PACKAGE_NAME env var

- appveyor.yml
- test/BootstrapCommand.js
- test/CleanCommand.js
- test/Command.js
- test/ExecCommand.js
- test/ImportCommand.js
- test/InitCommand.js
- test/LsCommand.js
- test/NpmUtilities.js
- test/Package.js
- test/PublishCommand.js
- test/RunCommand.js
- test/UpdatedCommand.js
- test/helpers/exitWithCode.js
- test/logger.js
Hoping to make the tests a bit easier to grok for new contributors.
> Refactor tests to better employ Jest patterns

- src/NpmUtilities.js
- src/commands/RunCommand.js
see discussion at #592 
see commit messages for details of changes
> Fix (some) error repetition when running failing `npm run` script

- README.md
Add documentation for `--conventional-commits` option
> Add documentation for --conventional-commits option

- README.md
- src/Command.js
- src/UpdatedPackagesCollector.js
- test/UpdatedCommand.js
Re: https://github.com/lerna/lerna/issues/706
> Remove --only-explicit-updates

- CONTRIBUTING.md
feel free to edit, just getting it started
> basic source code structure explanation [skip ci]

- package.json
- yarn.lock
Upgrades the [progress](https://github.com/visionmedia/node-progress) module in order to fix issues when bootstrapping due to window dimensions.
More info about the issue here https://github.com/visionmedia/node-progress/issues/130
https://github.com/lerna/lerna/issues/283
Linking the new version locally and running bootstrap with small window size
> Upgrade progress

- CHANGELOG.md
My first time using `lerna-changelog` 🙆 
Easy reading: https://github.com/lerna/lerna/blob/changelog-rc.0/CHANGELOG.md
/cc @hzoo @gigabo
> v2.0.0-rc.0 changelog

- appveyor.yml
- package.json
- test/config/integration.json
- test/fixtures/BootstrapCommand/integration-lifecycle/lerna.json
- test/fixtures/BootstrapCommand/integration-lifecycle/package-1/.gitignore
- test/fixtures/BootstrapCommand/integration-lifecycle/package-1/index.src.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-1/package.json
- test/fixtures/BootstrapCommand/integration-lifecycle/package-2/cli.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-2/index.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-2/package.json
- test/fixtures/BootstrapCommand/integration-lifecycle/package-3/cli1.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-3/cli2.js
- test/fixtures/BootstrapCommand/integration-lifecycle/package-3/package.json
- test/fixtures/BootstrapCommand/integration-lifecycle/package-4/package.json
- test/fixtures/BootstrapCommand/integration-lifecycle/package.json
- test/helpers/constants.js
- test/helpers/fixtureUtils.js
- test/helpers/replacePlaceholders.js
- test/helpers/serializePlaceholders.js
- test/integration/__snapshots__/lerna-bootstrap.test.js.snap
- test/integration/lerna-bootstrap.test.js
- yarn.lock
Improving the robustness of the longest pole (`lerna bootstrap` integration tests).
There are some frustrating failures in AppVeyor right now.
The integration tests are a little hard to grok, still.
> Fix bootstrap integration tests

- README.md
- doc/hoist.md
Add new Hoisting doc.
Update README to reference it.
For motivation, see #724.
No code changes, just doc.
> Update README.md and docs to better explain hoisting

- src/FileSystemUtilities.js
- src/commands/BootstrapCommand.js
- src/commands/CleanCommand.js
- src/progressBar.js
- test/BootstrapCommand.js
- test/CleanCommand.js
- test/FileSystemUtilities.js
- test/fixtures/CleanCommand/basic/packages/package-3/package.json
- test/fixtures/CleanCommand/integration/lerna.json
- test/fixtures/CleanCommand/integration/package.json
- test/fixtures/CleanCommand/integration/packages/package-1/package.json
- test/fixtures/CleanCommand/integration/packages/package-2/package.json
- test/fixtures/CleanCommand/integration/packages/package-3/package.json
- test/integration/__snapshots__/lerna-clean.test.js.snap
- test/integration/lerna-bootstrap.test.js
- test/integration/lerna-clean.test.js
Instead of one-at-a-time, pass chunked lists of directories to `rimraf --no-glob`.
`--no-glob` is somewhat faster, and we might as well let `rimraf` burn through a concurrency-based, exists-filtered chunk as fast as it can.
This is building up to fixing the require.resolve() stuff I broke last week, and records my attempts to get a freaking `yarn` local tarball install to bloody work.
Unit tests, new integration test, local runs.
> Pass multiple directories to rimraf

- src/UpdatedPackagesCollector.js
Don't filter the packages for updates if we don't have to, with support for `--force-publish` arrays or boolean. The following examples are now equivalent:
```sh
lerna publish --force-publish
lerna publish --force-publish=*
lerna publish --force-publish foo,bar
lerna publish --force-publish foo --force-publish bar
```
A bit of minor refactoring from the tail end of #779. At some point, we should probably add this flag to the options config (and maybe rename it `--force`?)...
Local testing with `--loglevel=silly`
> Clarify --force-publish argument handling

- README.md
- doc/troubleshooting.md
There are several re-occurring problems, or hiccups when someone starts using Lerna. Instead of users relying on github issues we should provide documentation to them detailing already known issues and the solutions to them.
(Requires #782 to be merged)
Added docs, which may need improvement and more bullet points since I only put in place the issues I could remember recently coming up in the issue tracker.
Only entries which provide solutions to problems should be added. 
Not sure if we should extend the FAQ section with information of this type, that's why I thought we should create a special place where we store them.
With this approach we may prevent future issues being submitted and present Lerna with the most support we can to make the life of others as painless as possible.
No …
> Add troubleshooting docs

- FAQ.md
People using Lerna could easily miss out features like hoisting and may think that it just isn't as great as it can be. I think mentioning hoisting in as many places as we could is a must. Since it saves time for humans and machines as well.
Added hoisting section to FAQ.
#792
Change contains only docs.
> Add bootstrap performance section to FAQ.

- package.json
- src/UpdatedPackagesCollector.js
- src/cli.js
- yarn.lock
Fixes #447 
Trusting upstream libraries (`npmlog`, `is-ci`) to be well-tested.
> Disable progress bars when running in CI or non-interactive shell

- src/commands/PublishCommand.js
- test/PublishCommand.js
- test/__snapshots__/PublishCommand.js.snap
- test/fixtures/PublishCommand/independent/packages/package-5/package.json
- test/integration/__snapshots__/lerna-publish.test.js.snap
Pretty straightforward.
#810 brought up the issue, but then other issues were raised. So this just fixes the easy one.
Added a private package to the independent fixture and made the tests pass.
> Do not log private packages as published

- README.md
Improved the step-by-step explanation of `lerna publish`.
1. Ordered list indentation does not work properly on Github, so even though the markdown is correct, it renders wrong making the output super confusing. I tried multiple permutations to try to get it to indent properly, and this was the one that worked (though the original markdown is better).
2. As I understand it, it is adding/removing package versions to the dist-tag, not tags.
The steps are misleading in their current form.
N/A
> Update publish docs in README

- .travis.yml
- appveyor.yml
Skip notification on new versions of npm (default in node 8) on CI
See https://github.com/lerna/lerna/pull/899#issuecomment-313295335
> Skip update notifiers on CI

- README.md
Updated the references to beta versions of lerna to 2.0.0 in the README
Updates the README to reflect 2.0.0 has been released, and is no longer in beta.
N/A
> Update v2 references in README.md

- src/ConventionalCommitUtilities.js
- test/ConventionalCommitUtilities.js
Update the header in the generated changelog to point to the Conventional Commits site: https://conventionalcommits.org
The repo for [standard-version](https://github.com/conventional-changelog/standard-version) only mentions the required commit format at the very end of its readme. 
`npm run test`
> Update generated changelog header

- src/Command.js
Fixed a small spelling mistake in a comment for `Command.js`.
Fixes a super minor spelling mistake in a comment that I noticed while reading through the code.
```diff
-UpdatedPackgaesCollector
+UpdatedPackagesCollector
```
A comment, does not need a test.
> Fixed spelling mistake in a comment for Command.js

- src/cli.js
Return error message and exit with non-zero code. Disable help on fail
so that the error is clearly visible.
Resolves #809
See issue #809
It's not, only seeing command specific tests. If I should add a test please point to where it should be added.
> Return error and exit on invalid command

- FAQ.md
Added "root package.json" and "CI setup" sections to the FAQ
A little bit overdue but as discussed in https://github.com/lerna/lerna/issues/866 I've extracted advices given to me with my personal experience and provided additional clarifications for mentioned topics as new sections for the FAQ
> Add root package.json and CI setup sections to FAQ

- README.md
Let me know if you want any changes done!
N/A
> Add shield example to README.md

- src/FileSystemUtilities.js
- src/commands/InitCommand.js
- test/FileSystemUtilities.js
- test/InitCommand.js
- test/integration/__snapshots__/lerna-init.test.js.snap
Create the packages directory when `lerna init` is ran in an empty directory.
https://github.com/lerna/lerna/issues/704
> Create configured "packages" directories during lerna init

- src/PackageUtilities.js
Help for future cases of #1024
No testing, will do something tomorrow.
Just added a log, is it a feature?
> Log  which packages are throwing ECYCLE error

- README.md
https://github.com/lerna/lerna/issues/1014#issuecomment-333423241
I have an issue when trying to use yarn workspace with lerna. I don't config `workspaces: ["packages/*"]`. I believe we should have better document and more friendly error message for this error.
> Update workspace document

- src/commands/LinkCommand.js
Remove the git requirement for linking packages.
Being able to run lerna in a local dev environment without having to publish a github repo. 
All current test pass.
> Remove git requirement from link command

- src/PackageUtilities.js
- src/commands/BootstrapCommand.js
- test/UpdatedCommand.js
- test/integration/lerna-exec.test.js
Minor cleanup
Cause I am anal
No need.
> Clean up code missed by lint settings

- README.md
- package.json
- src/Command.js
- src/commands/AddCommand.js
- src/index.js
- test/AddCommand.js
- test/fixtures/AddCommand/basic/lerna.json
- test/fixtures/AddCommand/basic/package.json
- test/fixtures/AddCommand/basic/packages/package-1/package.json
- test/fixtures/AddCommand/basic/packages/package-2/package.json
- test/fixtures/AddCommand/basic/packages/package-3/package.json
- test/fixtures/AddCommand/basic/packages/package-4/package.json
- test/fixtures/AddCommand/unchanged/lerna.json
- test/fixtures/AddCommand/unchanged/package.json
- test/fixtures/AddCommand/unchanged/packages/package-1/package.json
- test/fixtures/AddCommand/unchanged/packages/package-2/package.json
- test/helpers/pkgMatchers.js
- test/integration/lerna-add.test.js
- yarn.lock
* adresses #998
* implement AddCommand
* add AddCommand unit tests
* add lerna-add integration tests
* add pkgMatchers for better manifest assertions
**Given**
```sh
.
├── lerna.json
├── package.json
└── packages
├── package-1
│   └── package.json # 1.0
├── package-2
│   └── package.json # 2.0
├── package-3
│   └── package.json # 1.0
└── package-4
└── package.json # 1.0
```
```sh
lerna add @test/package-1 
lerna add @test/package-1@~1
lerna add @test/package-5
lerna add @test/package-1@2 
lerna add @test/package-1 --scope=@test/package-1 
lerna add @test/package-1 --scope=@test/package-2 
lerna add @test/package-1 --ignore=@test/package-2
lerna add @test/package-{1,2} --ignore=@test/package-2 
```
* adresses #998
* solution designed according to …
> feat: implement lerna add <pkg>[@version] [--dev]

- src/commands/AddCommand.js
- test/AddCommand.js
- test/fixtures/AddCommand/existing/lerna.json
- test/fixtures/AddCommand/existing/package.json
- test/fixtures/AddCommand/existing/packages/package-1/package.json
- test/fixtures/AddCommand/existing/packages/package-2/package.json
> Preserve existing deps with lerna add

- README.md
n/a
Better docs. Closes #914 
n/a
> add docs on how to publish scoped packages

- src/cli.js
This adds a warning message to the user when there's a typo in a command.
closes #1098
Manually tested. Running `lerna botostrap` should show the warning message.
> Warn user and exit non-zero if command is invalid

- src/Command.js
Edited the error message to mention the possibility of git initialization failing due to the absence of a git binary.
The git binary might be missing in some environments, such as an Alpine Linux image used in a CI. 
Not tested
> fix: add other potential cause of git initialization failure

- doc/guides.md
Added docs/guides.md with instructions for debugging a single package's Jest tests in Visual Studio Code.
n/a
Sharing knowledge
n/a
> Add guide for debugging Jest tests with vscode

- src/FileSystemUtilities.js
- src/commands/BootstrapCommand.js
- src/commands/LinkCommand.js
- src/utils/create-symlink.js
- src/utils/resolve-symlink.js
- src/utils/symlink-binary.js
- src/utils/symlink-dependencies.js
- test/BootstrapCommand.js
- test/FileSystemUtilities.js
- test/LinkCommand.js
- test/__snapshots__/BootstrapCommand.js.snap
- test/utils-create-symlink.test.js
- test/utils-resolve-symlink.test.js
- test/utils-symlink-binary.test.js
* Refocused existing symlink utility
* Added more bootstrap --hoist snapshots
> Split symlink methods out of FileSystemUtilities

- src/commands/AddCommand.js
> fix(add): Configure `--dev` as boolean option

- utils/collect-updates/collect-updates.js
> fix(collect-updates): Remove redundant short-circuit

- README.md
I copy-pasted, then lightly edited, the response to the question in #1416.
This adds documentation to our woefully under-documented options.
I read it.
> docs: Describe lerna.json `packages` config option

- README.md
This adds documentation for the `clean` command when using the `--hoist` option, this addition was sparked from the discussion at #1304.
Improves documentation!
Only changes the README, tested using markdown preview.
> docs: Clarify `lerna clean` behaviour when using `--hoist`

- README.md
One small step towards #1283
document npmClientArgs on lerna.json
Added an example about how to declare npmClientArgs on lerna.json
Documentation needs improvement
Well, this is correct
> docs(readme): document npmClientArgs on lerna.json

- README.md
`$_` retrieves the last argument of the previous command.
`!$` retrieves the last argument of previous command in the shell
history.
https://unix.stackexchange.com/a/219627
I was walking through the `Getting Started` section and noticed that `mkdir lerna-repo && cd !$` did not work as expected.
N/A
> docs: Fix "Getting Started" code snippet

- commands/version/README.md
Just a small addition to the version-command docs
Trying out lerna for the first time, took me a while to find this option/flag.
First i did not want to publish anything to npm, otherwise i would have found it in the "lerna publish" docs.
> docs(version): document the —yes option

- README.md
> docs: add code formatting in Readme

- commands/clean/README.md
Clarified note about how `lerna clean` interacts with the `--hoist` option
This caused some confusion on our team. Without already having the context of what `--hoist` does, it sounded like the root `node_modules` directory _would_ be modified or deleted if you don't use `--hoist`.
n/a
n/a doc update
n/a doc update
> docs: Clarify interaction of `lerna clean` and hoisting

- doc/hoist.md
> docs: Fix typo

- commands/run/index.js
- commands/run/package.json
- integration/lerna-run.test.js
- package-lock.json
- utils/timer/README.md
- utils/timer/package.json
- utils/timer/timer.js
Fixes #1780
- Adds `@lerna/timer` utility to enable emitting timing information while maintaining test stability.
- Adds log statement in `runScriptInPackageCapturing` to output package name and time taken to run the task.
- Adds timing information to the overall execution of `lerna run`
#1780 
`npm link` and then used in local project.
Before:
```
± % lerna run test:lint
lerna notice cli v3.4.3
lerna info Executing command in 29 packages: "yarn run test:lint"
yarn run v1.10.1
$ tslint -c tslint.yml 'types/*'
Done in 1.17s.
yarn run v1.10.1
$ tslint -c tslint.yml 'types/*'
Done in 1.17s.
yarn run v1.10.1
$ tslint -c tslint.yml -p tsconfig.json
Done in 4.68s.
yarn run v1.10.1
$ tslint -c tslint.yml -p tsconfig.json
Done in 4.75s.
yarn run v1.10.1
$ tslint -c tslint.yml -p tsconfig.json …
```
> feat(run): Log package name and timing in runScriptInPackageCapturing

- commands/version/README.md
Fixed broken link to `--git-remote` option under `--push` option.
Improves usability of docs
Link redirected appropriately to the option specified.
> docs: Fix link to `--git-remote` option

- utils/npm-install/__tests__/npm-install.test.js
- utils/npm-install/npm-install.js
Fix https://github.com/lerna/lerna/issues/1775
> fix(bootstrap): Omit local bundled dependencies

- commands/clean/README.md
The words "have" and "the" were duplicated.
Noticed the duplication while reading docs.
n/a
> Removed duplicate words from clean README

- README.md
Possible clarification for Issue #1830
Added clarifying statement for **Common devDependencies** section in README.
Possible fix for Issue #1830 
N/A -- changed only README file
> docs: Update README with lerna link convert command

- core/command/index.js
- integration/lerna-add.test.js
- integration/lerna-bootstrap-ci.test.js
- integration/lerna-bootstrap-yarn.test.js
- integration/lerna-clean.test.js
- integration/lerna-exec.test.js
- integration/lerna-run.test.js
A tiny log message added as proposed in #1825
#1825
> feat(command): log whether CI environment has been detected

- utils/describe-ref/__tests__/describe-ref.test.js
- utils/describe-ref/lib/describe-ref.js
I ran into an issue trying to publish my changes. `describe-ref` would attempt to find the tags from the upstream, however it incorrectly treated the output as a "minimal sha" as if no tags were found.
This change more strictly checks for minimal sha output. I'm not 100% sure what the output is supposed to look like for these "minimal shas". However, the test I added matches the shape of my repo's tags, and the following is the output when trying to publish without these changes:
```
lerna ERR! Error: Command failed: git rev-list --count 20190107
[Step 2/3] lerna ERR! fatal: ambiguous argument '20190107': unknown revision or path not in the working tree.
[Step 2/3] lerna ERR! Use '--' to separate paths from revisions, like this:
[Step 2/3] lerna ERR! 'git <command> [<revision>...] -- …
```
> fix(describe-ref): properly handle sha-like tag names

- commands/version/README.md
Was reading the [`lerna version` documentation](https://github.com/lerna/lerna/tree/master/commands/version#readme) and these parts confused me, are they supposed to be `publish` or `version`? Can we also configure lerna versioning also by configuring publish on `lerna.json`?
Make documentation more clear
> docs(version): update to `version` command in examples

- core/filter-options/README.md
…lter-options
-- Add details  to `--ignore <glob>` and `--scope <glob>`
-- Fixes [1904](https://github.com/lerna/lerna/issues/1904)
Ran `npm i`, `lerna boostrap`, and `npm test` to verify all tests pass.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
> docs(filter-options): Add more examples of `--ignore` and `--scope`

- commands/publish/README.md
lifecycles during `lerna publish` isn't explained clearly in docs, see: https://github.com/lerna/lerna/issues/1978
> docs(publish): Explained publish lifecycles

- README.md
> docs: Use correct term for file structure

- commands/publish/README.md
> docs(publish): Fix typo

- doc/hoist.md
https://github.com/lerna/lerna/issues/2062
See linked GitHub issue above
Closes #2062 
n/a, just docs
> docs: Indicate that even single-use deps are hoisted

- README.md
Added a small disclaimer to the README about potential serverless monorepo incompatibility. Lerna is NOT a deployment tool! See #2077 
Lerna might be mistaken as a serverless monorepo tool, but it has incompatibilities with the deployment process due, in part, to hoisting.
N/A
> docs: Add disclaimer that Lerna is not a deployment tool

- README.md
This helps users identify which fields are no longer in use.
> docs: add legacy fields section to lerna.json

- commands/version/README.md
fixed tag-version-prefix link
It's just a small fix
It has tested manually
- [x ] Bug fix (non-breaking change which fixes an issue)
> docs(version): Fix typo in option header

- commands/version/README.md
> docs(version): remove unnecessary -

- CONTRIBUTING.md
Update instructions to use npm ci so tests pass, closes #2098
Tests would not pass after following the install instructions in CONTRIBUTING.md. I found another contributor experiencing the same problem, as well as a solution here https://github.com/lerna/lerna/issues/2098#issuecomment-494088031
I tried these instructions and tests immediately passed.
> docs: Update instructions to use npm ci

- FAQ.md
very small change - remove extra word. spacing changes were made by prettier.
just noticed it while reading the docs
N/A
> docs: Remove Extra Word / Tweak Spacing

- README.md
Update readme
- fixed typo
- removed trailing space
Fix typo
No code changes
> Update readme: fixed typo

- commands/version/README.md
improve markdown of Prerelease section in readme
> docs(version): improve Prerelease section of readme

- FAQ.md
> docs: Remove managed-root from FAQ.md

- README.md
Improve language in first paragraphe of README.md
> docs(readme): Improve phrasing

- commands/bootstrap/README.md
Just a note about incompatibilities with `bootstrap --hoist` and `file:` specifiers
Based on https://github.com/lerna/lerna/issues/1679#issuecomment-461544321
n/a
> docs(bootstrap): Add note about `--hoist` incompatibility with `file:` specifiers

- README.md
Just noticed the logo took a long time to load and optimized it through https://tinypng.com/.
Replaced the PNG used in the Readme by a less heavy one.
Make the page faster to load, avoid to load useless datas for users.
The change should be lossless.
> Optimize logo PNG (170kb to 80kb)

- commands/version/README.md
Fix links to "semver bump" section in README.
I noticed that some links were not working in the README and I decided to fix it right away.
n/a
> chore: Fix links in README

- README.md
Update the maintenance message of the repository and point to related message #3121.
Lerna will continue to live on!
> docs(chore): update maintenance message

- utils/npm-run-script/__tests__/npm-run-script.test.js
- utils/npm-run-script/npm-run-script.js
Reproduction of https://github.com/lerna/lerna/pull/2946 in order to get it merged in time for the 5.1 release, the original author has been fully credited in the commit data
> fix(utils): orphaned child process on Windows

- FAQ.md
> chore: fix typo

- README.md
the file is `lerna.json` not `Lerna.json`
> chore: update lerna.json casing in README

- commands/add/README.md
When reading the docs, I just noticed a small styling issue. Fixed for consistency.
Not required. Just noticed it, took 2 min to fix, and moving on. 
Because this only touches documentation, no testing has been done.
> chore: fix styling of --exact command in lerna add README

- commands/init/__tests__/init-command.test.js
- commands/init/index.js
- e2e/lerna-init/lerna-init.spec.ts
- integration/lerna-init.test.js
- package-lock.json
> chore: explicitly set useNx to false

- e2e/lerna-info/lerna-info.spec.ts
- e2e/lerna-list/lerna-list.spec.ts
- e2e/utils/index.ts
Add e2e tests to cover the lerna info & lerna list.
- Add end to end test cases for the lerna info command.
- Add end to end test cases for the lerna list command.
This change adds additional confidence in the consistent performance of lerna over time.
I began with failing e2e test cases, added the appropriate flag to the command run in the test, then confirmed that the test succeeded.
> chore(e2e): Add e2e tests for lerna info & lerna list

- e2e/lerna-exec/lerna-exec.spec.ts
Add e2e tests to cover lerna exec.
Add e2e tests to cover the lerna exec command.
This change adds additional confidence in the consistent performance of lerna over time.
I began with failing e2e test cases, added the appropriate flag to the command run in the test, then confirmed that the test succeeded.
> chore(e2e): Add e2e tests for lerna exec

- website/docs/getting-started.md
Fixes youtube iframe to allow fullscreen
> docs: youtube video allows full screen

- commands/run/index.js
> fix: lerna run parallel should maximize concurrency with useNx

- e2e/tests/lerna-changed/lerna-changed.spec.ts
- e2e/tests/lerna-exec/lerna-exec.spec.ts
- e2e/tests/lerna-info/lerna-info.spec.ts
- e2e/tests/lerna-init/lerna-init.spec.ts
- e2e/tests/lerna-list/lerna-list-filter-options.spec.ts
- e2e/tests/lerna-list/lerna-list.spec.ts
- e2e/tests/lerna-run/lerna-run.spec.ts
- e2e/tests/lerna-version/errors.spec.ts
- e2e/tests/lerna-version/semver-keywords.spec.ts
- e2e/utils/fixture.ts
- lerna.json
- package-lock.json
(Also updates the creation of fixtures to reduce the need to repeat the same few setup methods over and over for most cases)
> chore: add some initial e2e coverage for version

- website/docusaurus.config.js
It enables the search feature on lerna.js.org via Algolia.
> docs(website): enable search

- e2e/tests/lerna-clean/lerna-clean.spec.ts
- e2e/tests/lerna-diff/lerna-diff.spec.ts
Add a couple e2e tests to cover `clean` and `diff`.
This change adds additional confidence in the consistent performance of lerna over time.
> chore(e2e): add tests for clean and diff

- website/docs/getting-started.md
> chore: Typo in readme (getting-started)

- commands/version/index.js
> fix(version): inherit stdio for lerna version lifecycle scripts

- .github/workflows/ci.yml
- nx.json
- package-lock.json
- package.json
> chore(repo): enable nx cloud to speed up the build

- e2e/tests/lerna-create/lerna-create.spec.ts
- e2e/utils/fixture.ts
Adds end to end tests for the `lerna create` command. Also adds support to the test fixture for commands making network requests.
These tests increase confidence in the consistent behavior of lerna over time.
> chore(e2e): e2e tests for lerna create

- e2e/tests/lerna-publish/lerna-publish-npm.spec.ts
- e2e/tests/lerna-publish/lerna-publish-yarn.spec.ts
- e2e/utils/fixture.ts
Adds a couple end to end tests for `lerna publish`.
Adds end to end tests for `lerna publish` that cover specifying registry with --registry and .npmrc file, for both npm and yarn.
These tests improve confidence in lerna's consistent behavior over time.
> chore(e2e): basic publish e2e tests for npm config

- website/src/components/about-lerna.tsx
Removes a repeated word occurrence that creates unusal emphasis in expression
> Docs: fix a typo on home page

- commands/version/index.js
- e2e/tests/lerna-version/npm-workspaces.spec.ts
Updates the package-lock file in the root after running `lerna version`.
This removes the need to manually update the package lock file after a new version is tagged.
I have tested this manually on the lerna repo itself. It is also covered by end to end tests.
> fix(version): update package-lock at the root if it exists

- website/docusaurus.config.js
It adds an announcement bar on the top of the website about NxConf Lerna's talks.
> chore(website): add announcement banner lerna talks

- website/docs/api-reference/configuration.md
This PR fixes a typo in an example on the api-reference/configuration page of the website.
Shameless attempt to be listed as contributor for simply proof-reading.
The example does not work as expected unless this change is applied.
> chore(website): fix typo on configuration page

- commands/version/README.md
Added `GH_TOKEN` scope requirements for creating github release by `lerna version`.
No clear `GH_TOKEN` scope requirements for creating github release results in back and forth debugging.  
Not applicable
> docs(version): add GH_TOKEN scope requirements for --create-release option

- commands/run/index.js
Update deprecated nx arg _ to __overrides__.
_ is deprecated and __overrides__ is preferred.
> chore(run): Update deprecated nx arg _ to __overrides__

- website/docs/getting-started.md
fixing command in `website/docs/getting-started.md`
> chore: update getting-started.md

- commands/run/package.json
- package-lock.json
The `fs-extra` dependency is missing when `lerna run` is executed. 
This dependency must be declared and installed
> fix(run): missing `fs-extra` dependency declaration

- e2e/tests/lerna-run/lerna-run-nx-pnpm.spec.ts
- e2e/utils/fixture.ts
Configures a local store for pnpm in the e2e tests. 
This prevents integrity issues in the global store due to re-downloading different files for the same version of lerna between different e2e runs.
All e2e tests still pass.
> chore(e2e): use local store for pnpm in e2e tests

- website/docs/getting-started.md
- References the [Lerna Walkthrough video](https://youtu.be/1oxFYphTS4Y)
- Updates the Getting Started Guide to the v6 changes
> docs(core): update getting started with latest Lerna changes

- website/package-lock.json
- website/package.json
- website/src/components/about-lerna.tsx
- website/src/components/hero-lerna.tsx
It upgrades the HeroIcons dependencies to the latest version. This version has new freshly redesigned icons, and components have been updated to reflect breaking changes.
> docs(website): upgrade heroicons dependency to 2.0.12

- website/package-lock.json
- website/package.json
It upgrades Docusaurus dependencies to the latest version `2.2.0`.
> docs(website): upgrade docusaurus dependencies to 2.2.0

- CHANGELOG.md
> Typo 'serious' to 'series'

- website/docs/features/version-and-publish.md
> Lerna comes with a `version` that allows...
Grammar is incorrect here.
Add command after `version`, to read as:
> Lerna comes with a `version` command that allows...
No.
> fix: grammar for version command

- website/src/components/hero-upgrade.tsx
fixes npm install command on the lerna upgrade docs page
> docs(website): fix lerna install command

- website/docusaurus.config.js
> docs(website): update YT link

- e2e/publish/src/publish-pnpm-workspace-prefix.spec.ts
- libs/e2e-utils/src/lib/fixture.ts
Adds e2e tests for workspace prefix support with pnpm.
> chore(e2e): fill in e2e tests for workspace prefix with pnpm

- commands/run/package.json
- package-lock.json
Adds an explicit dependency on Nx to @lerna/run.
#3481
This has been tested manually against the repo from issue #3481 as well as a barebones reproduction workspace.
> fix(run): add explicit nx dependency

- core/lerna/commands/watch/README.md
- website/docs/api-reference/commands.md
- website/docs/features/workspace-watching.md
- website/sidebars.js
Adds a Workspace Watching feature overview with examples to the lerna.js.org website. 
This helps promote discovery of the new Workspace Watching feature and makes api reference more accessible.
> chore(docs): add workspace watching feature doc

- website/docusaurus.config.js
> chore(docs): remove state of js banner

- commands/run/package.json
- core/lerna/commands/repair/index.js
- package-lock.json
Bump the nx version required by @lerna/run to match the rest of lerna.
#3491
Mismatched versions of Nx in node_modules appear to be causing an issue when running tasks.
Existing e2e tests pass. I have verified that #3491 is resolved locally with these changes.
> fix(run): bump nx version

- core/filter-options/README.md
Updates the docs to correctly specify that quotes are needed around glob arguments and that an explicit "=" must be used with npx to prevent premature substitution.
This fix clarifies common pitfalls when running lerna with --scope and npx.
> chore(docs): update filter options docs to specify quote necessity

- libs/commands/add/README.md
- libs/commands/bootstrap/README.md
- libs/commands/changed/README.md
- libs/commands/clean/README.md
- libs/commands/create/README.md
- libs/commands/diff/README.md
- libs/commands/exec/README.md
- libs/commands/import/README.md
- libs/commands/init/README.md
- libs/commands/link/README.md
- libs/commands/publish/README.md
- libs/commands/run/README.md
- libs/commands/version/README.md
- packages/child-process/README.md
- website/docs/api-reference/commands.md
- website/docs/features/version-and-publish.md
- website/docs/features/workspace-watching.md
Some consistency points and broken links post refactor
> chore: update docs

- .github/workflows/ci.yml
- libs/commands/run/README.md
- package-lock.json
- package.json
- tools/scripts/build.sh
Adds a note to the docs, warning users about using Yarn with `lerna run -- args`. 
This is needed because it is currently unclear why `yarn lerna run test -- --myarg` won't correctly pass `--myarg` to the `test` script.
#3510
> chore(run): warn in docs about using yarn and passing args to lerna run

- packages/lerna/src/commands/watch/README.md
- website/docs/features/workspace-watching.md
Adds an example to the docs on how to use lerna watch to rebuild dependent packages when one changes.
> chore(docs): add lerna watch -- build --include-dependents example

- .github/workflows/ci.yml
- package-lock.json
- package.json
> Revert "chore: bump nx-cloud"

- website/docusaurus.config.js
> adding 6.5 video banner link to lerna docs

- doc/troubleshooting.md
I propose to update a little typo on the troubleshooting documentation regarding the `--conventional-commits` option.
In order to help people without error.
> docs: update `troubleshooting.md` typo

- libs/commands/publish/__fixtures__/lerna-version-mocks.ts
- libs/commands/publish/src/lib/publish-command.spec.ts
- libs/commands/publish/src/lib/publish-licenses.spec.ts
- libs/commands/publish/src/lib/publish-lifecycle-scripts.spec.ts
- libs/commands/publish/src/lib/publish-relative-file-specifiers.spec.ts
- libs/commands/publish/src/lib/publish-tagging.spec.ts
Puts all needed version command mocks in a common place.
Puts all needed version command mocks in a common place.
Avoid code duplication for test setup. 
All tests still pass.
> refactor(publish): add common version command utils test fixture

- CHANGELOG.md
- libs/commands/publish/src/index.ts
- packages/child-process/CHANGELOG.md
- packages/legacy-package-management/CHANGELOG.md
- packages/legacy-structure/commands/create/CHANGELOG.md
- packages/lerna/CHANGELOG.md
Uses the correct key when looking up versions for confirmation.
> fix(publish): use correct version in log messages

- libs/core/src/lib/command/index.ts
#3719 
This has been tested manually.
> fix(core): reset nx daemon after command finishes

- libs/core/src/index.ts
- libs/core/src/lib/command/detect-projects.ts
- libs/core/src/lib/command/index.ts
- packages/lerna/package.json
- packages/lerna/project.json
- packages/lerna/src/utils/create-project-graph-with-packages.ts
- packages/lerna/src/utils/detect-projects.ts
- packages/lerna/src/utils/index.ts
- website/docs/api-reference/utilities.md
- website/sidebars.js
Exports the detectProjects() function used by Lerna.
This allows external tooling to operate on the same project graph that Lerna does:
```js
const { detectProjects } = require("lerna/utils");
const { projectGraph, projectFileMap } = await detectProjects();
```
#3721
This has been tested manually.
> feat(core): export detectProjects utility function

- libs/commands/publish/src/index.ts
Ensure the error code ends up as a number.
Node will throw a different error if the process error code is not a number, which conceals the original error.
#3693 
This has been tested manually.
> fix(publish): ensure that error code is a number

- website/docs/legacy-package-management.md
Document an issue with yarn not linking binaries.
#3737
> chore(bootstrap): document yarn issue with linking binaries

- packages/lerna/package.json
> fix(core): Export cli.js for global installs

- package-lock.json
- packages/lerna/package.json
This PR adds a missing `lodash` dependency to the `lerna` package.
Resolves https://github.com/lerna/lerna/issues/3777.
N/A
> fix: add missing lodash dependency

- libs/commands/version/src/lib/git-add.ts
Removes the explicit require on a node_modules path for prettier.
This allows the required prettier to follow the normal node rules for importing modules, which also allows it to support Yarn PnP.
This has been tested manually. All automated tests pass.
> fix(version): remove explicit node_modules require

- libs/commands/init/README.md
- libs/commands/init/src/index.ts
Infer the invoked package manager (pnpx, yarn dlx, npx) if no lockfile exists.
This allows users to create fresh Lerna workspaces with their package manager of choice.
This has been tested manually.
> feat(init): infer invoked pkg mgr

- libs/core/src/lib/run-projects-topologically.spec.ts
- libs/core/src/lib/run-projects-topologically.ts
Gracefully exit when a cycle outside the scope of projects to run is encountered.
#3803 
This was tested manually and is covered by a unit test.
> fix(core): gracefully ignore cycles outside scope to run

- website/docs/features/version-and-publish.md
Is this typo? 
Since the example app does mark private in package.json
ref: https://github.com/lerna/getting-started-example/blob/2e37c43fbbd4f1fc050a766d6585f88d4ef3f79d/packages/remixapp/package.json#L4C19-L4C19
Match example repo's package private status with doc.
May fix paradox between two doc 
N/A
- [ x] Chore (change that has absolutely no effect on users)
- [ x] My change requires a change to the documentation.
- [ x] I have read the **CONTRIBUTING** document.
> docs: Update version-and-publish.md

- package-lock.json
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
Update make-dir to 4.0.0 and run npm audit fix
#3826
All existing automated tests pass.
> fix: update make-dir to 4.0.0 and npm audit fix

- libs/core/src/lib/cycles/get-cycles.spec.ts
- libs/core/src/lib/cycles/get-cycles.ts
- libs/core/src/lib/run-projects-topologically.spec.ts
- libs/core/src/lib/run-projects-topologically.ts
- libs/core/src/lib/toposort-projects.spec.ts
- libs/core/src/lib/toposort-projects.ts
Skip unnecessary cycles when running tasks.
Without this, the `runProjectsTopologically` function can get "stuck" when there are cycles. It could pick a cycle that doesn't have any projects to run, causing it to exit without running all tasks. See #3798
This has been covered by unit tests.
> fix(core): skip unnecessary cycles when running tasks

- e2e/version/src/npm-workspaces.spec.ts
Add e2e test for new --run-scripts-on-lockfile-update option.
> chore(version): add e2e test for --run-scripts-on-lockfile-update

- .gitignore
Excludes nested package node_modules from git.
> chore: exclude package node_modules from git

- libs/commands/diff/src/index.ts
- libs/commands/diff/src/lib/get-last-commit.ts
- libs/commands/diff/src/lib/has-commit.ts
- libs/commands/diff/tsconfig.json
- libs/core/src/index.ts
- libs/core/src/lib/command/index.ts
Removed some ts-ignore comments and any types
Make diff command lib more typesafe
Existing unit and regression test.
> chore(diff): enable strict type checking for diff command

- libs/commands/version/README.md
Clarifies behaviour in #3727
#3727
> docs(version): udpate force-publish documentation for conventional workflow

- e2e/version/src/conventional-commits.spec.ts
- libs/commands/changed/README.md
- libs/commands/changed/src/command.ts
- libs/commands/changed/src/index.ts
- libs/commands/version/README.md
- libs/commands/version/src/command.ts
- libs/commands/version/src/index.ts
- libs/core/src/lib/collect-updates/collect-project-updates.spec.ts
- libs/core/src/lib/collect-updates/collect-project-updates.ts
- packages/lerna/schemas/lerna-schema.json
- when using --conventional-commits and --conventional-graduate
Solves #3727
#3727
UnitTests and e2e tests added
> feat(version): add option to force version update

- package-lock.json
Regenerate package-lock file to restore 'resolved' and 'integrity' properties.
#3843
> chore(core): regenerate package-lock file to restore resolved/integrity

- libs/commands/info/src/command.ts
remove some eslint warings
all test pass
> chore(info): use import instead of require

- package-lock.json
- package.json
- tools/scripts/build.sh
- Pins verdaccio at 5.19.0, as the latest versions of verdaccio are crashing when trying to write output during package publishing.
- Performs npm install within `build.sh` to ensure that the `lerna` executable has been properly linked after the build. This is necessary because the first `npm install` in a freshly-cloned Lerna repo cannot link this executable due to no build having been run yet.
This has been tested locally.
> chore: fix e2e tests

- .github/workflows/other-node-versions.yml
- package-lock.json
- package.json
- packages/child-process/__tests__/child-process.test.js
- packages/child-process/index.js
- packages/child-process/package.json
- packages/child-process/set-exit-code.js
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
Drop support for Node 16, update CI to test node versions 18 and 20.
Node 16 reached end of life in August 2023 (https://endoflife.date/nodejs).
All existing automated tests pass.
> chore: drop support for Node 16

- package-lock.json
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
FIxes https://github.com/lerna/lerna/issues/3605
> fix: update node-gyp usage to v10 to resolve npm warning

- libs/core/src/lib/command/index.ts
- package-lock.json
- package.json
use correct type definitions
avoid as any
all tests still pass
> chore: update npmlog types

- website/docs/lerna-and-nx-version-matrix.md
Update the Nx/Lerna version matrix to include Lerna 8 and Nx 17
The version chart is outdated.
All existing tests pass.
> chore(docs): update nx and Lerna version matrix

- libs/core/src/lib/command/index.ts
Fixes:  #3557
I haven't test it but seems it's just changing a string :D
> fix: improve git binary error

- package-lock.json
- packages/legacy-package-management/package.json
- packages/legacy-structure/commands/create/package.json
- packages/lerna/package.json
> fix(publish): upgrade @npmcli/arborist to 7.5.4

- website/docs/features/run-tasks.md
- website/docs/lerna-and-nx.md
Hello, I've fixed some simple typos in the official documents.
1. Github -> GitHub
2. Add a punctuation.
3. Add inline code block: .env -> `.env`
> docs: fixed some typos

- website/docs/features/distribute-tasks.md
Hello, I've fixed some broken links and added some links in `distribute-tasks.md`
First, The links below are not available. So I've fixed it using the links in [Nx Docs](https://nx.dev/ci/recipes/set-up).
And `#distributed-ci-with-nx-cloud` fragments are not available anymore... So I deleted them.
```text
- [Overview](https://nx.dev/recipes/ci/ci-setup#distributed-ci-with-nx-cloud)
- [Azure Pipelines](https://nx.dev/recipes/ci/monorepo-ci-azure#distributed-ci-with-nx-cloud)
- [Circle CI](https://nx.dev/recipes/ci/monorepo-ci-circle-ci#distributed-ci-with-nx-cloud)
- [GitHub Actions](https://nx.dev/recipes/ci/monorepo-ci-github-actions#distributed-ci-with-nx-cloud)
- [Jenkins](https://nx.dev/recipes/ci/monorepo-ci-jenkins#distributed-ci-with-nx-cloud)
```
And I added `GitLab` and …
> docs: fix broken links and add some links in `distribute-tasks.md`

- libs/commands/import/README.md
Hello, I've fixed some typos in `import/README.md`.
1. Wrap `lerna.json` with an inline code block.
Since, `package.json` is also wrapped in an inline code block, I did the same to the `lerna.json`.
1. Github => GitHub
> docs: fix simple typos in `import/README.md`

- README.md
> docs(readme): added a link and badge to Twitter

- website/docs/features/editor-integrations.md
> docs(misc): update nx console docs
